// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project cde98c358c3069ef "matt.buzz", do not edit manually */
"use client";

/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
}} Props

 */
import { className, css, fonts } from "./chunks/chunk-GCG4FXA2.js";
import { stdin_default } from "./chunks/chunk-YYMSPGWM.js";
import "./chunks/chunk-NB4Q2TMV.js";
import { routes } from "./chunks/chunk-54YFTX6O.js";

// virtual:404
import { Fragment as Fragment2 } from "react";
import { ContextProviders } from "unframer";

// /:https://framerusercontent.com/modules/qGpjDWbMcK4Ge1Obw54P/WiWzVGhE1ZtY2iVKFZJU/ilrcliDPo.js
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import {
	addFonts,
	addPropertyControls,
	ComponentViewportProvider,
	ControlType,
	cx,
	getFonts,
	getFontsFromSharedStyle,
	ResolveLinks,
	RichText,
	SmartComponentScopedContainer,
	useComponentViewport,
	useLocaleInfo,
	useRouter,
	useVariantState,
	withCSS,
} from "unframer";
import { LayoutGroup, motion, MotionConfigContext } from "unframer";
import * as React from "react";
import { useRef } from "react";

// /:https://framerusercontent.com/modules/7YhqvrlZMGt08Fi7zmua/GJ0tePLn1FvSsNt08gyb/UFkngxFNd.js
import { fontStore } from "unframer";
fontStore.loadFonts(["BI;Open Sauce Sans/Medium/v0"]);
var fonts2 = [
	{
		explicitInter: true,
		fonts: [
			{
				family: "Open Sauce Sans",
				source: "builtIn",
				style: "normal",
				url: "https://framerusercontent.com/assets/O2R7AhA6wjBk0GHLJl0N8fqxN0.woff2",
				weight: "500",
			},
		],
	},
];
var css2 = [
	'.framer-M7N0k .framer-styles-preset-1pku1h6:not(.rich-text-wrapper), .framer-M7N0k .framer-styles-preset-1pku1h6.rich-text-wrapper p { --framer-font-family: "Open Sauce Sans", "Open Sauce Sans Placeholder", sans-serif; --framer-font-open-type-features: normal; --framer-font-size: 300px; --framer-font-style: normal; --framer-font-variation-axes: normal; --framer-font-weight: 500; --framer-letter-spacing: -0.02em; --framer-line-height: 1em; --framer-paragraph-spacing: 0px; --framer-text-alignment: center; --framer-text-color: var(--token-5fde730a-8086-4528-a317-d71b3bf4efde, #000000); --framer-text-decoration: none; --framer-text-stroke-color: initial; --framer-text-stroke-width: initial; --framer-text-transform: none; }',
	'@media (max-width: 1439px) and (min-width: 1025px) { .framer-M7N0k .framer-styles-preset-1pku1h6:not(.rich-text-wrapper), .framer-M7N0k .framer-styles-preset-1pku1h6.rich-text-wrapper p { --framer-font-family: "Open Sauce Sans", "Open Sauce Sans Placeholder", sans-serif; --framer-font-open-type-features: normal; --framer-font-size: 300px; --framer-font-style: normal; --framer-font-variation-axes: normal; --framer-font-weight: 500; --framer-letter-spacing: -0.02em; --framer-line-height: 1em; --framer-paragraph-spacing: 0px; --framer-text-alignment: center; --framer-text-color: var(--token-5fde730a-8086-4528-a317-d71b3bf4efde, #000000); --framer-text-decoration: none; --framer-text-stroke-color: initial; --framer-text-stroke-width: initial; --framer-text-transform: none; } }',
	'@media (max-width: 1024px) and (min-width: 700px) { .framer-M7N0k .framer-styles-preset-1pku1h6:not(.rich-text-wrapper), .framer-M7N0k .framer-styles-preset-1pku1h6.rich-text-wrapper p { --framer-font-family: "Open Sauce Sans", "Open Sauce Sans Placeholder", sans-serif; --framer-font-open-type-features: normal; --framer-font-size: 200px; --framer-font-style: normal; --framer-font-variation-axes: normal; --framer-font-weight: 500; --framer-letter-spacing: -0.02em; --framer-line-height: 1em; --framer-paragraph-spacing: 0px; --framer-text-alignment: center; --framer-text-color: var(--token-5fde730a-8086-4528-a317-d71b3bf4efde, #000000); --framer-text-decoration: none; --framer-text-stroke-color: initial; --framer-text-stroke-width: initial; --framer-text-transform: none; } }',
	'@media (max-width: 699px) and (min-width: 0px) { .framer-M7N0k .framer-styles-preset-1pku1h6:not(.rich-text-wrapper), .framer-M7N0k .framer-styles-preset-1pku1h6.rich-text-wrapper p { --framer-font-family: "Open Sauce Sans", "Open Sauce Sans Placeholder", sans-serif; --framer-font-open-type-features: normal; --framer-font-size: 120px; --framer-font-style: normal; --framer-font-variation-axes: normal; --framer-font-weight: 500; --framer-letter-spacing: -0.02em; --framer-line-height: 1em; --framer-paragraph-spacing: 0px; --framer-text-alignment: center; --framer-text-color: var(--token-5fde730a-8086-4528-a317-d71b3bf4efde, #000000); --framer-text-decoration: none; --framer-text-stroke-color: initial; --framer-text-stroke-width: initial; --framer-text-transform: none; } }',
];
var className2 = "framer-M7N0k";

// /:https://framerusercontent.com/modules/qGpjDWbMcK4Ge1Obw54P/WiWzVGhE1ZtY2iVKFZJU/ilrcliDPo.js
var LinkFonts = getFonts(stdin_default);
var cycleOrder = ["x3DLK7_jB", "B8Peoi3Xd", "knjqFHLGo", "zPPoD3gsW"];
var serializationHash = "framer-RmwsW";
var variantClassNames = {
	B8Peoi3Xd: "framer-v-t5l8tz",
	knjqFHLGo: "framer-v-u9vrxm",
	x3DLK7_jB: "framer-v-kswgkd",
	zPPoD3gsW: "framer-v-16c3fur",
};
function addPropertyOverrides(overrides, ...variants) {
	const nextOverrides = {};
	variants?.forEach(
		(variant) => variant && Object.assign(nextOverrides, overrides[variant]),
	);
	return nextOverrides;
}
var transition1 = {
	bounce: 0.2,
	delay: 0,
	duration: 0.4,
	type: "spring",
};
var Transition = ({ value, children }) => {
	const config = React.useContext(MotionConfigContext);
	const transition = value ?? config.transition;
	const contextValue = React.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext.Provider value={contextValue}>
			{children}
		</MotionConfigContext.Provider>
	);
};
var Variants = motion.create(React.Fragment);
var humanReadableVariantMap = {
	Desktop: "x3DLK7_jB",
	Laptop: "B8Peoi3Xd",
	Phone: "zPPoD3gsW",
	Tablet: "knjqFHLGo",
};
var getProps = ({ height, id, width, ...props }) => {
	return {
		...props,
		variant:
			humanReadableVariantMap[props.variant] ?? props.variant ?? "x3DLK7_jB",
	};
};
var createLayoutDependency = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
	const fallbackRef = useRef(null);
	const refBinding = ref ?? fallbackRef;
	const defaultLayoutId = React.useId();
	const { activeLocale, setLocale } = useLocaleInfo();
	const componentViewport = useComponentViewport();
	const {
		style,
		className: className3,
		layoutId,
		variant,
		...restProps
	} = getProps(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState({
		cycleOrder,
		defaultVariant: "x3DLK7_jB",
		ref: refBinding,
		variant,
		variantClassNames,
	});
	const layoutDependency = createLayoutDependency(props, variants);
	const sharedStyleClassNames = [className2, className];
	const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
	const router = useRouter();
	return (
		<LayoutGroup id={layoutId ?? defaultLayoutId}>
			<Variants animate={variants} initial={false}>
				<Transition value={transition1}>
					<motion.main
						{...restProps}
						{...gestureHandlers}
						className={cx(
							scopingClassNames,
							"framer-kswgkd",
							className3,
							classNames,
						)}
						data-framer-name={"Desktop"}
						layoutDependency={layoutDependency}
						layoutId={"x3DLK7_jB"}
						ref={refBinding}
						style={{
							...style,
						}}
						{...addPropertyOverrides(
							{
								B8Peoi3Xd: {
									"data-framer-name": "Laptop",
								},
								knjqFHLGo: {
									"data-framer-name": "Tablet",
								},
								zPPoD3gsW: {
									"data-framer-name": "Phone",
								},
							},
							baseVariant,
							gestureVariant,
						)}
					>
						<motion.header
							className={"framer-1t8wqb2"}
							data-framer-name={"Header"}
							layoutDependency={layoutDependency}
							layoutId={"nQtscwmOK"}
						>
							<motion.div
								className={"framer-1t7e88e"}
								data-framer-name={"Box"}
								layoutDependency={layoutDependency}
								layoutId={"tEIM1ADV5"}
								style={{
									borderBottomLeftRadius: 32,
									borderBottomRightRadius: 32,
									borderTopLeftRadius: 32,
									borderTopRightRadius: 32,
									boxShadow:
										"inset 0px 1px 0px 1px var(--token-4ad2450b-089e-49a2-b079-884bae7e4c6d, rgba(255, 255, 255, 0.06))",
								}}
								variants={{
									zPPoD3gsW: {
										borderBottomLeftRadius: 24,
										borderBottomRightRadius: 24,
										borderTopLeftRadius: 24,
										borderTopRightRadius: 24,
									},
								}}
							>
								<motion.div
									className={"framer-1qqmlu3"}
									data-framer-name={"Text"}
									layoutDependency={layoutDependency}
									layoutId={"GE6PLgwAo"}
								>
									<RichText
										__fromCanvasComponent={true}
										className={"framer-82grua"}
										data-framer-name={"Text"}
										fonts={["Inter"]}
										layoutDependency={layoutDependency}
										layoutId={"Omt0PF2wI"}
										style={{
											"--framer-link-text-color": "rgb(0, 153, 255)",
											"--framer-link-text-decoration": "underline",
										}}
										verticalAlignment={"top"}
										withExternalLayout={true}
									>
										<React.Fragment>
											<motion.p
												className={"framer-styles-preset-1pku1h6"}
												data-styles-preset={"UFkngxFNd"}
											>
												{"404"}
											</motion.p>
										</React.Fragment>
									</RichText>
									<RichText
										__fromCanvasComponent={true}
										className={"framer-eadeyi"}
										data-framer-name={"Text"}
										fonts={["Inter"]}
										layoutDependency={layoutDependency}
										layoutId={"hc15gMX6y"}
										style={{
											"--framer-link-text-color": "rgb(0, 153, 255)",
											"--framer-link-text-decoration": "underline",
										}}
										verticalAlignment={"top"}
										withExternalLayout={true}
										{...addPropertyOverrides(
											{
												zPPoD3gsW: {
													children: (
														<React.Fragment>
															<motion.p
																className={"framer-styles-preset-1jepal"}
																data-styles-preset={"LM8JVdUMr"}
																style={{
																	"--framer-text-alignment": "center",
																}}
															>
																{
																	"It seems like this page doesn't exist, or it's gone. But don't worry! I'll get you back on track :)"
																}
															</motion.p>
														</React.Fragment>
													),
												},
											},
											baseVariant,
											gestureVariant,
										)}
									>
										<React.Fragment>
											<motion.p
												className={"framer-styles-preset-1jepal"}
												data-styles-preset={"LM8JVdUMr"}
												style={{
													"--framer-text-alignment": "center",
												}}
											>
												{"It seems like this page doesn't exist, or it's gone."}
												<motion.br />
												{"But don't worry! I'll get you back on track :)"}
											</motion.p>
										</React.Fragment>
									</RichText>
								</motion.div>
								<ResolveLinks
									links={[
										{
											href: {
												webPageId: "augiA20Il",
											},
											implicitPathVariables: void 0,
										},
										{
											href: {
												webPageId: "augiA20Il",
											},
											implicitPathVariables: void 0,
										},
										{
											href: {
												webPageId: "augiA20Il",
											},
											implicitPathVariables: void 0,
										},
										{
											href: {
												webPageId: "augiA20Il",
											},
											implicitPathVariables: void 0,
										},
									]}
								>
									{(resolvedLinks) => (
										<ComponentViewportProvider
											height={29}
											y={
												(componentViewport?.y || 0) +
												0 +
												(((componentViewport?.height || 200) - 0 - 900) / 2 +
													0 +
													0) +
												-466.5 +
												64 +
												1676
											}
											{...addPropertyOverrides(
												{
													knjqFHLGo: {
														y:
															(componentViewport?.y || 0) +
															0 +
															(((componentViewport?.height || 200) - 0 - 900) /
																2 +
																0 +
																0) +
															-450.5 +
															48 +
															1676,
													},
													zPPoD3gsW: {
														y:
															(componentViewport?.y || 0) +
															0 +
															(((componentViewport?.height || 200) - 0 - 1785) /
																2 +
																0 +
																0) +
															0 +
															48 +
															1660,
													},
												},
												baseVariant,
												gestureVariant,
											)}
										>
											<SmartComponentScopedContainer
												className={"framer-17gxhcb-container"}
												layoutDependency={layoutDependency}
												layoutId={"EHwXtw6WE-container"}
												nodeId={"EHwXtw6WE"}
												rendersWithMotion={true}
												scopeId={"ilrcliDPo"}
											>
												{_jsx(stdin_default, {
													gaudSAYyV: resolvedLinks[0],
													gnxB9JgXH: "Back to Home",
													height: "100%",
													id: "EHwXtw6WE",
													Ke1ihOPDv: false,
													layoutId: "EHwXtw6WE",
													variant: "JpxTAmqKP",
													width: "100%",
													...addPropertyOverrides(
														{
															B8Peoi3Xd: {
																gaudSAYyV: resolvedLinks[1],
															},
															knjqFHLGo: {
																gaudSAYyV: resolvedLinks[2],
															},
															zPPoD3gsW: {
																gaudSAYyV: resolvedLinks[3],
																variant: "gZZq7oJv9",
															},
														},
														baseVariant,
														gestureVariant,
													),
												})}
											</SmartComponentScopedContainer>
										</ComponentViewportProvider>
									)}
								</ResolveLinks>
								<motion.div
									className={"framer-sy1dyw"}
									data-framer-name={"BG"}
									layoutDependency={layoutDependency}
									layoutId={"I9xKSHMmW"}
									style={{
										backgroundColor:
											"var(--token-5fde730a-8086-4528-a317-d71b3bf4efde, rgb(0, 0, 0))",
										opacity: 0.08,
									}}
								/>
							</motion.div>
						</motion.header>
					</motion.main>
				</Transition>
			</Variants>
		</LayoutGroup>
	);
});
var css3 = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-RmwsW.framer-153au4j, .framer-RmwsW .framer-153au4j { display: block; }",
	".framer-RmwsW.framer-kswgkd { align-content: center; align-items: center; display: flex; flex-direction: column; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: center; max-width: 1920px; overflow: hidden; padding: 0px; position: relative; width: 1440px; }",
	".framer-RmwsW .framer-1t8wqb2 { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: 900px; justify-content: center; max-width: 1200px; overflow: hidden; padding: 0px; position: relative; width: 80%; }",
	".framer-RmwsW .framer-1t7e88e { align-content: center; align-items: center; display: flex; flex: 1 0 0px; flex-direction: column; flex-wrap: nowrap; gap: 48px; height: min-content; justify-content: center; overflow: hidden; padding: 64px; position: relative; width: 1px; will-change: var(--framer-will-change-override, transform); }",
	".framer-RmwsW .framer-1qqmlu3 { align-content: center; align-items: center; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 16px; height: min-content; justify-content: center; overflow: hidden; padding: 0px; position: relative; width: 100%; z-index: 2; }",
	".framer-RmwsW .framer-82grua, .framer-RmwsW .framer-eadeyi { flex: none; height: auto; position: relative; white-space: pre-wrap; width: 100%; word-break: break-word; word-wrap: break-word; z-index: 2; }",
	".framer-RmwsW .framer-17gxhcb-container { flex: none; height: auto; position: relative; width: auto; z-index: 2; }",
	".framer-RmwsW .framer-sy1dyw { bottom: 0px; flex: none; left: 0px; overflow: hidden; position: absolute; right: 0px; top: 0px; z-index: 1; }",
	".framer-RmwsW.framer-v-t5l8tz.framer-kswgkd { width: 1025px; }",
	".framer-RmwsW.framer-v-u9vrxm.framer-kswgkd { padding: 0px 24px 0px 24px; width: 200px; }",
	".framer-RmwsW.framer-v-u9vrxm .framer-1t8wqb2 { width: 100%; }",
	".framer-RmwsW.framer-v-u9vrxm .framer-1t7e88e { padding: 48px; }",
	".framer-RmwsW.framer-v-16c3fur.framer-kswgkd { padding: 0px 16px 0px 16px; width: 200px; }",
	".framer-RmwsW.framer-v-16c3fur .framer-1t8wqb2 { height: min-content; width: 100%; }",
	".framer-RmwsW.framer-v-16c3fur .framer-1t7e88e { gap: 32px; padding: 48px; }",
	...css2,
	...css,
];
var FramerilrcliDPo = withCSS(Component, css3, "framer-RmwsW");
var stdin_default2 = FramerilrcliDPo;
FramerilrcliDPo.displayName = "404";
FramerilrcliDPo.defaultProps = {
	height: 900,
	width: 1440,
};
addPropertyControls(FramerilrcliDPo, {
	variant: {
		options: ["x3DLK7_jB", "B8Peoi3Xd", "knjqFHLGo", "zPPoD3gsW"],
		optionTitles: ["Desktop", "Laptop", "Tablet", "Phone"],
		title: "Variant",
		type: ControlType.Enum,
	},
});
addFonts(
	FramerilrcliDPo,
	[
		{
			explicitInter: true,
			fonts: [
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
					url: "https://framerusercontent.com/assets/5vvr9Vy74if2I6bQbJvbw7SY1pQ.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
					url: "https://framerusercontent.com/assets/EOr0mi4hNtlgWNn9if640EZzXCo.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+1F00-1FFF",
					url: "https://framerusercontent.com/assets/Y9k9QrlZAqio88Klkmbd8VoMQc.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+0370-03FF",
					url: "https://framerusercontent.com/assets/OYrD2tBIBPvoJXiIHnLoOXnY9M.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
					url: "https://framerusercontent.com/assets/JeYwfuaPfZHQhEG8U5gtPDZ7WQ.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2070, U+2074-207E, U+2080-208E, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
					url: "https://framerusercontent.com/assets/GrgcKwrN6d3Uz8EwcLHZxwEfC4.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
					url: "https://framerusercontent.com/assets/b6Y37FthZeALduNqHicBT6FutY.woff2",
					weight: "400",
				},
			],
		},
		...LinkFonts,
		...getFontsFromSharedStyle(fonts2),
		...getFontsFromSharedStyle(fonts),
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// virtual:404
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {
	base: "knjqFHLGo",
	lg: "B8Peoi3Xd",
	xl: "x3DLK7_jB",
};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"cde98c358c3069ef2a8dce28a8c2c8459e940a47824cf38ac0a6e3a305f8bfbb"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default2, {
				...rest,
			})}
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders Framer404FramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"cde98c358c3069ef2a8dce28a8c2c8459e940a47824cf38ac0a6e3a305f8bfbb"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				Component={stdin_default2}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default2);
var __default = ComponentWithRoot;
export { __default as default };
