// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project cde98c358c3069ef "matt.buzz", do not edit manually */
"use client";

/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
}} Props

 */
import { Text_Reveal } from "./chunks/text-reveal.js";
import { stdin_default as stdin_default2 } from "./chunks/text-showcase.js";
import { stdin_default } from "./chunks/experience.js";
import "./chunks/dual-typography.js";
import "./chunks/ticker.js";
import { routes } from "./chunks/routes.js";

// virtual:about
import { Fragment as Fragment2 } from "react";
import { ContextProviders } from "unframer";

// /:https://framerusercontent.com/modules/ydKOnXevGJEHV6m0dvpF/5FvM6fm6eP0eaaGZElHw/ez0fHtPoh.js
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import {
	addFonts,
	addPropertyControls,
	ComponentViewportProvider,
	ControlType,
	cx,
	getFonts,
	getFontsFromSharedStyle,
	getLoadingLazyAtYPosition,
	Image,
	RichText,
	SmartComponentScopedContainer,
	useComponentViewport,
	useLocaleInfo,
	useVariantState,
	withCSS,
	withFX,
	withOptimizedAppearEffect,
} from "unframer";
import { LayoutGroup, motion, MotionConfigContext } from "unframer";
import * as React from "react";
import { useRef } from "react";

// /:https://framerusercontent.com/modules/iZRbFcoUJX5zxlxG1E0C/K6bJxqCq1COOKIKgenKX/g9Fk1b9H5.js
import { fontStore } from "unframer";
fontStore.loadFonts(["BI;Open Sauce Sans/Medium/v0"]);
var fonts = [
	{
		explicitInter: true,
		fonts: [
			{
				family: "Open Sauce Sans",
				source: "builtIn",
				style: "normal",
				url: "https://framerusercontent.com/assets/O2R7AhA6wjBk0GHLJl0N8fqxN0.woff2",
				weight: "500",
			},
		],
	},
];
var css = [
	'.framer-Exvc0 .framer-styles-preset-1ou71qi:not(.rich-text-wrapper), .framer-Exvc0 .framer-styles-preset-1ou71qi.rich-text-wrapper p { --framer-font-family: "Open Sauce Sans", "Open Sauce Sans Placeholder", sans-serif; --framer-font-open-type-features: normal; --framer-font-size: 36px; --framer-font-style: normal; --framer-font-variation-axes: normal; --framer-font-weight: 500; --framer-letter-spacing: -0.02em; --framer-line-height: 1.2em; --framer-paragraph-spacing: 0px; --framer-text-alignment: start; --framer-text-color: var(--token-5fde730a-8086-4528-a317-d71b3bf4efde, #ffffff); --framer-text-decoration: none; --framer-text-stroke-color: initial; --framer-text-stroke-width: initial; --framer-text-transform: none; }',
	'@media (max-width: 1439px) and (min-width: 1025px) { .framer-Exvc0 .framer-styles-preset-1ou71qi:not(.rich-text-wrapper), .framer-Exvc0 .framer-styles-preset-1ou71qi.rich-text-wrapper p { --framer-font-family: "Open Sauce Sans", "Open Sauce Sans Placeholder", sans-serif; --framer-font-open-type-features: normal; --framer-font-size: 36px; --framer-font-style: normal; --framer-font-variation-axes: normal; --framer-font-weight: 500; --framer-letter-spacing: -0.02em; --framer-line-height: 1.2em; --framer-paragraph-spacing: 0px; --framer-text-alignment: start; --framer-text-color: var(--token-5fde730a-8086-4528-a317-d71b3bf4efde, #ffffff); --framer-text-decoration: none; --framer-text-stroke-color: initial; --framer-text-stroke-width: initial; --framer-text-transform: none; } }',
	'@media (max-width: 1024px) and (min-width: 700px) { .framer-Exvc0 .framer-styles-preset-1ou71qi:not(.rich-text-wrapper), .framer-Exvc0 .framer-styles-preset-1ou71qi.rich-text-wrapper p { --framer-font-family: "Open Sauce Sans", "Open Sauce Sans Placeholder", sans-serif; --framer-font-open-type-features: normal; --framer-font-size: 28px; --framer-font-style: normal; --framer-font-variation-axes: normal; --framer-font-weight: 500; --framer-letter-spacing: -0.02em; --framer-line-height: 1.2em; --framer-paragraph-spacing: 0px; --framer-text-alignment: start; --framer-text-color: var(--token-5fde730a-8086-4528-a317-d71b3bf4efde, #ffffff); --framer-text-decoration: none; --framer-text-stroke-color: initial; --framer-text-stroke-width: initial; --framer-text-transform: none; } }',
	'@media (max-width: 699px) and (min-width: 0px) { .framer-Exvc0 .framer-styles-preset-1ou71qi:not(.rich-text-wrapper), .framer-Exvc0 .framer-styles-preset-1ou71qi.rich-text-wrapper p { --framer-font-family: "Open Sauce Sans", "Open Sauce Sans Placeholder", sans-serif; --framer-font-open-type-features: normal; --framer-font-size: 24px; --framer-font-style: normal; --framer-font-variation-axes: normal; --framer-font-weight: 500; --framer-letter-spacing: -0.02em; --framer-line-height: 1.2em; --framer-paragraph-spacing: 0px; --framer-text-alignment: start; --framer-text-color: var(--token-5fde730a-8086-4528-a317-d71b3bf4efde, #ffffff); --framer-text-decoration: none; --framer-text-stroke-color: initial; --framer-text-stroke-width: initial; --framer-text-transform: none; } }',
];
var className = "framer-Exvc0";

// /:https://framerusercontent.com/modules/ydKOnXevGJEHV6m0dvpF/5FvM6fm6eP0eaaGZElHw/ez0fHtPoh.js
var Text_RevealFonts = getFonts(Text_Reveal);
var SmartComponentScopedContainerWithFXWithOptimizedAppearEffect =
	withOptimizedAppearEffect(withFX(SmartComponentScopedContainer));
var ExperienceFonts = getFonts(stdin_default);
var SmartComponentScopedContainerWithFX = withFX(SmartComponentScopedContainer);
var TickerFonts = getFonts(stdin_default2);
var cycleOrder = ["lY_N7Oico", "fowZFvNk8", "VQvFkXhWS", "a2b1MWrcW"];
var serializationHash = "framer-ZYzfN";
var variantClassNames = {
	a2b1MWrcW: "framer-v-139tmnp",
	fowZFvNk8: "framer-v-15cqmyr",
	lY_N7Oico: "framer-v-1rug56r",
	VQvFkXhWS: "framer-v-mwof9x",
};
function addPropertyOverrides(overrides, ...variants) {
	const nextOverrides = {};
	variants?.forEach(
		(variant) => variant && Object.assign(nextOverrides, overrides[variant]),
	);
	return nextOverrides;
}
var transition1 = {
	bounce: 0.2,
	delay: 0,
	duration: 0.4,
	type: "spring",
};
var transition2 = {
	damping: 80,
	delay: 0.4,
	mass: 1,
	stiffness: 400,
	type: "spring",
};
var animation = {
	opacity: 1,
	rotate: 0,
	rotateX: 0,
	rotateY: 0,
	scale: 1,
	skewX: 0,
	skewY: 0,
	transition: transition2,
	x: 0,
	y: 0,
};
var animation1 = {
	opacity: 1e-3,
	rotate: 0,
	rotateX: 0,
	rotateY: 0,
	scale: 1,
	skewX: 0,
	skewY: 0,
	x: 0,
	y: 20,
};
var animation2 = {
	opacity: 0,
	rotate: 0,
	rotateX: 0,
	rotateY: 0,
	scale: 1,
	skewX: 0,
	skewY: 0,
	x: 0,
	y: 30,
};
var transition3 = {
	delay: 0,
	duration: 0.6,
	ease: [0.44, 0, 0.56, 1],
	type: "tween",
};
var Transition = ({ value, children }) => {
	const config = React.useContext(MotionConfigContext);
	const transition = value ?? config.transition;
	const contextValue = React.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext.Provider value={contextValue}>
			{children}
		</MotionConfigContext.Provider>
	);
};
var Variants = motion.create(React.Fragment);
var humanReadableVariantMap = {
	Desktop: "lY_N7Oico",
	Laptop: "fowZFvNk8",
	Phone: "a2b1MWrcW",
	Tablet: "VQvFkXhWS",
};
var getProps = ({ height, id, width, ...props }) => {
	return {
		...props,
		variant:
			humanReadableVariantMap[props.variant] ?? props.variant ?? "lY_N7Oico",
	};
};
var createLayoutDependency = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
	const fallbackRef = useRef(null);
	const refBinding = ref ?? fallbackRef;
	const defaultLayoutId = React.useId();
	const { activeLocale, setLocale } = useLocaleInfo();
	const componentViewport = useComponentViewport();
	const {
		style,
		className: className2,
		layoutId,
		variant,
		...restProps
	} = getProps(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState({
		cycleOrder,
		defaultVariant: "lY_N7Oico",
		ref: refBinding,
		variant,
		variantClassNames,
	});
	const layoutDependency = createLayoutDependency(props, variants);
	const sharedStyleClassNames = [className];
	const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
	return (
		<LayoutGroup id={layoutId ?? defaultLayoutId}>
			<Variants animate={variants} initial={false}>
				<Transition value={transition1}>
					<motion.main
						{...restProps}
						{...gestureHandlers}
						className={cx(
							scopingClassNames,
							"framer-1rug56r",
							className2,
							classNames,
						)}
						data-framer-name={"Desktop"}
						layoutDependency={layoutDependency}
						layoutId={"lY_N7Oico"}
						ref={refBinding}
						style={{
							...style,
						}}
						{...addPropertyOverrides(
							{
								a2b1MWrcW: {
									"data-framer-name": "Phone",
								},
								fowZFvNk8: {
									"data-framer-name": "Laptop",
								},
								VQvFkXhWS: {
									"data-framer-name": "Tablet",
								},
							},
							baseVariant,
							gestureVariant,
						)}
					>
						<motion.div
							className={"framer-g7am9s"}
							data-framer-name={"Content"}
							layoutDependency={layoutDependency}
							layoutId={"GCUlBqrs3"}
						>
							<motion.section
								className={"framer-w73wrx"}
								data-framer-name={"About"}
								layoutDependency={layoutDependency}
								layoutId={"xGYTVQtlb"}
							>
								<motion.div
									className={"framer-1wwgt9u"}
									data-framer-name={"Title"}
									layoutDependency={layoutDependency}
									layoutId={"AjpwQ9Edn"}
								>
									<ComponentViewportProvider>
										<SmartComponentScopedContainerWithFXWithOptimizedAppearEffect
											__perspectiveFX={false}
											__smartComponentFX={true}
											__targetOpacity={1}
											animate={animation}
											className={"framer-1sqndvs-container"}
											data-framer-appear-id={"1sqndvs"}
											initial={animation1}
											isAuthoredByUser={true}
											layoutDependency={layoutDependency}
											layoutId={"SptVIW2S6-container"}
											nodeId={"SptVIW2S6"}
											optimized={true}
											rendersWithMotion={true}
											scopeId={"ez0fHtPoh"}
										>
											<Text_Reveal
												font={{
													fontFamily:
														'"Open Sauce Sans", "Open Sauce Sans Placeholder", sans-serif',
													fontSize: "48px",
													fontStyle: "normal",
													fontWeight: 500,
													letterSpacing: "-0.02em",
													lineHeight: "1.2em",
												}}
												height={"100%"}
												id={"SptVIW2S6"}
												layoutId={"SptVIW2S6"}
												style={{
													maxWidth: "100%",
													width: "100%",
												}}
												text={
													"I\u2019m Nolan Carter, a multi-disciplinary designer specializing in creating immersive and engaging product experiences. My work is characterized by a commitment to clarity, consistency, and attention to detail, ensuring that every project resonates authentically with its audience.\n\nI have a deep appreciation for typography and its powerful role in design. Additionally, I\u2019m an aspiring entrepreneur, driven by the desire to innovate and push creative boundaries in the industry."
												}
												textColor={
													"var(--token-5fde730a-8086-4528-a317-d71b3bf4efde, rgb(0, 0, 0))"
												}
												width={"100%"}
												{...addPropertyOverrides(
													{
														a2b1MWrcW: {
															font: {
																fontFamily:
																	'"Open Sauce Sans", "Open Sauce Sans Placeholder", sans-serif',
																fontSize: "26px",
																fontStyle: "normal",
																fontWeight: 500,
																letterSpacing: "-0.02em",
																lineHeight: "1.2em",
															},
														},
														VQvFkXhWS: {
															font: {
																fontFamily:
																	'"Open Sauce Sans", "Open Sauce Sans Placeholder", sans-serif',
																fontSize: "36px",
																fontStyle: "normal",
																fontWeight: 500,
																letterSpacing: "-0.02em",
																lineHeight: "1.2em",
															},
														},
													},
													baseVariant,
													gestureVariant,
												)}
											/>
										</SmartComponentScopedContainerWithFXWithOptimizedAppearEffect>
									</ComponentViewportProvider>
								</motion.div>
								<motion.div
									className={"framer-gy7ro2"}
									data-framer-name={"Avatar"}
									layoutDependency={layoutDependency}
									layoutId={"sHRrQi97x"}
								>
									<Image
										background={{
											alt: "Portrait of man looking to the right",
											fit: "fill",
											loading: getLoadingLazyAtYPosition(
												(componentViewport?.y || 0) +
													0 +
													(((componentViewport?.height || 200) - 20 - 2069.2) /
														2 +
														0 +
														0) +
													0 +
													0 +
													0 +
													280 +
													0 +
													0,
											),
											pixelHeight: 1e3,
											pixelWidth: 1e3,
											sizes: `calc((${componentViewport?.width || "100vw"} - 64px) * 0.35)`,
											src: "https://framerusercontent.com/images/PMcAE84t2rNMzywN7Z2vlArCccg.webp?width=1000&height=1000",
											srcSet:
												"https://framerusercontent.com/images/PMcAE84t2rNMzywN7Z2vlArCccg.webp?scale-down-to=512&width=1000&height=1000 512w,https://framerusercontent.com/images/PMcAE84t2rNMzywN7Z2vlArCccg.webp?width=1000&height=1000 1000w",
										}}
										className={"framer-coxmqt"}
										layoutDependency={layoutDependency}
										layoutId={"Ny6Km7kxc"}
										{...addPropertyOverrides(
											{
												a2b1MWrcW: {
													background: {
														alt: "Portrait of man looking to the right",
														fit: "fill",
														loading: getLoadingLazyAtYPosition(
															(componentViewport?.y || 0) +
																0 +
																(((componentViewport?.height || 200) -
																	0 -
																	1933.2) /
																	2 +
																	0 +
																	0) +
																0 +
																0 +
																0 +
																248 +
																0 +
																0,
														),
														pixelHeight: 1e3,
														pixelWidth: 1e3,
														sizes: `calc(${componentViewport?.width || "100vw"} - 32px)`,
														src: "https://framerusercontent.com/images/PMcAE84t2rNMzywN7Z2vlArCccg.webp?width=1000&height=1000",
														srcSet:
															"https://framerusercontent.com/images/PMcAE84t2rNMzywN7Z2vlArCccg.webp?scale-down-to=512&width=1000&height=1000 512w,https://framerusercontent.com/images/PMcAE84t2rNMzywN7Z2vlArCccg.webp?width=1000&height=1000 1000w",
													},
												},
												fowZFvNk8: {
													background: {
														alt: "Portrait of man looking to the right",
														fit: "fill",
														loading: getLoadingLazyAtYPosition(
															(componentViewport?.y || 0) +
																0 +
																(((componentViewport?.height || 200) -
																	20 -
																	2069.2) /
																	2 +
																	0 +
																	0) +
																0 +
																0 +
																0 +
																280 +
																0 +
																0,
														),
														pixelHeight: 1e3,
														pixelWidth: 1e3,
														sizes: `calc((${componentViewport?.width || "100vw"} - 64px) * 0.4)`,
														src: "https://framerusercontent.com/images/PMcAE84t2rNMzywN7Z2vlArCccg.webp?width=1000&height=1000",
														srcSet:
															"https://framerusercontent.com/images/PMcAE84t2rNMzywN7Z2vlArCccg.webp?scale-down-to=512&width=1000&height=1000 512w,https://framerusercontent.com/images/PMcAE84t2rNMzywN7Z2vlArCccg.webp?width=1000&height=1000 1000w",
													},
												},
												VQvFkXhWS: {
													background: {
														alt: "Portrait of man looking to the right",
														fit: "fill",
														loading: getLoadingLazyAtYPosition(
															(componentViewport?.y || 0) +
																0 +
																(((componentViewport?.height || 200) -
																	20 -
																	2069.2) /
																	2 +
																	0 +
																	0) +
																0 +
																0 +
																0 +
																280 +
																0 +
																0,
														),
														pixelHeight: 1e3,
														pixelWidth: 1e3,
														sizes: `calc((${componentViewport?.width || "100vw"} - 48px) * 0.4)`,
														src: "https://framerusercontent.com/images/PMcAE84t2rNMzywN7Z2vlArCccg.webp?width=1000&height=1000",
														srcSet:
															"https://framerusercontent.com/images/PMcAE84t2rNMzywN7Z2vlArCccg.webp?scale-down-to=512&width=1000&height=1000 512w,https://framerusercontent.com/images/PMcAE84t2rNMzywN7Z2vlArCccg.webp?width=1000&height=1000 1000w",
													},
												},
											},
											baseVariant,
											gestureVariant,
										)}
									/>
								</motion.div>
							</motion.section>
							<motion.section
								className={"framer-1ift6rv"}
								data-framer-name={"Experience"}
								layoutDependency={layoutDependency}
								layoutId={"yd8DKXvdP"}
							>
								<RichText
									__fromCanvasComponent={true}
									className={"framer-dv9ouf"}
									data-framer-name={"Title"}
									fonts={["Inter"]}
									layoutDependency={layoutDependency}
									layoutId={"PJ6b0mFu6"}
									style={{
										"--framer-link-text-color": "rgb(0, 153, 255)",
										"--framer-link-text-decoration": "underline",
									}}
									verticalAlignment={"top"}
									withExternalLayout={true}
								>
									<React.Fragment>
										<motion.p
											className={"framer-styles-preset-1ou71qi"}
											data-styles-preset={"g9Fk1b9H5"}
										>
											{"Work Experience"}
										</motion.p>
									</React.Fragment>
								</RichText>
								<motion.div
									className={"framer-1poajm1"}
									data-framer-name={"Content"}
									layoutDependency={layoutDependency}
									layoutId={"k8QBF7c_q"}
								>
									<ComponentViewportProvider
										height={134}
										width={`calc(${componentViewport?.width || "100vw"} - 64px)`}
										y={
											(componentViewport?.y || 0) +
											0 +
											(((componentViewport?.height || 200) - 20 - 2069.2) / 2 +
												0 +
												0) +
											0 +
											1070 +
											0 +
											123.2 +
											0 +
											0
										}
										{...addPropertyOverrides(
											{
												a2b1MWrcW: {
													width: `calc(${componentViewport?.width || "100vw"} - 32px)`,
													y:
														(componentViewport?.y || 0) +
														0 +
														(((componentViewport?.height || 200) - 0 - 1933.2) /
															2 +
															0 +
															0) +
														0 +
														1002 +
														0 +
														91.2 +
														0 +
														0,
												},
												VQvFkXhWS: {
													width: `calc(${componentViewport?.width || "100vw"} - 48px)`,
												},
											},
											baseVariant,
											gestureVariant,
										)}
									>
										<SmartComponentScopedContainerWithFX
											__framer__animate={{
												transition: transition3,
											}}
											__framer__animateOnce={true}
											__framer__enter={animation2}
											__framer__styleAppearEffectEnabled={true}
											__framer__threshold={0}
											__perspectiveFX={false}
											__smartComponentFX={true}
											__targetOpacity={1}
											className={"framer-amzvdb-container"}
											layoutDependency={layoutDependency}
											layoutId={"l_Ncbc7LS-container"}
											nodeId={"l_Ncbc7LS"}
											rendersWithMotion={true}
											scopeId={"ez0fHtPoh"}
										>
											{_jsx(stdin_default, {
												bVE4ijxia: "Design Director",
												height: "100%",
												id: "l_Ncbc7LS",
												layoutId: "l_Ncbc7LS",
												R2Gne3I4X: "2025 \u2013 Present",
												SF2hqf3NH:
													"Led the creative vision and design strategy across digital and physical touchpoints, overseeing a team of multidisciplinary designers. Spearheaded the launch of multiple product lines and brand campaigns, resulting in a 30% increase in customer engagement. Championed user-centered design processes, aligning product innovation with business goals and lifestyle trends.",
												style: {
													width: "100%",
												},
												Uito5nZJ6: "Incase",
												variant: "L7MdRydaj",
												width: "100%",
												...addPropertyOverrides(
													{
														a2b1MWrcW: {
															variant: "AdAEdw9AH",
														},
														VQvFkXhWS: {
															variant: "FNGOkxvQw",
														},
													},
													baseVariant,
													gestureVariant,
												),
											})}
										</SmartComponentScopedContainerWithFX>
									</ComponentViewportProvider>
									<ComponentViewportProvider
										height={134}
										width={`calc(${componentViewport?.width || "100vw"} - 64px)`}
										y={
											(componentViewport?.y || 0) +
											0 +
											(((componentViewport?.height || 200) - 20 - 2069.2) / 2 +
												0 +
												0) +
											0 +
											1070 +
											0 +
											123.2 +
											0 +
											182
										}
										{...addPropertyOverrides(
											{
												a2b1MWrcW: {
													width: `calc(${componentViewport?.width || "100vw"} - 32px)`,
													y:
														(componentViewport?.y || 0) +
														0 +
														(((componentViewport?.height || 200) - 0 - 1933.2) /
															2 +
															0 +
															0) +
														0 +
														1002 +
														0 +
														91.2 +
														0 +
														182,
												},
												VQvFkXhWS: {
													width: `calc(${componentViewport?.width || "100vw"} - 48px)`,
												},
											},
											baseVariant,
											gestureVariant,
										)}
									>
										<SmartComponentScopedContainerWithFX
											__framer__animate={{
												transition: transition3,
											}}
											__framer__animateOnce={true}
											__framer__enter={animation2}
											__framer__styleAppearEffectEnabled={true}
											__framer__threshold={0}
											__perspectiveFX={false}
											__smartComponentFX={true}
											__targetOpacity={1}
											className={"framer-1cgbety-container"}
											layoutDependency={layoutDependency}
											layoutId={"c3aL3nExu-container"}
											nodeId={"c3aL3nExu"}
											rendersWithMotion={true}
											scopeId={"ez0fHtPoh"}
										>
											{_jsx(stdin_default, {
												bVE4ijxia: "Design Lead",
												height: "100%",
												id: "c3aL3nExu",
												layoutId: "c3aL3nExu",
												R2Gne3I4X: "2023 \u2013 2024",
												SF2hqf3NH:
													"Directed creative execution for global campaigns, collaborating with cross-functional teams to deliver compelling digital experiences for top-tier clients. Guided a team of designers through fast-paced projects, elevating the agency\u2019s digital presence and winning multiple industry awards. Focused on storytelling, usability, and brand consistency across channels.",
												style: {
													width: "100%",
												},
												Uito5nZJ6: "Grey",
												variant: "L7MdRydaj",
												width: "100%",
												...addPropertyOverrides(
													{
														a2b1MWrcW: {
															variant: "AdAEdw9AH",
														},
														VQvFkXhWS: {
															variant: "FNGOkxvQw",
														},
													},
													baseVariant,
													gestureVariant,
												),
											})}
										</SmartComponentScopedContainerWithFX>
									</ComponentViewportProvider>
									<ComponentViewportProvider
										height={134}
										width={`calc(${componentViewport?.width || "100vw"} - 64px)`}
										y={
											(componentViewport?.y || 0) +
											0 +
											(((componentViewport?.height || 200) - 20 - 2069.2) / 2 +
												0 +
												0) +
											0 +
											1070 +
											0 +
											123.2 +
											0 +
											364
										}
										{...addPropertyOverrides(
											{
												a2b1MWrcW: {
													width: `calc(${componentViewport?.width || "100vw"} - 32px)`,
													y:
														(componentViewport?.y || 0) +
														0 +
														(((componentViewport?.height || 200) - 0 - 1933.2) /
															2 +
															0 +
															0) +
														0 +
														1002 +
														0 +
														91.2 +
														0 +
														364,
												},
												VQvFkXhWS: {
													width: `calc(${componentViewport?.width || "100vw"} - 48px)`,
												},
											},
											baseVariant,
											gestureVariant,
										)}
									>
										<SmartComponentScopedContainerWithFX
											__framer__animate={{
												transition: transition3,
											}}
											__framer__animateOnce={true}
											__framer__enter={animation2}
											__framer__styleAppearEffectEnabled={true}
											__framer__threshold={0}
											__perspectiveFX={false}
											__smartComponentFX={true}
											__targetOpacity={1}
											className={"framer-1ls08sm-container"}
											layoutDependency={layoutDependency}
											layoutId={"zseUEHl7p-container"}
											nodeId={"zseUEHl7p"}
											rendersWithMotion={true}
											scopeId={"ez0fHtPoh"}
										>
											{_jsx(stdin_default, {
												bVE4ijxia: "Senior Designer",
												height: "100%",
												id: "zseUEHl7p",
												layoutId: "zseUEHl7p",
												R2Gne3I4X: "2020 \u2013 2022",
												SF2hqf3NH:
													"Played a key role in crafting scalable design systems and improving the user experience for merchants across the platform. Partnered with product managers and engineers to launch features that enhanced onboarding and retention. Advocated for accessibility and design inclusivity, influencing platform-wide standards.",
												style: {
													width: "100%",
												},
												Uito5nZJ6: "Shopify",
												variant: "L7MdRydaj",
												width: "100%",
												...addPropertyOverrides(
													{
														a2b1MWrcW: {
															variant: "AdAEdw9AH",
														},
														VQvFkXhWS: {
															variant: "FNGOkxvQw",
														},
													},
													baseVariant,
													gestureVariant,
												),
											})}
										</SmartComponentScopedContainerWithFX>
									</ComponentViewportProvider>
									<ComponentViewportProvider
										height={134}
										width={`calc(${componentViewport?.width || "100vw"} - 64px)`}
										y={
											(componentViewport?.y || 0) +
											0 +
											(((componentViewport?.height || 200) - 20 - 2069.2) / 2 +
												0 +
												0) +
											0 +
											1070 +
											0 +
											123.2 +
											0 +
											546
										}
										{...addPropertyOverrides(
											{
												a2b1MWrcW: {
													width: `calc(${componentViewport?.width || "100vw"} - 32px)`,
													y:
														(componentViewport?.y || 0) +
														0 +
														(((componentViewport?.height || 200) - 0 - 1933.2) /
															2 +
															0 +
															0) +
														0 +
														1002 +
														0 +
														91.2 +
														0 +
														546,
												},
												VQvFkXhWS: {
													width: `calc(${componentViewport?.width || "100vw"} - 48px)`,
												},
											},
											baseVariant,
											gestureVariant,
										)}
									>
										<SmartComponentScopedContainerWithFX
											__framer__animate={{
												transition: transition3,
											}}
											__framer__animateOnce={true}
											__framer__enter={animation2}
											__framer__styleAppearEffectEnabled={true}
											__framer__threshold={0}
											__perspectiveFX={false}
											__smartComponentFX={true}
											__targetOpacity={1}
											className={"framer-1a8bkm7-container"}
											layoutDependency={layoutDependency}
											layoutId={"k2VPfbLGw-container"}
											nodeId={"k2VPfbLGw"}
											rendersWithMotion={true}
											scopeId={"ez0fHtPoh"}
										>
											{_jsx(stdin_default, {
												bVE4ijxia: "UX/UI Designer",
												height: "100%",
												id: "k2VPfbLGw",
												layoutId: "k2VPfbLGw",
												R2Gne3I4X: "2018 \u2013 2020",
												SF2hqf3NH:
													"Designed and optimized the core product experience for a mental health startup, contributing to a 40% increase in user retention. Conducted user research and usability testing to inform product decisions, translating insights into thoughtful interfaces. Collaborated closely with the founding team to define the brand\u2019s visual and interaction language.",
												style: {
													width: "100%",
												},
												Uito5nZJ6: "Shrink",
												variant: "L7MdRydaj",
												width: "100%",
												...addPropertyOverrides(
													{
														a2b1MWrcW: {
															variant: "AdAEdw9AH",
														},
														VQvFkXhWS: {
															variant: "FNGOkxvQw",
														},
													},
													baseVariant,
													gestureVariant,
												),
											})}
										</SmartComponentScopedContainerWithFX>
									</ComponentViewportProvider>
								</motion.div>
							</motion.section>
							<motion.section
								className={"framer-qu9gei"}
								data-framer-name={"Ticker"}
								layoutDependency={layoutDependency}
								layoutId={"xBqoTDH2J"}
							>
								<ComponentViewportProvider
									height={96}
									width={componentViewport?.width || "100vw"}
									y={
										(componentViewport?.y || 0) +
										0 +
										(((componentViewport?.height || 200) - 20 - 2069.2) / 2 +
											0 +
											0) +
										0 +
										1973.2 +
										0 +
										0
									}
									{...addPropertyOverrides(
										{
											a2b1MWrcW: {
												y:
													(componentViewport?.y || 0) +
													0 +
													(((componentViewport?.height || 200) - 0 - 1933.2) /
														2 +
														0 +
														0) +
													0 +
													1837.2 +
													0 +
													0,
											},
										},
										baseVariant,
										gestureVariant,
									)}
								>
									<SmartComponentScopedContainer
										className={"framer-5h61wf-container"}
										layoutDependency={layoutDependency}
										layoutId={"njD0PpPj4-container"}
										nodeId={"njD0PpPj4"}
										rendersWithMotion={true}
										scopeId={"ez0fHtPoh"}
									>
										{_jsx(stdin_default2, {
											AW9pUoArR: " Framer Development \u22C5",
											height: "100%",
											id: "njD0PpPj4",
											layoutId: "njD0PpPj4",
											Oho2iCzl9: 80,
											px8arhzxh: " Digital Design \u22C5",
											style: {
												width: "100%",
											},
											width: "100%",
											YqnkipU9c: " Art Direction \u22C5",
											...addPropertyOverrides(
												{
													a2b1MWrcW: {
														Oho2iCzl9: 50,
													},
												},
												baseVariant,
												gestureVariant,
											),
										})}
									</SmartComponentScopedContainer>
								</ComponentViewportProvider>
							</motion.section>
						</motion.div>
					</motion.main>
				</Transition>
			</Variants>
		</LayoutGroup>
	);
});
var css2 = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-ZYzfN.framer-h2mok5, .framer-ZYzfN .framer-h2mok5 { display: block; }",
	".framer-ZYzfN.framer-1rug56r { align-content: center; align-items: center; display: flex; flex-direction: column; flex-wrap: nowrap; gap: 16px; height: min-content; justify-content: center; max-width: 1920px; overflow: hidden; padding: 0px 0px 20px 0px; position: relative; width: 1440px; }",
	".framer-ZYzfN .framer-g7am9s { align-content: center; align-items: center; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 100px; height: min-content; justify-content: center; overflow: hidden; padding: 0px; position: relative; width: 100%; }",
	".framer-ZYzfN .framer-w73wrx { align-content: center; align-items: center; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 80px; height: min-content; justify-content: center; overflow: hidden; padding: 0px 32px 0px 32px; position: relative; width: 100%; }",
	".framer-ZYzfN .framer-1wwgt9u { align-content: flex-start; align-items: flex-start; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 0px; height: min-content; justify-content: flex-start; overflow: hidden; padding: 0px; position: relative; width: 100%; }",
	".framer-ZYzfN .framer-1sqndvs-container { flex: none; height: auto; max-width: 100%; position: relative; width: 100%; }",
	".framer-ZYzfN .framer-gy7ro2 { align-content: flex-end; align-items: flex-end; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: center; overflow: hidden; padding: 0px; position: relative; width: 100%; }",
	".framer-ZYzfN .framer-coxmqt { aspect-ratio: 0.7978260869565217 / 1; flex: none; height: var(--framer-aspect-ratio-supported, 604px); overflow: hidden; position: relative; width: 35%; }",
	".framer-ZYzfN .framer-1ift6rv { align-content: flex-start; align-items: flex-start; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 80px; height: min-content; justify-content: center; overflow: hidden; padding: 0px 32px 0px 32px; position: relative; width: 100%; }",
	".framer-ZYzfN .framer-dv9ouf { flex: none; height: auto; position: relative; white-space: pre; width: auto; }",
	".framer-ZYzfN .framer-1poajm1 { align-content: center; align-items: center; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 48px; height: min-content; justify-content: center; overflow: hidden; padding: 0px; position: relative; width: 100%; }",
	".framer-ZYzfN .framer-amzvdb-container, .framer-ZYzfN .framer-1cgbety-container, .framer-ZYzfN .framer-1ls08sm-container, .framer-ZYzfN .framer-1a8bkm7-container, .framer-ZYzfN .framer-5h61wf-container { flex: none; height: auto; position: relative; width: 100%; }",
	".framer-ZYzfN .framer-qu9gei { align-content: center; align-items: center; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: center; overflow: hidden; padding: 0px; position: relative; width: 100%; }",
	".framer-ZYzfN.framer-v-15cqmyr.framer-1rug56r { width: 1025px; }",
	".framer-ZYzfN.framer-v-15cqmyr .framer-coxmqt, .framer-ZYzfN.framer-v-mwof9x .framer-coxmqt { height: var(--framer-aspect-ratio-supported, 251px); width: 40%; }",
	".framer-ZYzfN.framer-v-mwof9x.framer-1rug56r { width: 700px; }",
	".framer-ZYzfN.framer-v-mwof9x .framer-w73wrx, .framer-ZYzfN.framer-v-mwof9x .framer-1ift6rv { padding: 0px 24px 0px 24px; }",
	".framer-ZYzfN.framer-v-139tmnp.framer-1rug56r { padding: 0px; width: 200px; }",
	".framer-ZYzfN.framer-v-139tmnp .framer-g7am9s { gap: 64px; }",
	".framer-ZYzfN.framer-v-139tmnp .framer-w73wrx, .framer-ZYzfN.framer-v-139tmnp .framer-1ift6rv { gap: 48px; padding: 0px 16px 0px 16px; }",
	".framer-ZYzfN.framer-v-139tmnp .framer-gy7ro2 { align-content: center; align-items: center; }",
	".framer-ZYzfN.framer-v-139tmnp .framer-coxmqt { height: var(--framer-aspect-ratio-supported, 251px); width: 100%; }",
	...css,
];
var Framerez0fHtPoh = withCSS(Component, css2, "framer-ZYzfN");
var stdin_default3 = Framerez0fHtPoh;
Framerez0fHtPoh.displayName = "About";
Framerez0fHtPoh.defaultProps = {
	height: 2403,
	width: 1440,
};
addPropertyControls(Framerez0fHtPoh, {
	variant: {
		options: ["lY_N7Oico", "fowZFvNk8", "VQvFkXhWS", "a2b1MWrcW"],
		optionTitles: ["Desktop", "Laptop", "Tablet", "Phone"],
		title: "Variant",
		type: ControlType.Enum,
	},
});
addFonts(
	Framerez0fHtPoh,
	[
		{
			explicitInter: true,
			fonts: [
				{
					family: "Open Sauce Sans",
					source: "builtIn",
					style: "normal",
					url: "https://framerusercontent.com/assets/O2R7AhA6wjBk0GHLJl0N8fqxN0.woff2",
					weight: "500",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
					url: "https://framerusercontent.com/assets/5vvr9Vy74if2I6bQbJvbw7SY1pQ.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
					url: "https://framerusercontent.com/assets/EOr0mi4hNtlgWNn9if640EZzXCo.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+1F00-1FFF",
					url: "https://framerusercontent.com/assets/Y9k9QrlZAqio88Klkmbd8VoMQc.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+0370-03FF",
					url: "https://framerusercontent.com/assets/OYrD2tBIBPvoJXiIHnLoOXnY9M.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
					url: "https://framerusercontent.com/assets/JeYwfuaPfZHQhEG8U5gtPDZ7WQ.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2070, U+2074-207E, U+2080-208E, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
					url: "https://framerusercontent.com/assets/GrgcKwrN6d3Uz8EwcLHZxwEfC4.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
					url: "https://framerusercontent.com/assets/b6Y37FthZeALduNqHicBT6FutY.woff2",
					weight: "400",
				},
			],
		},
		...Text_RevealFonts,
		...ExperienceFonts,
		...TickerFonts,
		...getFontsFromSharedStyle(fonts),
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// virtual:about
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {
	base: "VQvFkXhWS",
	lg: "fowZFvNk8",
	xl: "lY_N7Oico",
};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"cde98c358c3069ef2a8dce28a8c2c8459e940a47824cf38ac0a6e3a305f8bfbb"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default3, {
				...rest,
			})}
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders AboutFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"cde98c358c3069ef2a8dce28a8c2c8459e940a47824cf38ac0a6e3a305f8bfbb"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				Component={stdin_default3}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default3);
var about_default = ComponentWithRoot;
export { about_default as default };
