// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project cde98c358c3069ef "matt.buzz", do not edit manually */
"use client";

/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
}} Props

 */
import {
	className as className2,
	css as css2,
	fonts as fonts2,
} from "./chunks/hero-typography.js";
import { className, css, fonts } from "./chunks/body-typography.js";
import { stdin_default } from "./chunks/link-skew.js";
import "./chunks/heading-typography.js";
import { stdin_default as stdin_default2 } from "./chunks/form-button.js";
import "./chunks/shared-fonts.js";
import { routes } from "./chunks/routes.js";

// virtual:contact
import { Fragment as Fragment2 } from "react";
import { ContextProviders } from "unframer";

// /:https://framerusercontent.com/modules/02Aoyfxt9oiJEUcekfzi/Khtt9wXVpM8Pzsb0ijgJ/cmXbPL8Nf.js
import {
	jsx as _jsx,
	jsxs as _jsxs,
	Fragment as _Fragment,
} from "react/jsx-runtime";
import {
	addFonts,
	addPropertyControls,
	ComponentViewportProvider,
	ControlType,
	cx,
	FormBooleanInput,
	FormContainer,
	FormPlainTextInput,
	getFonts,
	getFontsFromSharedStyle,
	RichText,
	SmartComponentScopedContainer,
	useComponentViewport,
	useLocaleInfo,
	useVariantState,
	withCSS,
	withFX,
} from "unframer";
import { LayoutGroup, motion, MotionConfigContext } from "unframer";
import * as React from "react";
import { useRef } from "react";
var LinkFonts = getFonts(stdin_default);
var FormButtonFonts = getFonts(stdin_default2);
var MotionDivWithFX = withFX(motion.div);
var cycleOrder = ["EpQq4QIe4", "mfiN6ML2V", "SJWKFfZ8_", "kif8CK8Tz"];
var serializationHash = "framer-MOnlf";
var variantClassNames = {
	EpQq4QIe4: "framer-v-nd42wg",
	kif8CK8Tz: "framer-v-ia4cai",
	mfiN6ML2V: "framer-v-12rmsmh",
	SJWKFfZ8_: "framer-v-130gd0z",
};
function addPropertyOverrides(overrides, ...variants) {
	const nextOverrides = {};
	variants?.forEach(
		(variant) => variant && Object.assign(nextOverrides, overrides[variant]),
	);
	return nextOverrides;
}
var transition1 = {
	bounce: 0.2,
	delay: 0,
	duration: 0.4,
	type: "spring",
};
var animation = {
	opacity: 1e-3,
	rotate: 0,
	scale: 1,
	skewX: 0,
	skewY: 0,
	x: 0,
	y: 20,
};
var transition2 = {
	damping: 80,
	delay: 0.02,
	mass: 1,
	stiffness: 400,
	type: "spring",
};
var textEffect = {
	effect: animation,
	repeat: false,
	startDelay: 0.4,
	tokenization: "word",
	transition: transition2,
	trigger: "onMount",
	type: "appear",
};
var formVariants = (form, variants, currentVariant) => {
	switch (form.state) {
		case "success":
			return variants.success ?? currentVariant;
		case "pending":
			return variants.pending ?? currentVariant;
		case "error":
			return variants.error ?? currentVariant;
		case "incomplete":
			return variants.incomplete ?? currentVariant;
	}
};
var transition3 = {
	delay: 0,
	duration: 2.2,
	ease: [0.5, 0, 0.7, 0.77],
	type: "tween",
};
var animation1 = {
	opacity: 0,
	rotate: 0,
	rotateX: 0,
	rotateY: 0,
	scale: 5,
	skewX: 0,
	skewY: 0,
	x: 0,
	y: 0,
};
var Transition = ({ value, children }) => {
	const config = React.useContext(MotionConfigContext);
	const transition = value ?? config.transition;
	const contextValue = React.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext.Provider value={contextValue}>
			{children}
		</MotionConfigContext.Provider>
	);
};
var Variants = motion.create(React.Fragment);
var humanReadableVariantMap = {
	Desktop: "EpQq4QIe4",
	Laptop: "mfiN6ML2V",
	Phone: "kif8CK8Tz",
	Tablet: "SJWKFfZ8_",
};
var getProps = ({ height, id, width, ...props }) => {
	return {
		...props,
		variant:
			humanReadableVariantMap[props.variant] ?? props.variant ?? "EpQq4QIe4",
	};
};
var createLayoutDependency = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
	const fallbackRef = useRef(null);
	const refBinding = ref ?? fallbackRef;
	const defaultLayoutId = React.useId();
	const { activeLocale, setLocale } = useLocaleInfo();
	const componentViewport = useComponentViewport();
	const {
		style,
		className: className3,
		layoutId,
		variant,
		...restProps
	} = getProps(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState({
		cycleOrder,
		defaultVariant: "EpQq4QIe4",
		ref: refBinding,
		variant,
		variantClassNames,
	});
	const layoutDependency = createLayoutDependency(props, variants);
	const sharedStyleClassNames = [className2, className];
	const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
	return (
		<LayoutGroup id={layoutId ?? defaultLayoutId}>
			<Variants animate={variants} initial={false}>
				<Transition value={transition1}>
					<motion.main
						{...restProps}
						{...gestureHandlers}
						className={cx(
							scopingClassNames,
							"framer-nd42wg",
							className3,
							classNames,
						)}
						data-framer-name={"Desktop"}
						layoutDependency={layoutDependency}
						layoutId={"EpQq4QIe4"}
						ref={refBinding}
						style={{
							...style,
						}}
						{...addPropertyOverrides(
							{
								kif8CK8Tz: {
									"data-framer-name": "Phone",
								},
								mfiN6ML2V: {
									"data-framer-name": "Laptop",
								},
								SJWKFfZ8_: {
									"data-framer-name": "Tablet",
								},
							},
							baseVariant,
							gestureVariant,
						)}
					>
						<motion.div
							className={"framer-108rcfv"}
							data-framer-name={"Title"}
							layoutDependency={layoutDependency}
							layoutId={"bO9R0wZx7"}
						>
							<RichText
								__fromCanvasComponent={true}
								className={"framer-xu9ok6"}
								data-framer-name={"Text"}
								effect={textEffect}
								fonts={["Inter"]}
								layoutDependency={layoutDependency}
								layoutId={"CyUytV5Ju"}
								style={{
									"--framer-link-text-color": "rgb(0, 153, 255)",
									"--framer-link-text-decoration": "underline",
								}}
								verticalAlignment={"top"}
								withExternalLayout={true}
							>
								<React.Fragment>
									<motion.h2
										className={"framer-styles-preset-157lx9s"}
										data-styles-preset={"zdGnSmc2f"}
									>
										{
											"If you prefer not to fill out forms, feel free to email me directly and let's talk about the next big thing!"
										}
									</motion.h2>
								</React.Fragment>
							</RichText>
						</motion.div>
						<motion.section
							className={"framer-1nnq4af"}
							data-framer-name={"Content"}
							layoutDependency={layoutDependency}
							layoutId={"XsYktxRAP"}
						>
							<motion.div
								className={"framer-pbnt1a"}
								data-framer-name={"Email + Phone"}
								layoutDependency={layoutDependency}
								layoutId={"HhXwP7egd"}
							>
								<ComponentViewportProvider height={29}>
									<SmartComponentScopedContainer
										className={"framer-13addyh-container"}
										layoutDependency={layoutDependency}
										layoutId={"YikcOX2OT-container"}
										nodeId={"YikcOX2OT"}
										rendersWithMotion={true}
										scopeId={"cmXbPL8Nf"}
									>
										{_jsx(stdin_default, {
											gaudSAYyV: "tel:+20 12345678",
											gnxB9JgXH: "(+20) 1012345678",
											height: "100%",
											id: "YikcOX2OT",
											Ke1ihOPDv: true,
											layoutId: "YikcOX2OT",
											variant: "JpxTAmqKP",
											width: "100%",
											...addPropertyOverrides(
												{
													kif8CK8Tz: {
														variant: "gZZq7oJv9",
													},
													SJWKFfZ8_: {
														variant: "gZZq7oJv9",
													},
												},
												baseVariant,
												gestureVariant,
											),
										})}
									</SmartComponentScopedContainer>
								</ComponentViewportProvider>
								<ComponentViewportProvider height={29}>
									<SmartComponentScopedContainer
										className={"framer-1dn4ysc-container"}
										layoutDependency={layoutDependency}
										layoutId={"rLFGfisGO-container"}
										nodeId={"rLFGfisGO"}
										rendersWithMotion={true}
										scopeId={"cmXbPL8Nf"}
									>
										{_jsx(stdin_default, {
											gaudSAYyV: "mailto:hello@nolan.com",
											gnxB9JgXH: "hello@nolan.com",
											height: "100%",
											id: "rLFGfisGO",
											Ke1ihOPDv: true,
											layoutId: "rLFGfisGO",
											variant: "JpxTAmqKP",
											width: "100%",
											...addPropertyOverrides(
												{
													kif8CK8Tz: {
														variant: "gZZq7oJv9",
													},
													SJWKFfZ8_: {
														variant: "gZZq7oJv9",
													},
												},
												baseVariant,
												gestureVariant,
											),
										})}
									</SmartComponentScopedContainer>
								</ComponentViewportProvider>
							</motion.div>
							<motion.div
								className={"framer-k2jkju"}
								data-framer-name={"Box"}
								layoutDependency={layoutDependency}
								layoutId={"mboN6RHO7"}
								style={{
									backdropFilter: "blur(10px)",
									borderBottomLeftRadius: 24,
									borderBottomRightRadius: 24,
									borderTopLeftRadius: 24,
									borderTopRightRadius: 24,
									boxShadow:
										"inset 0px 1px 0px 1px var(--token-4ad2450b-089e-49a2-b079-884bae7e4c6d, rgba(0, 0, 0, 0.02))",
									WebkitBackdropFilter: "blur(10px)",
								}}
								variants={{
									kif8CK8Tz: {
										borderBottomLeftRadius: 16,
										borderBottomRightRadius: 16,
										borderTopLeftRadius: 16,
										borderTopRightRadius: 16,
									},
								}}
							>
								<FormContainer
									action={
										"https://api.framer.com/forms/v1/forms/cfbed335-ca88-40ef-acf3-80d6cf6f04a9/submit"
									}
									className={"framer-1678973"}
									layoutDependency={layoutDependency}
									layoutId={"V1ubPwoKK"}
									nodeId={"V1ubPwoKK"}
								>
									{(formState) => (
										<_Fragment>
											<motion.label
												className={"framer-19kfhvv"}
												data-framer-name={"Name"}
												layoutDependency={layoutDependency}
												layoutId={"yrOTpg8Hn"}
											>
												<RichText
													__fromCanvasComponent={true}
													className={"framer-59fntn"}
													data-framer-name={"Label"}
													fonts={["Inter"]}
													layoutDependency={layoutDependency}
													layoutId={"pWl5iZTIm"}
													verticalAlignment={"top"}
													withExternalLayout={true}
												>
													<React.Fragment>
														<motion.p
															className={"framer-styles-preset-1jepal"}
															data-styles-preset={"LM8JVdUMr"}
														>
															{"Full name"}
														</motion.p>
													</React.Fragment>
												</RichText>
												<FormPlainTextInput
													className={"framer-10km0wr"}
													inputName={"Name"}
													layoutDependency={layoutDependency}
													layoutId={"iretC21d8"}
													placeholder={"ex. John Smith"}
													required={true}
													style={{
														"--framer-input-background":
															"var(--token-efbe759a-c6fd-4186-bb39-f926ba3e6290, rgba(0, 0, 0, 0.04))",
														"--framer-input-border-bottom-width": "1px",
														"--framer-input-border-color":
															"var(--token-bc0dc324-3347-4f8c-8b15-0992ca3d8bd7, rgba(0, 0, 0, 0.04))",
														"--framer-input-border-left-width": "1px",
														"--framer-input-border-radius-bottom-left": "12px",
														"--framer-input-border-radius-bottom-right": "12px",
														"--framer-input-border-radius-top-left": "12px",
														"--framer-input-border-radius-top-right": "12px",
														"--framer-input-border-right-width": "1px",
														"--framer-input-border-style": "solid",
														"--framer-input-border-top-width": "1px",
														"--framer-input-font-color":
															"var(--token-5fde730a-8086-4528-a317-d71b3bf4efde, rgb(255, 255, 255))",
														"--framer-input-icon-color": "rgb(153, 153, 153)",
														"--framer-input-placeholder-color":
															"var(--token-46fcdfa9-54c0-493b-b93f-fa8d2ec6c393, rgba(255, 255, 255, 0.48))",
													}}
													type={"text"}
												/>
											</motion.label>
											<motion.label
												className={"framer-1h4y4f8"}
												data-framer-name={"Email"}
												layoutDependency={layoutDependency}
												layoutId={"G_kIGbs04"}
											>
												<RichText
													__fromCanvasComponent={true}
													className={"framer-1xjwq7i"}
													data-framer-name={"Label"}
													fonts={["Inter"]}
													layoutDependency={layoutDependency}
													layoutId={"xJ_olVJG9"}
													verticalAlignment={"top"}
													withExternalLayout={true}
												>
													<React.Fragment>
														<motion.p
															className={"framer-styles-preset-1jepal"}
															data-styles-preset={"LM8JVdUMr"}
														>
															{"Email"}
														</motion.p>
													</React.Fragment>
												</RichText>
												<FormPlainTextInput
													className={"framer-1e103yb"}
													inputName={"Email"}
													layoutDependency={layoutDependency}
													layoutId={"YzNnF4azH"}
													placeholder={"hello@website.com"}
													required={true}
													style={{
														"--framer-input-background":
															"var(--token-efbe759a-c6fd-4186-bb39-f926ba3e6290, rgba(0, 0, 0, 0.04))",
														"--framer-input-border-bottom-width": "1px",
														"--framer-input-border-color":
															"var(--token-bc0dc324-3347-4f8c-8b15-0992ca3d8bd7, rgba(0, 0, 0, 0.04))",
														"--framer-input-border-left-width": "1px",
														"--framer-input-border-radius-bottom-left": "12px",
														"--framer-input-border-radius-bottom-right": "12px",
														"--framer-input-border-radius-top-left": "12px",
														"--framer-input-border-radius-top-right": "12px",
														"--framer-input-border-right-width": "1px",
														"--framer-input-border-style": "solid",
														"--framer-input-border-top-width": "1px",
														"--framer-input-font-color":
															"var(--token-5fde730a-8086-4528-a317-d71b3bf4efde, rgb(255, 255, 255))",
														"--framer-input-icon-color": "rgb(153, 153, 153)",
														"--framer-input-placeholder-color":
															"var(--token-46fcdfa9-54c0-493b-b93f-fa8d2ec6c393, rgba(0, 0, 0, 0.48))",
													}}
													type={"email"}
												/>
											</motion.label>
											<motion.div
												className={"framer-lkdd18"}
												data-framer-name={"Section"}
												layoutDependency={layoutDependency}
												layoutId={"l6xM2Mpj4"}
											>
												<motion.div
													className={"framer-bnt6ru"}
													data-framer-name={"Project Type"}
													layoutDependency={layoutDependency}
													layoutId={"Ivr4JdXU_"}
												>
													<RichText
														__fromCanvasComponent={true}
														className={"framer-1drx5bq"}
														data-framer-name={"Label"}
														fonts={["Inter"]}
														layoutDependency={layoutDependency}
														layoutId={"Ktonlt1dL"}
														verticalAlignment={"top"}
														withExternalLayout={true}
													>
														<React.Fragment>
															<motion.p
																className={"framer-styles-preset-1jepal"}
																data-styles-preset={"LM8JVdUMr"}
															>
																{"What's Your Project About?"}
															</motion.p>
														</React.Fragment>
													</RichText>
													<motion.div
														className={"framer-3doa2s"}
														data-framer-name={"Selection"}
														layoutDependency={layoutDependency}
														layoutId={"lifrVGNXr"}
													>
														<motion.label
															className={"framer-azn9at"}
															layoutDependency={layoutDependency}
															layoutId={"ZJDxWTmKv"}
														>
															<FormBooleanInput
																className={"framer-1w86fvl"}
																defaultChecked={false}
																inputName={"Multipage Website Design"}
																layoutDependency={layoutDependency}
																layoutId={"A4xf5QZw4"}
																style={{
																	"--framer-input-background":
																		"var(--token-efbe759a-c6fd-4186-bb39-f926ba3e6290, rgba(0, 0, 0, 0.04))",
																	"--framer-input-boolean-checked-background":
																		"var(--token-5fde730a-8086-4528-a317-d71b3bf4efde, rgb(255, 255, 255))",
																	"--framer-input-border-bottom-width": "1px",
																	"--framer-input-border-color":
																		"var(--token-bc0dc324-3347-4f8c-8b15-0992ca3d8bd7, rgba(0, 0, 0, 0.04))",
																	"--framer-input-border-left-width": "1px",
																	"--framer-input-border-radius-bottom-left":
																		"6px",
																	"--framer-input-border-radius-bottom-right":
																		"6px",
																	"--framer-input-border-radius-top-left":
																		"6px",
																	"--framer-input-border-radius-top-right":
																		"6px",
																	"--framer-input-border-right-width": "1px",
																	"--framer-input-border-style": "solid",
																	"--framer-input-border-top-width": "1px",
																	"--framer-input-icon-color":
																		"var(--token-62d5ebd4-5867-40fc-ba4d-ed46a167a079, rgb(0, 0, 0))",
																}}
																type={"checkbox"}
															/>
															<RichText
																__fromCanvasComponent={true}
																className={"framer-gj2bt8"}
																data-framer-name={"Text"}
																fonts={["Inter"]}
																layoutDependency={layoutDependency}
																layoutId={"jF0gfJOb1"}
																verticalAlignment={"top"}
																withExternalLayout={true}
															>
																<React.Fragment>
																	<motion.p
																		className={"framer-styles-preset-1jepal"}
																		data-styles-preset={"LM8JVdUMr"}
																	>
																		{"Multipage Website Design"}
																	</motion.p>
																</React.Fragment>
															</RichText>
														</motion.label>
														<motion.label
															className={"framer-1fm9cet"}
															layoutDependency={layoutDependency}
															layoutId={"IGRozri7t"}
														>
															<FormBooleanInput
																className={"framer-jsxsvy"}
																defaultChecked={false}
																inputName={"Landing Page Design"}
																layoutDependency={layoutDependency}
																layoutId={"FDuPkf_zl"}
																style={{
																	"--framer-input-background":
																		"var(--token-efbe759a-c6fd-4186-bb39-f926ba3e6290, rgba(0, 0, 0, 0.04))",
																	"--framer-input-boolean-checked-background":
																		"var(--token-5fde730a-8086-4528-a317-d71b3bf4efde, rgb(255, 255, 255))",
																	"--framer-input-border-bottom-width": "1px",
																	"--framer-input-border-color":
																		"var(--token-bc0dc324-3347-4f8c-8b15-0992ca3d8bd7, rgba(0, 0, 0, 0.04))",
																	"--framer-input-border-left-width": "1px",
																	"--framer-input-border-radius-bottom-left":
																		"6px",
																	"--framer-input-border-radius-bottom-right":
																		"6px",
																	"--framer-input-border-radius-top-left":
																		"6px",
																	"--framer-input-border-radius-top-right":
																		"6px",
																	"--framer-input-border-right-width": "1px",
																	"--framer-input-border-style": "solid",
																	"--framer-input-border-top-width": "1px",
																	"--framer-input-icon-color":
																		"var(--token-62d5ebd4-5867-40fc-ba4d-ed46a167a079, rgb(0, 0, 0))",
																}}
																type={"checkbox"}
															/>
															<RichText
																__fromCanvasComponent={true}
																className={"framer-u58l7o"}
																data-framer-name={"Text"}
																fonts={["Inter"]}
																layoutDependency={layoutDependency}
																layoutId={"cKOZ4FF7D"}
																verticalAlignment={"top"}
																withExternalLayout={true}
															>
																<React.Fragment>
																	<motion.p
																		className={"framer-styles-preset-1jepal"}
																		data-styles-preset={"LM8JVdUMr"}
																	>
																		{"Landing Page Design"}
																	</motion.p>
																</React.Fragment>
															</RichText>
														</motion.label>
														<motion.label
															className={"framer-16k0d27"}
															layoutDependency={layoutDependency}
															layoutId={"wBf4LWiWn"}
														>
															<FormBooleanInput
																className={"framer-pfgf5c"}
																defaultChecked={false}
																inputName={"Framer Website Development"}
																layoutDependency={layoutDependency}
																layoutId={"hHzF27VYc"}
																style={{
																	"--framer-input-background":
																		"var(--token-efbe759a-c6fd-4186-bb39-f926ba3e6290, rgba(0, 0, 0, 0.04))",
																	"--framer-input-boolean-checked-background":
																		"var(--token-5fde730a-8086-4528-a317-d71b3bf4efde, rgb(255, 255, 255))",
																	"--framer-input-border-bottom-width": "1px",
																	"--framer-input-border-color":
																		"var(--token-bc0dc324-3347-4f8c-8b15-0992ca3d8bd7, rgba(0, 0, 0, 0.04))",
																	"--framer-input-border-left-width": "1px",
																	"--framer-input-border-radius-bottom-left":
																		"6px",
																	"--framer-input-border-radius-bottom-right":
																		"6px",
																	"--framer-input-border-radius-top-left":
																		"6px",
																	"--framer-input-border-radius-top-right":
																		"6px",
																	"--framer-input-border-right-width": "1px",
																	"--framer-input-border-style": "solid",
																	"--framer-input-border-top-width": "1px",
																	"--framer-input-icon-color":
																		"var(--token-62d5ebd4-5867-40fc-ba4d-ed46a167a079, rgb(0, 0, 0))",
																}}
																type={"checkbox"}
															/>
															<RichText
																__fromCanvasComponent={true}
																className={"framer-15j5uuw"}
																data-framer-name={"Text"}
																fonts={["Inter"]}
																layoutDependency={layoutDependency}
																layoutId={"oZNyvMGgL"}
																verticalAlignment={"top"}
																withExternalLayout={true}
															>
																<React.Fragment>
																	<motion.p
																		className={"framer-styles-preset-1jepal"}
																		data-styles-preset={"LM8JVdUMr"}
																	>
																		{"Framer Website Development"}
																	</motion.p>
																</React.Fragment>
															</RichText>
														</motion.label>
														<motion.label
															className={"framer-9er02c"}
															layoutDependency={layoutDependency}
															layoutId={"wsKjB4JKw"}
														>
															<FormBooleanInput
																className={"framer-18lbztk"}
																defaultChecked={false}
																inputName={"Framer Landing Page Development"}
																layoutDependency={layoutDependency}
																layoutId={"wEytwIprg"}
																style={{
																	"--framer-input-background":
																		"var(--token-efbe759a-c6fd-4186-bb39-f926ba3e6290, rgba(0, 0, 0, 0.04))",
																	"--framer-input-boolean-checked-background":
																		"var(--token-5fde730a-8086-4528-a317-d71b3bf4efde, rgb(255, 255, 255))",
																	"--framer-input-border-bottom-width": "1px",
																	"--framer-input-border-color":
																		"var(--token-bc0dc324-3347-4f8c-8b15-0992ca3d8bd7, rgba(0, 0, 0, 0.04))",
																	"--framer-input-border-left-width": "1px",
																	"--framer-input-border-radius-bottom-left":
																		"6px",
																	"--framer-input-border-radius-bottom-right":
																		"6px",
																	"--framer-input-border-radius-top-left":
																		"6px",
																	"--framer-input-border-radius-top-right":
																		"6px",
																	"--framer-input-border-right-width": "1px",
																	"--framer-input-border-style": "solid",
																	"--framer-input-border-top-width": "1px",
																	"--framer-input-icon-color":
																		"var(--token-62d5ebd4-5867-40fc-ba4d-ed46a167a079, rgb(0, 0, 0))",
																}}
																type={"checkbox"}
															/>
															<RichText
																__fromCanvasComponent={true}
																className={"framer-epnerd"}
																data-framer-name={"Text"}
																fonts={["Inter"]}
																layoutDependency={layoutDependency}
																layoutId={"ljeOFHkDj"}
																verticalAlignment={"top"}
																withExternalLayout={true}
															>
																<React.Fragment>
																	<motion.p
																		className={"framer-styles-preset-1jepal"}
																		data-styles-preset={"LM8JVdUMr"}
																	>
																		{"Framer Landing Page Development"}
																	</motion.p>
																</React.Fragment>
															</RichText>
														</motion.label>
													</motion.div>
												</motion.div>
												<motion.div
													className={"framer-1sc0o4p"}
													data-framer-name={"Project Budget"}
													layoutDependency={layoutDependency}
													layoutId={"gsdThu9eS"}
												>
													<RichText
														__fromCanvasComponent={true}
														className={"framer-d1gijy"}
														data-framer-name={"Label"}
														fonts={["Inter"]}
														layoutDependency={layoutDependency}
														layoutId={"PSPP7JqsN"}
														verticalAlignment={"top"}
														withExternalLayout={true}
													>
														<React.Fragment>
															<motion.p
																className={"framer-styles-preset-1jepal"}
																data-styles-preset={"LM8JVdUMr"}
															>
																{"Project Budget"}
															</motion.p>
														</React.Fragment>
													</RichText>
													<motion.div
														className={"framer-1avcaz1"}
														data-framer-name={"Selection"}
														layoutDependency={layoutDependency}
														layoutId={"DDATkcWNT"}
													>
														<motion.label
															className={"framer-7wph5g"}
															layoutDependency={layoutDependency}
															layoutId={"DWqUgxvh9"}
														>
															<FormBooleanInput
																className={"framer-1gdi3lg"}
																defaultChecked={false}
																defaultValue={"$1k \u2013 $5k"}
																inputName={"Radio"}
																layoutDependency={layoutDependency}
																layoutId={"WEZRLSgE0"}
																style={{
																	"--framer-input-background":
																		"var(--token-efbe759a-c6fd-4186-bb39-f926ba3e6290, rgba(0, 0, 0, 0.04))",
																	"--framer-input-boolean-checked-box-shadow":
																		"inset 0px 0px 0px 6px var(--token-5fde730a-8086-4528-a317-d71b3bf4efde, rgb(255, 255, 255))",
																	"--framer-input-border-bottom-width": "1px",
																	"--framer-input-border-color":
																		"var(--token-bc0dc324-3347-4f8c-8b15-0992ca3d8bd7, rgba(0, 0, 0, 0.04))",
																	"--framer-input-border-left-width": "1px",
																	"--framer-input-border-radius-bottom-left":
																		"12px",
																	"--framer-input-border-radius-bottom-right":
																		"12px",
																	"--framer-input-border-radius-top-left":
																		"12px",
																	"--framer-input-border-radius-top-right":
																		"12px",
																	"--framer-input-border-right-width": "1px",
																	"--framer-input-border-style": "solid",
																	"--framer-input-border-top-width": "1px",
																	"--framer-input-icon-mask-image": "none",
																}}
																type={"radio"}
															/>
															<RichText
																__fromCanvasComponent={true}
																className={"framer-d66dbz"}
																fonts={["Inter"]}
																layoutDependency={layoutDependency}
																layoutId={"pPT4vb1_o"}
																verticalAlignment={"top"}
																withExternalLayout={true}
															>
																<React.Fragment>
																	<motion.p
																		className={"framer-styles-preset-1jepal"}
																		data-styles-preset={"LM8JVdUMr"}
																	>
																		{"$1k \u2013 $5k"}
																	</motion.p>
																</React.Fragment>
															</RichText>
														</motion.label>
														<motion.label
															className={"framer-leo32o"}
															layoutDependency={layoutDependency}
															layoutId={"vLnXLMjXd"}
														>
															<FormBooleanInput
																className={"framer-xpoivc"}
																defaultChecked={false}
																defaultValue={"$5k \u2013 $10k"}
																inputName={"Radio"}
																layoutDependency={layoutDependency}
																layoutId={"x2pWcqR26"}
																style={{
																	"--framer-input-background":
																		"var(--token-efbe759a-c6fd-4186-bb39-f926ba3e6290, rgba(0, 0, 0, 0.04))",
																	"--framer-input-boolean-checked-box-shadow":
																		"inset 0px 0px 0px 6px var(--token-5fde730a-8086-4528-a317-d71b3bf4efde, rgb(255, 255, 255))",
																	"--framer-input-border-bottom-width": "1px",
																	"--framer-input-border-color":
																		"var(--token-bc0dc324-3347-4f8c-8b15-0992ca3d8bd7, rgba(0, 0, 0, 0.04))",
																	"--framer-input-border-left-width": "1px",
																	"--framer-input-border-radius-bottom-left":
																		"12px",
																	"--framer-input-border-radius-bottom-right":
																		"12px",
																	"--framer-input-border-radius-top-left":
																		"12px",
																	"--framer-input-border-radius-top-right":
																		"12px",
																	"--framer-input-border-right-width": "1px",
																	"--framer-input-border-style": "solid",
																	"--framer-input-border-top-width": "1px",
																	"--framer-input-icon-mask-image": "none",
																}}
																type={"radio"}
															/>
															<RichText
																__fromCanvasComponent={true}
																className={"framer-432cb6"}
																fonts={["Inter"]}
																layoutDependency={layoutDependency}
																layoutId={"T0ATT2HoJ"}
																verticalAlignment={"top"}
																withExternalLayout={true}
															>
																<React.Fragment>
																	<motion.p
																		className={"framer-styles-preset-1jepal"}
																		data-styles-preset={"LM8JVdUMr"}
																	>
																		{"$5k \u2013 $10k"}
																	</motion.p>
																</React.Fragment>
															</RichText>
														</motion.label>
														<motion.label
															className={"framer-8vph3p"}
															layoutDependency={layoutDependency}
															layoutId={"CtBXSQ_Cg"}
														>
															<FormBooleanInput
																className={"framer-3ouxet"}
																defaultChecked={false}
																defaultValue={"$10k \u2013 $20k"}
																inputName={"Radio"}
																layoutDependency={layoutDependency}
																layoutId={"o0p_0iNou"}
																style={{
																	"--framer-input-background":
																		"var(--token-efbe759a-c6fd-4186-bb39-f926ba3e6290, rgba(0, 0, 0, 0.04))",
																	"--framer-input-boolean-checked-box-shadow":
																		"inset 0px 0px 0px 6px var(--token-5fde730a-8086-4528-a317-d71b3bf4efde, rgb(255, 255, 255))",
																	"--framer-input-border-bottom-width": "1px",
																	"--framer-input-border-color":
																		"var(--token-bc0dc324-3347-4f8c-8b15-0992ca3d8bd7, rgba(0, 0, 0, 0.04))",
																	"--framer-input-border-left-width": "1px",
																	"--framer-input-border-radius-bottom-left":
																		"12px",
																	"--framer-input-border-radius-bottom-right":
																		"12px",
																	"--framer-input-border-radius-top-left":
																		"12px",
																	"--framer-input-border-radius-top-right":
																		"12px",
																	"--framer-input-border-right-width": "1px",
																	"--framer-input-border-style": "solid",
																	"--framer-input-border-top-width": "1px",
																	"--framer-input-icon-mask-image": "none",
																}}
																type={"radio"}
															/>
															<RichText
																__fromCanvasComponent={true}
																className={"framer-y9imwu"}
																fonts={["Inter"]}
																layoutDependency={layoutDependency}
																layoutId={"gffM8y3VJ"}
																verticalAlignment={"top"}
																withExternalLayout={true}
															>
																<React.Fragment>
																	<motion.p
																		className={"framer-styles-preset-1jepal"}
																		data-styles-preset={"LM8JVdUMr"}
																	>
																		{"$10k \u2013 $20k"}
																	</motion.p>
																</React.Fragment>
															</RichText>
														</motion.label>
														<motion.label
															className={"framer-225ei6"}
															layoutDependency={layoutDependency}
															layoutId={"f2qpREgEY"}
														>
															<FormBooleanInput
																className={"framer-77my0k"}
																defaultChecked={false}
																defaultValue={"> $20k"}
																inputName={"Radio"}
																layoutDependency={layoutDependency}
																layoutId={"Rh0qRdBAI"}
																style={{
																	"--framer-input-background":
																		"var(--token-efbe759a-c6fd-4186-bb39-f926ba3e6290, rgba(0, 0, 0, 0.04))",
																	"--framer-input-boolean-checked-box-shadow":
																		"inset 0px 0px 0px 6px var(--token-5fde730a-8086-4528-a317-d71b3bf4efde, rgb(255, 255, 255))",
																	"--framer-input-border-bottom-width": "1px",
																	"--framer-input-border-color":
																		"var(--token-bc0dc324-3347-4f8c-8b15-0992ca3d8bd7, rgba(0, 0, 0, 0.04))",
																	"--framer-input-border-left-width": "1px",
																	"--framer-input-border-radius-bottom-left":
																		"12px",
																	"--framer-input-border-radius-bottom-right":
																		"12px",
																	"--framer-input-border-radius-top-left":
																		"12px",
																	"--framer-input-border-radius-top-right":
																		"12px",
																	"--framer-input-border-right-width": "1px",
																	"--framer-input-border-style": "solid",
																	"--framer-input-border-top-width": "1px",
																	"--framer-input-icon-mask-image": "none",
																}}
																type={"radio"}
															/>
															<RichText
																__fromCanvasComponent={true}
																className={"framer-192g457"}
																fonts={["Inter"]}
																layoutDependency={layoutDependency}
																layoutId={"plkhoX1t6"}
																verticalAlignment={"top"}
																withExternalLayout={true}
															>
																<React.Fragment>
																	<motion.p
																		className={"framer-styles-preset-1jepal"}
																		data-styles-preset={"LM8JVdUMr"}
																	>
																		{"> $20k"}
																	</motion.p>
																</React.Fragment>
															</RichText>
														</motion.label>
													</motion.div>
												</motion.div>
											</motion.div>
											<motion.label
												className={"framer-1xcsud6"}
												data-framer-name={"More Details"}
												layoutDependency={layoutDependency}
												layoutId={"xlg31mKMI"}
											>
												<RichText
													__fromCanvasComponent={true}
													className={"framer-24vqxw"}
													data-framer-name={"Label"}
													fonts={["Inter"]}
													layoutDependency={layoutDependency}
													layoutId={"MrGlOshJ0"}
													verticalAlignment={"top"}
													withExternalLayout={true}
												>
													<React.Fragment>
														<motion.p
															className={"framer-styles-preset-1jepal"}
															data-styles-preset={"LM8JVdUMr"}
														>
															{"Share More Details"}
														</motion.p>
													</React.Fragment>
												</RichText>
												<FormPlainTextInput
													className={"framer-1xb4vm3"}
													inputName={"Details"}
													layoutDependency={layoutDependency}
													layoutId={"CmacsrPJa"}
													placeholder={"About your project..."}
													required={false}
													style={{
														"--framer-input-background":
															"var(--token-efbe759a-c6fd-4186-bb39-f926ba3e6290, rgba(0, 0, 0, 0.04))",
														"--framer-input-border-bottom-width": "1px",
														"--framer-input-border-color":
															"var(--token-bc0dc324-3347-4f8c-8b15-0992ca3d8bd7, rgba(0, 0, 0, 0.04))",
														"--framer-input-border-left-width": "1px",
														"--framer-input-border-radius-bottom-left": "12px",
														"--framer-input-border-radius-bottom-right": "12px",
														"--framer-input-border-radius-top-left": "12px",
														"--framer-input-border-radius-top-right": "12px",
														"--framer-input-border-right-width": "1px",
														"--framer-input-border-style": "solid",
														"--framer-input-border-top-width": "1px",
														"--framer-input-font-color":
															"var(--token-5fde730a-8086-4528-a317-d71b3bf4efde, rgb(255, 255, 255))",
														"--framer-input-icon-color": "rgb(153, 153, 153)",
														"--framer-input-placeholder-color":
															"var(--token-46fcdfa9-54c0-493b-b93f-fa8d2ec6c393, rgba(0, 0, 0, 0.48))",
													}}
													type={"textarea"}
												/>
											</motion.label>
											<ComponentViewportProvider
												height={54}
												{...addPropertyOverrides(
													{
														kif8CK8Tz: {
															width: `calc(${componentViewport?.width || "100vw"} - 80px)`,
														},
													},
													baseVariant,
													gestureVariant,
												)}
											>
												<SmartComponentScopedContainer
													className={"framer-1tbrxnm-container"}
													layoutDependency={layoutDependency}
													layoutId={"F1JqIdtWn-container"}
													nodeId={"F1JqIdtWn"}
													rendersWithMotion={true}
													scopeId={"cmXbPL8Nf"}
												>
													{_jsx(stdin_default2, {
														height: "100%",
														id: "F1JqIdtWn",
														layoutId: "F1JqIdtWn",
														type: "submit",
														variant: formVariants(
															formState,
															{
																pending: "vtYExkIsS",
																success: "eU9XjXN9d",
															},
															"ABDaItX2g",
														),
														width: "100%",
														...addPropertyOverrides(
															{
																kif8CK8Tz: {
																	style: {
																		width: "100%",
																	},
																},
															},
															baseVariant,
															gestureVariant,
														),
													})}
												</SmartComponentScopedContainer>
											</ComponentViewportProvider>
											<motion.div
												className={"framer-1ym4338"}
												data-framer-name={"Availability"}
												layoutDependency={layoutDependency}
												layoutId={"ZkT7Y25Zk"}
											>
												<motion.div
													className={"framer-1u1oj9m"}
													data-framer-name={"Dot"}
													layoutDependency={layoutDependency}
													layoutId={"Ce8g9gQRY"}
												>
													<MotionDivWithFX
														__framer__loop={animation1}
														__framer__loopEffectEnabled={true}
														__framer__loopRepeatDelay={0.5}
														__framer__loopRepeatType={"loop"}
														__framer__loopTransition={transition3}
														__perspectiveFX={false}
														__smartComponentFX={true}
														__targetOpacity={0.7}
														className={"framer-u0smuu"}
														layoutDependency={layoutDependency}
														layoutId={"varzrtXrL"}
														style={{
															backgroundColor:
																"var(--token-cce8dd83-3970-42e1-a1b4-fa8f1ad36a75, rgb(126, 204, 0))",
															borderBottomLeftRadius: "50%",
															borderBottomRightRadius: "50%",
															borderTopLeftRadius: "50%",
															borderTopRightRadius: "50%",
															opacity: 0.7,
														}}
													/>
													<motion.div
														className={"framer-1ffrzte"}
														layoutDependency={layoutDependency}
														layoutId={"jDHyd8C9J"}
														style={{
															backgroundColor:
																"var(--token-cce8dd83-3970-42e1-a1b4-fa8f1ad36a75, rgb(126, 204, 0))",
															borderBottomLeftRadius: "50%",
															borderBottomRightRadius: "50%",
															borderTopLeftRadius: "50%",
															borderTopRightRadius: "50%",
														}}
													/>
												</motion.div>
												<RichText
													__fromCanvasComponent={true}
													className={"framer-13wezy3"}
													data-framer-name={"Text"}
													fonts={["Inter"]}
													layoutDependency={layoutDependency}
													layoutId={"tavUZJ2WB"}
													style={{
														"--framer-link-text-color": "rgb(0, 153, 255)",
														"--framer-link-text-decoration": "underline",
													}}
													verticalAlignment={"top"}
													withExternalLayout={true}
												>
													<React.Fragment>
														<motion.p
															className={"framer-styles-preset-1jepal"}
															data-styles-preset={"LM8JVdUMr"}
														>
															{"One spot available for Jun, 2025"}
														</motion.p>
													</React.Fragment>
												</RichText>
											</motion.div>
										</_Fragment>
									)}
								</FormContainer>
								<motion.div
									className={"framer-1fu6a2k"}
									data-framer-name={"BG"}
									layoutDependency={layoutDependency}
									layoutId={"S9NblIvf5"}
									style={{
										backgroundColor:
											"var(--token-5fde730a-8086-4528-a317-d71b3bf4efde, rgb(0, 0, 0))",
										opacity: 0.08,
									}}
								/>
							</motion.div>
						</motion.section>
					</motion.main>
				</Transition>
			</Variants>
		</LayoutGroup>
	);
});
var css3 = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-MOnlf.framer-tg8a2w, .framer-MOnlf .framer-tg8a2w { display: block; }",
	".framer-MOnlf.framer-nd42wg { align-content: flex-end; align-items: flex-end; display: flex; flex-direction: column; flex-wrap: nowrap; gap: 80px; height: min-content; justify-content: center; max-width: 1920px; overflow: hidden; padding: 0px 32px 0px 32px; position: relative; width: 1440px; }",
	".framer-MOnlf .framer-108rcfv { align-content: flex-start; align-items: flex-start; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 48px; height: min-content; justify-content: center; overflow: visible; padding: 0px; position: relative; width: 100%; }",
	".framer-MOnlf .framer-xu9ok6 { flex: none; height: auto; max-width: 70%; position: relative; white-space: pre-wrap; width: 100%; word-break: break-word; word-wrap: break-word; }",
	".framer-MOnlf .framer-1nnq4af { align-content: flex-start; align-items: flex-start; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; height: min-content; justify-content: space-between; overflow: hidden; padding: 0px; position: relative; width: 100%; }",
	".framer-MOnlf .framer-pbnt1a { align-content: flex-start; align-items: flex-start; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 8px; height: min-content; justify-content: center; overflow: hidden; padding: 0px; position: relative; width: min-content; }",
	".framer-MOnlf .framer-13addyh-container, .framer-MOnlf .framer-1dn4ysc-container, .framer-MOnlf .framer-1tbrxnm-container { flex: none; height: auto; position: relative; width: auto; }",
	".framer-MOnlf .framer-k2jkju { align-content: flex-start; align-items: flex-start; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 48px; height: min-content; justify-content: center; overflow: hidden; padding: 48px; position: relative; width: 60%; will-change: var(--framer-will-change-override, transform); z-index: 1; }",
	".framer-MOnlf .framer-1678973 { align-content: flex-start; align-items: flex-start; display: flex; flex: 1 0 0px; flex-direction: column; flex-wrap: nowrap; gap: 40px; height: min-content; justify-content: flex-start; overflow: visible; padding: 0px; position: relative; width: 1px; z-index: 2; }",
	".framer-MOnlf .framer-19kfhvv, .framer-MOnlf .framer-1h4y4f8, .framer-MOnlf .framer-1xcsud6 { align-content: flex-start; align-items: flex-start; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 12px; height: min-content; justify-content: flex-start; padding: 0px; position: relative; width: 100%; }",
	".framer-MOnlf .framer-59fntn, .framer-MOnlf .framer-1xjwq7i, .framer-MOnlf .framer-1drx5bq, .framer-MOnlf .framer-d1gijy, .framer-MOnlf .framer-24vqxw { flex: none; height: auto; position: relative; white-space: pre; width: auto; }",
	'.framer-MOnlf .framer-10km0wr { --framer-input-focused-border-color: var(--token-3633f5d4-b3f9-4387-bf26-367a735dd616, rgba(255, 255, 255, 0.24)); --framer-input-focused-border-style: solid; --framer-input-focused-border-width: 1px; --framer-input-focused-transition: all 0.2s cubic-bezier(0.12,0.23,0.5,1) 0s; --framer-input-font-family: "Open Sauce Sans"; --framer-input-font-letter-spacing: -0.02em; --framer-input-font-line-height: 1.2em; --framer-input-font-size: 16px; --framer-input-font-weight: 400; --framer-input-padding: 16px; --framer-input-wrapper-height: auto; flex: none; height: auto; position: relative; width: 100%; }',
	'.framer-MOnlf .framer-1e103yb { --framer-input-focused-border-color: var(--token-3633f5d4-b3f9-4387-bf26-367a735dd616, rgba(0, 0, 0, 0.24)); --framer-input-focused-border-style: solid; --framer-input-focused-border-width: 1px; --framer-input-focused-transition: all 0.2s cubic-bezier(0.12,0.23,0.5,1) 0s; --framer-input-font-family: "Open Sauce Sans"; --framer-input-font-letter-spacing: -0.02em; --framer-input-font-line-height: 1.2em; --framer-input-font-size: 16px; --framer-input-font-weight: 400; --framer-input-padding: 16px; --framer-input-wrapper-height: auto; flex: none; height: auto; position: relative; width: 100%; }',
	".framer-MOnlf .framer-lkdd18 { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 80px; height: min-content; justify-content: center; overflow: hidden; padding: 0px; position: relative; width: 100%; }",
	".framer-MOnlf .framer-bnt6ru, .framer-MOnlf .framer-1sc0o4p { align-content: flex-start; align-items: flex-start; display: flex; flex: 1 0 0px; flex-direction: column; flex-wrap: nowrap; gap: 24px; height: min-content; justify-content: flex-start; padding: 0px; position: relative; width: 1px; }",
	".framer-MOnlf .framer-3doa2s { align-content: flex-start; align-items: flex-start; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 16px; height: min-content; justify-content: center; overflow: hidden; padding: 0px; position: relative; width: 100%; }",
	".framer-MOnlf .framer-azn9at, .framer-MOnlf .framer-1fm9cet, .framer-MOnlf .framer-16k0d27, .framer-MOnlf .framer-9er02c, .framer-MOnlf .framer-7wph5g, .framer-MOnlf .framer-leo32o, .framer-MOnlf .framer-8vph3p, .framer-MOnlf .framer-225ei6 { align-content: center; align-items: center; cursor: pointer; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 12px; height: min-content; justify-content: flex-start; padding: 0px; position: relative; width: 100%; }",
	".framer-MOnlf .framer-1w86fvl, .framer-MOnlf .framer-jsxsvy, .framer-MOnlf .framer-pfgf5c, .framer-MOnlf .framer-18lbztk, .framer-MOnlf .framer-1gdi3lg, .framer-MOnlf .framer-xpoivc, .framer-MOnlf .framer-3ouxet, .framer-MOnlf .framer-77my0k { --framer-input-boolean-checked-transition: all 0.2s cubic-bezier(0.12,0.23,0.5,1) 0s; aspect-ratio: 1 / 1; flex: none; height: var(--framer-aspect-ratio-supported, 20px); position: relative; width: 20px; }",
	".framer-MOnlf .framer-gj2bt8, .framer-MOnlf .framer-u58l7o, .framer-MOnlf .framer-15j5uuw, .framer-MOnlf .framer-epnerd, .framer-MOnlf .framer-d66dbz, .framer-MOnlf .framer-432cb6, .framer-MOnlf .framer-y9imwu, .framer-MOnlf .framer-192g457 { -webkit-user-select: none; flex: none; height: auto; position: relative; user-select: none; white-space: pre; width: auto; }",
	".framer-MOnlf .framer-1avcaz1 { align-content: center; align-items: center; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 16px; height: min-content; justify-content: center; overflow: hidden; padding: 0px; position: relative; width: 100%; }",
	'.framer-MOnlf .framer-1xb4vm3 { --framer-input-focused-border-color: var(--token-3633f5d4-b3f9-4387-bf26-367a735dd616, rgba(0, 0, 0, 0.24)); --framer-input-focused-border-style: solid; --framer-input-focused-border-width: 1px; --framer-input-focused-transition: all 0.2s cubic-bezier(0.12,0.23,0.5,1) 0s; --framer-input-font-family: "Open Sauce Sans"; --framer-input-font-letter-spacing: -0.02em; --framer-input-font-line-height: 1.2em; --framer-input-font-size: 16px; --framer-input-font-weight: 400; --framer-input-padding: 16px; --framer-input-wrapper-height: auto; --framer-textarea-resize: vertical; flex: none; height: auto; min-height: 140px; position: relative; width: 100%; }',
	".framer-MOnlf .framer-1ym4338 { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 6px; height: min-content; justify-content: center; overflow: visible; padding: 0px; position: relative; width: 100%; }",
	".framer-MOnlf .framer-1u1oj9m { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: center; overflow: visible; padding: 0px; position: relative; width: min-content; }",
	".framer-MOnlf .framer-u0smuu { bottom: 2px; flex: none; left: 2px; overflow: hidden; position: absolute; right: 2px; top: 2px; will-change: var(--framer-will-change-override, transform); z-index: 1; }",
	".framer-MOnlf .framer-1ffrzte { aspect-ratio: 1 / 1; flex: none; height: var(--framer-aspect-ratio-supported, 10px); overflow: hidden; position: relative; width: 10px; will-change: var(--framer-will-change-override, transform); z-index: 2; }",
	".framer-MOnlf .framer-13wezy3 { flex: 1 0 0px; height: auto; position: relative; white-space: pre-wrap; width: 1px; word-break: break-word; word-wrap: break-word; }",
	".framer-MOnlf .framer-1fu6a2k { bottom: 0px; flex: none; left: 0px; overflow: hidden; position: absolute; right: 0px; top: 0px; z-index: 1; }",
	".framer-MOnlf.framer-v-12rmsmh.framer-nd42wg { width: 1025px; }",
	".framer-MOnlf.framer-v-12rmsmh .framer-1gdi3lg, .framer-MOnlf.framer-v-130gd0z .framer-1gdi3lg, .framer-MOnlf.framer-v-ia4cai .framer-1gdi3lg { height: var(--framer-aspect-ratio-supported, 19px); }",
	".framer-MOnlf.framer-v-12rmsmh .framer-xpoivc, .framer-MOnlf.framer-v-12rmsmh .framer-3ouxet, .framer-MOnlf.framer-v-12rmsmh .framer-77my0k, .framer-MOnlf.framer-v-130gd0z .framer-xpoivc, .framer-MOnlf.framer-v-130gd0z .framer-3ouxet, .framer-MOnlf.framer-v-130gd0z .framer-77my0k, .framer-MOnlf.framer-v-ia4cai .framer-xpoivc, .framer-MOnlf.framer-v-ia4cai .framer-3ouxet, .framer-MOnlf.framer-v-ia4cai .framer-77my0k { height: var(--framer-aspect-ratio-supported, 16px); }",
	".framer-MOnlf.framer-v-130gd0z.framer-nd42wg { padding: 0px 24px 0px 24px; width: 200px; }",
	".framer-MOnlf.framer-v-130gd0z .framer-xu9ok6, .framer-MOnlf.framer-v-ia4cai .framer-xu9ok6 { max-width: 100%; }",
	".framer-MOnlf.framer-v-130gd0z .framer-1nnq4af { gap: 16px; justify-content: center; }",
	".framer-MOnlf.framer-v-130gd0z .framer-pbnt1a { gap: 12px; width: 35%; }",
	".framer-MOnlf.framer-v-130gd0z .framer-k2jkju { flex: 1 0 0px; flex-direction: column; padding: 32px; width: 1px; }",
	".framer-MOnlf.framer-v-130gd0z .framer-1678973 { flex: none; gap: 32px; width: 100%; }",
	".framer-MOnlf.framer-v-ia4cai.framer-nd42wg { gap: 32px; padding: 0px 16px 0px 16px; width: 200px; }",
	".framer-MOnlf.framer-v-ia4cai .framer-1nnq4af { flex-direction: column; gap: 32px; justify-content: center; }",
	".framer-MOnlf.framer-v-ia4cai .framer-pbnt1a { gap: 6px; }",
	".framer-MOnlf.framer-v-ia4cai .framer-k2jkju { flex-direction: column; padding: 24px; width: 100%; }",
	".framer-MOnlf.framer-v-ia4cai .framer-1678973 { flex: none; gap: 24px; width: 100%; }",
	".framer-MOnlf.framer-v-ia4cai .framer-19kfhvv, .framer-MOnlf.framer-v-ia4cai .framer-1h4y4f8, .framer-MOnlf.framer-v-ia4cai .framer-1xcsud6 { gap: 8px; }",
	".framer-MOnlf.framer-v-ia4cai .framer-lkdd18 { flex-direction: column; gap: 32px; }",
	".framer-MOnlf.framer-v-ia4cai .framer-bnt6ru, .framer-MOnlf.framer-v-ia4cai .framer-1sc0o4p { flex: none; width: 100%; }",
	".framer-MOnlf.framer-v-ia4cai .framer-1tbrxnm-container { width: 100%; }",
	...css2,
	...css,
];
var FramercmXbPL8Nf = withCSS(Component, css3, "framer-MOnlf");
var stdin_default3 = FramercmXbPL8Nf;
FramercmXbPL8Nf.displayName = "Contact";
FramercmXbPL8Nf.defaultProps = {
	height: 1155,
	width: 1440,
};
addPropertyControls(FramercmXbPL8Nf, {
	variant: {
		options: ["EpQq4QIe4", "mfiN6ML2V", "SJWKFfZ8_", "kif8CK8Tz"],
		optionTitles: ["Desktop", "Laptop", "Tablet", "Phone"],
		title: "Variant",
		type: ControlType.Enum,
	},
});
addFonts(
	FramercmXbPL8Nf,
	[
		{
			explicitInter: true,
			fonts: [
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
					url: "https://framerusercontent.com/assets/5vvr9Vy74if2I6bQbJvbw7SY1pQ.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
					url: "https://framerusercontent.com/assets/EOr0mi4hNtlgWNn9if640EZzXCo.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+1F00-1FFF",
					url: "https://framerusercontent.com/assets/Y9k9QrlZAqio88Klkmbd8VoMQc.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+0370-03FF",
					url: "https://framerusercontent.com/assets/OYrD2tBIBPvoJXiIHnLoOXnY9M.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
					url: "https://framerusercontent.com/assets/JeYwfuaPfZHQhEG8U5gtPDZ7WQ.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2070, U+2074-207E, U+2080-208E, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
					url: "https://framerusercontent.com/assets/GrgcKwrN6d3Uz8EwcLHZxwEfC4.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
					url: "https://framerusercontent.com/assets/b6Y37FthZeALduNqHicBT6FutY.woff2",
					weight: "400",
				},
				{
					family: "Open Sauce Sans",
					source: "builtIn",
					style: "normal",
					url: "https://framerusercontent.com/assets/VvQsG6v03iEur3JMvHc8uDrkGo.woff2",
					weight: "400",
				},
			],
		},
		...LinkFonts,
		...FormButtonFonts,
		...getFontsFromSharedStyle(fonts2),
		...getFontsFromSharedStyle(fonts),
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// virtual:contact
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {
	base: "SJWKFfZ8_",
	lg: "mfiN6ML2V",
	xl: "EpQq4QIe4",
};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"cde98c358c3069ef2a8dce28a8c2c8459e940a47824cf38ac0a6e3a305f8bfbb"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default3, {
				...rest,
			})}
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders ContactFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"cde98c358c3069ef2a8dce28a8c2c8459e940a47824cf38ac0a6e3a305f8bfbb"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				Component={stdin_default3}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default3);
var contact_default = ComponentWithRoot;
export { contact_default as default };
