// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project cde98c358c3069ef "matt.buzz", do not edit manually */
"use client";

/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
}} Props

 */
import { stdin_default } from "./chunks/nav-link.js";
import {
	className as className2,
	css as css2,
	fonts as fonts2,
} from "./chunks/hero-typography.js";
import { stdin_default as stdin_default2 } from "./chunks/text-showcase.js";
import { className, css, fonts } from "./chunks/body-typography.js";
import "./chunks/ticker.js";
import { routes } from "./chunks/routes.js";

// virtual:edu
import { Fragment as Fragment2 } from "react";
import { ContextProviders } from "unframer";

// /:https://framerusercontent.com/modules/EDgO2TqnruTxQIV4xHBm/WoEeKTUYLjcpHTkeW3cU/Oh3EUIZdn.js
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import {
	addFonts,
	addPropertyControls,
	ComponentViewportProvider,
	ControlType,
	cx,
	getFonts,
	getFontsFromSharedStyle,
	getLoadingLazyAtYPosition,
	Image,
	ResolveLinks,
	RichText,
	SmartComponentScopedContainer,
	useComponentViewport,
	useLocaleInfo,
	useRouter,
	useVariantState,
	withCSS,
	withFX,
} from "unframer";
import { LayoutGroup, motion, MotionConfigContext } from "unframer";
import * as React from "react";
import { useRef } from "react";

// /:https://framerusercontent.com/modules/kiTIBxvPfb6lfU99eF0V/RysSEByp15UOtbkOywWp/vDajAIZP7.js
import { fontStore } from "unframer";
fontStore.loadFonts(["BI;Open Sauce Sans/Medium/v0"]);
var fonts3 = [
	{
		explicitInter: true,
		fonts: [
			{
				family: "Open Sauce Sans",
				source: "builtIn",
				style: "normal",
				url: "https://framerusercontent.com/assets/O2R7AhA6wjBk0GHLJl0N8fqxN0.woff2",
				weight: "500",
			},
		],
	},
];
var css3 = [
	'.framer-ZsBYC .framer-styles-preset-1fidxhc:not(.rich-text-wrapper), .framer-ZsBYC .framer-styles-preset-1fidxhc.rich-text-wrapper p { --framer-font-family: "Open Sauce Sans", "Open Sauce Sans Placeholder", sans-serif; --framer-font-open-type-features: normal; --framer-font-size: 20px; --framer-font-style: normal; --framer-font-variation-axes: normal; --framer-font-weight: 500; --framer-letter-spacing: -0.02em; --framer-line-height: 1.2em; --framer-paragraph-spacing: 0px; --framer-text-alignment: start; --framer-text-color: var(--token-5fde730a-8086-4528-a317-d71b3bf4efde, #ffffff); --framer-text-decoration: none; --framer-text-stroke-color: initial; --framer-text-stroke-width: initial; --framer-text-transform: none; }',
	'@media (max-width: 1439px) and (min-width: 1025px) { .framer-ZsBYC .framer-styles-preset-1fidxhc:not(.rich-text-wrapper), .framer-ZsBYC .framer-styles-preset-1fidxhc.rich-text-wrapper p { --framer-font-family: "Open Sauce Sans", "Open Sauce Sans Placeholder", sans-serif; --framer-font-open-type-features: normal; --framer-font-size: 20px; --framer-font-style: normal; --framer-font-variation-axes: normal; --framer-font-weight: 500; --framer-letter-spacing: -0.02em; --framer-line-height: 1.2em; --framer-paragraph-spacing: 0px; --framer-text-alignment: start; --framer-text-color: var(--token-5fde730a-8086-4528-a317-d71b3bf4efde, #ffffff); --framer-text-decoration: none; --framer-text-stroke-color: initial; --framer-text-stroke-width: initial; --framer-text-transform: none; } }',
	'@media (max-width: 1024px) and (min-width: 700px) { .framer-ZsBYC .framer-styles-preset-1fidxhc:not(.rich-text-wrapper), .framer-ZsBYC .framer-styles-preset-1fidxhc.rich-text-wrapper p { --framer-font-family: "Open Sauce Sans", "Open Sauce Sans Placeholder", sans-serif; --framer-font-open-type-features: normal; --framer-font-size: 18px; --framer-font-style: normal; --framer-font-variation-axes: normal; --framer-font-weight: 500; --framer-letter-spacing: -0.02em; --framer-line-height: 1.2em; --framer-paragraph-spacing: 0px; --framer-text-alignment: start; --framer-text-color: var(--token-5fde730a-8086-4528-a317-d71b3bf4efde, #ffffff); --framer-text-decoration: none; --framer-text-stroke-color: initial; --framer-text-stroke-width: initial; --framer-text-transform: none; } }',
	'@media (max-width: 699px) and (min-width: 0px) { .framer-ZsBYC .framer-styles-preset-1fidxhc:not(.rich-text-wrapper), .framer-ZsBYC .framer-styles-preset-1fidxhc.rich-text-wrapper p { --framer-font-family: "Open Sauce Sans", "Open Sauce Sans Placeholder", sans-serif; --framer-font-open-type-features: normal; --framer-font-size: 16px; --framer-font-style: normal; --framer-font-variation-axes: normal; --framer-font-weight: 500; --framer-letter-spacing: -0.02em; --framer-line-height: 1.2em; --framer-paragraph-spacing: 0px; --framer-text-alignment: start; --framer-text-color: var(--token-5fde730a-8086-4528-a317-d71b3bf4efde, #ffffff); --framer-text-decoration: none; --framer-text-stroke-color: initial; --framer-text-stroke-width: initial; --framer-text-transform: none; } }',
];
var className3 = "framer-ZsBYC";

// /:https://framerusercontent.com/modules/EDgO2TqnruTxQIV4xHBm/WoEeKTUYLjcpHTkeW3cU/Oh3EUIZdn.js
var ImageWithFX = withFX(Image);
var TickerFonts = getFonts(stdin_default2);
var LinkPortfolioFonts = getFonts(stdin_default);
var cycleOrder = ["NYf9d8K13", "e_UYxB7Zy", "BR2UTbsAs", "nU7I1YtGa"];
var serializationHash = "framer-5EwEW";
var variantClassNames = {
	BR2UTbsAs: "framer-v-1vcff77",
	e_UYxB7Zy: "framer-v-153rblq",
	nU7I1YtGa: "framer-v-1n9pnbf",
	NYf9d8K13: "framer-v-9ladjt",
};
function addPropertyOverrides(overrides, ...variants) {
	const nextOverrides = {};
	variants?.forEach(
		(variant) => variant && Object.assign(nextOverrides, overrides[variant]),
	);
	return nextOverrides;
}
var transition1 = {
	bounce: 0.2,
	delay: 0,
	duration: 0.4,
	type: "spring",
};
var animation = {
	opacity: 1e-3,
	rotate: 0,
	scale: 1,
	skewX: 0,
	skewY: 0,
	x: 0,
	y: 20,
};
var transition2 = {
	damping: 80,
	delay: 0.02,
	mass: 1,
	stiffness: 400,
	type: "spring",
};
var textEffect = {
	effect: animation,
	repeat: false,
	startDelay: 0.4,
	tokenization: "character",
	transition: transition2,
	trigger: "onMount",
	type: "appear",
};
var toResponsiveImage = (value) => {
	if (
		typeof value === "object" &&
		value !== null &&
		typeof value.src === "string"
	) {
		return value;
	}
	return typeof value === "string"
		? {
				src: value,
			}
		: void 0;
};
var isSet = (value) => {
	if (Array.isArray(value)) return value.length > 0;
	return value !== void 0 && value !== null && value !== "";
};
var Transition = ({ value, children }) => {
	const config = React.useContext(MotionConfigContext);
	const transition = value ?? config.transition;
	const contextValue = React.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext.Provider value={contextValue}>
			{children}
		</MotionConfigContext.Provider>
	);
};
var Variants = motion.create(React.Fragment);
var humanReadableVariantMap = {
	Desktop: "NYf9d8K13",
	Laptop: "e_UYxB7Zy",
	Phone: "nU7I1YtGa",
	Tablet: "BR2UTbsAs",
};
var getProps = ({
	background,
	category,
	challenge,
	client,
	height,
	id,
	image1,
	image2,
	image3,
	image4,
	image5,
	image6,
	next,
	objective,
	previous,
	projectTitle,
	results,
	role,
	thumbnail,
	width,
	year,
	...props
}) => {
	return {
		...props,
		B01XONVu3: next ?? props.B01XONVu3,
		C22cdIE2E: image1 ?? props.C22cdIE2E,
		EULy8_Q5_: year ?? props.EULy8_Q5_ ?? "2025",
		fkZQL44FD: client ?? props.fkZQL44FD ?? "Alex T.",
		GVR4L0JmR: image3 ?? props.GVR4L0JmR,
		J_BryPek2: image5 ?? props.J_BryPek2,
		KL36dHpa5: image4 ?? props.KL36dHpa5,
		l19wRZOJl: thumbnail ?? props.l19wRZOJl,
		Ma3jyzJmc: projectTitle ?? props.Ma3jyzJmc ?? "Edbost",
		oRd6CbCVT: role ?? props.oRd6CbCVT ?? "UX Designer",
		PceLctrYV:
			challenge ??
			props.PceLctrYV ??
			"Independent filmmakers and digital artists lacked access to affordable, user-friendly AI tools, forcing them to rely on expensive, complex software or outsource effects work\u2014limiting creative control and scalability.",
		Px_uoypCH:
			background ??
			props.Px_uoypCH ??
			"High-end VFX and editing tools required steep learning curves and costly subscriptions, putting them out of reach for small studios and solo creators. Edbost identified the need for democratized AI-powered creative tools that simplified advanced workflows.",
		tttpWdpG6: image6 ?? props.tttpWdpG6,
		uy_Svr1ZS: image2 ?? props.uy_Svr1ZS,
		variant:
			humanReadableVariantMap[props.variant] ?? props.variant ?? "NYf9d8K13",
		Z9ngVeKB2:
			objective ??
			props.Z9ngVeKB2 ??
			"The mission was to build an accessible, cloud-based platform offering AI-driven video editing, green screen removal, and text-to-video generation. By integrating machine learning into an intuitive interface, Edbost aimed to empower creators without technical expertise.",
		zGrq8FZEk: category ?? props.zGrq8FZEk ?? "Visual Design",
		ZnDf43hgQ: previous ?? props.ZnDf43hgQ ?? "f0LvCUSVK",
		ZQSM5PkKU:
			results ??
			props.ZQSM5PkKU ??
			"Edbost became a game-changer for indie artists, enabling professional-grade results at a fraction of the cost. Its tools have been used in award-winning projects, proving that AI could level the playing field in creative industries.",
	};
};
var createLayoutDependency = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
	const fallbackRef = useRef(null);
	const refBinding = ref ?? fallbackRef;
	const defaultLayoutId = React.useId();
	const { activeLocale, setLocale } = useLocaleInfo();
	const componentViewport = useComponentViewport();
	const {
		style,
		className: className4,
		layoutId,
		variant,
		Ma3jyzJmc,
		zGrq8FZEk,
		l19wRZOJl,
		Px_uoypCH,
		fkZQL44FD,
		oRd6CbCVT,
		EULy8_Q5_,
		C22cdIE2E,
		uy_Svr1ZS,
		PceLctrYV,
		Z9ngVeKB2,
		ZQSM5PkKU,
		GVR4L0JmR,
		KL36dHpa5,
		J_BryPek2,
		tttpWdpG6,
		ZnDf43hgQ,
		B01XONVu3,
		previousItemIdBI7ZQ0OEo,
		previousItemId_T7gBS1DsSBI7ZQ0OEo,
		nextItemIdBI7ZQ0OEo,
		nextItemId_T7gBS1DsSBI7ZQ0OEo,
		...restProps
	} = getProps(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState({
		cycleOrder,
		defaultVariant: "NYf9d8K13",
		ref: refBinding,
		variant,
		variantClassNames,
	});
	const layoutDependency = createLayoutDependency(props, variants);
	const sharedStyleClassNames = [className2, className3, className];
	const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
	const visible = isSet(Z9ngVeKB2);
	const visible1 = isSet(ZQSM5PkKU);
	const visible2 = isSet(GVR4L0JmR);
	const visible3 = isSet(KL36dHpa5);
	const visible4 = isSet(J_BryPek2);
	const visible5 = isSet(tttpWdpG6);
	const visible6 = isSet(previousItemIdBI7ZQ0OEo);
	const isDisplayed = (value) => {
		if (baseVariant === "nU7I1YtGa") return value;
		return true;
	};
	const visible7 = isSet(ZnDf43hgQ);
	const router = useRouter();
	const visible8 = isSet(nextItemIdBI7ZQ0OEo);
	const visible9 = isSet(B01XONVu3);
	return (
		<LayoutGroup id={layoutId ?? defaultLayoutId}>
			<Variants animate={variants} initial={false}>
				<Transition value={transition1}>
					<motion.main
						{...restProps}
						{...gestureHandlers}
						className={cx(
							scopingClassNames,
							"framer-9ladjt",
							className4,
							classNames,
						)}
						data-framer-name={"Desktop"}
						layoutDependency={layoutDependency}
						layoutId={"NYf9d8K13"}
						ref={refBinding}
						style={{
							...style,
						}}
						{...addPropertyOverrides(
							{
								BR2UTbsAs: {
									"data-framer-name": "Tablet",
								},
								e_UYxB7Zy: {
									"data-framer-name": "Laptop",
								},
								nU7I1YtGa: {
									"data-framer-name": "Phone",
								},
							},
							baseVariant,
							gestureVariant,
						)}
					>
						<motion.section
							className={"framer-1o3laja"}
							data-framer-name={"Heading"}
							layoutDependency={layoutDependency}
							layoutId={"zBITkktJz"}
						>
							<motion.div
								className={"framer-1kdlw5h"}
								data-framer-name={"Title"}
								layoutDependency={layoutDependency}
								layoutId={"px4ZCw2Rx"}
							>
								<RichText
									__fromCanvasComponent={true}
									className={"framer-1vojahi"}
									data-framer-name={"Text"}
									effect={textEffect}
									fonts={["Inter"]}
									layoutDependency={layoutDependency}
									layoutId={"UrszBeDxt"}
									style={{
										"--framer-link-text-color": "rgb(0, 153, 255)",
										"--framer-link-text-decoration": "underline",
									}}
									text={Ma3jyzJmc}
									verticalAlignment={"top"}
									withExternalLayout={true}
								>
									<React.Fragment>
										<motion.h2
											className={"framer-styles-preset-157lx9s"}
											data-styles-preset={"zdGnSmc2f"}
										>
											{"Gamma"}
										</motion.h2>
									</React.Fragment>
								</RichText>
								<RichText
									__fromCanvasComponent={true}
									className={"framer-clst47"}
									data-framer-name={"Text"}
									fonts={["Inter"]}
									layoutDependency={layoutDependency}
									layoutId={"E3878Omxd"}
									style={{
										"--framer-link-text-color": "rgb(0, 153, 255)",
										"--framer-link-text-decoration": "underline",
										opacity: 0.5,
									}}
									text={zGrq8FZEk}
									verticalAlignment={"top"}
									withExternalLayout={true}
								>
									<React.Fragment>
										<motion.p
											className={"framer-styles-preset-1fidxhc"}
											data-styles-preset={"vDajAIZP7"}
										>
											{"App Design"}
										</motion.p>
									</React.Fragment>
								</RichText>
							</motion.div>
							<motion.div
								className={"framer-1fg0yzc"}
								data-framer-name={"Image"}
								layoutDependency={layoutDependency}
								layoutId={"U1YPjjeJn"}
								style={{
									borderBottomLeftRadius: 32,
									borderBottomRightRadius: 32,
									borderTopLeftRadius: 32,
									borderTopRightRadius: 32,
								}}
								variants={{
									BR2UTbsAs: {
										borderBottomLeftRadius: 24,
										borderBottomRightRadius: 24,
										borderTopLeftRadius: 24,
										borderTopRightRadius: 24,
									},
									nU7I1YtGa: {
										borderBottomLeftRadius: 16,
										borderBottomRightRadius: 16,
										borderTopLeftRadius: 16,
										borderTopRightRadius: 16,
									},
								}}
							>
								<ImageWithFX
									__framer__adjustPosition={false}
									__framer__offset={0}
									__framer__parallaxTransformEnabled={true}
									__framer__speed={85}
									__perspectiveFX={false}
									__smartComponentFX={true}
									__targetOpacity={1}
									background={{
										alt: "",
										fit: "fit",
										loading: getLoadingLazyAtYPosition(
											(componentViewport?.y || 0) +
												0 +
												(((componentViewport?.height || 200) - 0 - 3997) / 2 +
													0 +
													0) +
												0 +
												141.6 +
												-120,
										),
										sizes: `calc((${componentViewport?.width || "100vw"} - 64px) * 1.1)`,
										...toResponsiveImage(l19wRZOJl),
										...{
											positionX: "center",
											positionY: "center",
										},
									}}
									className={"framer-9su0hj"}
									layoutDependency={layoutDependency}
									layoutId={"hUKBbpSuH"}
									style={{
										borderBottomLeftRadius: 16,
										borderBottomRightRadius: 16,
										borderTopLeftRadius: 16,
										borderTopRightRadius: 16,
									}}
									{...addPropertyOverrides(
										{
											BR2UTbsAs: {
												background: {
													alt: "",
													fit: "fill",
													loading: getLoadingLazyAtYPosition(
														(componentViewport?.y || 0) +
															0 +
															(((componentViewport?.height || 200) - 0 - 3965) /
																2 +
																0 +
																0) +
															0 +
															141.6 +
															-120,
													),
													sizes: `calc((${componentViewport?.width || "100vw"} - 48px) * 1.1)`,
													...toResponsiveImage(l19wRZOJl),
													...{
														positionX: "center",
														positionY: "center",
													},
												},
											},
											e_UYxB7Zy: {
												background: {
													alt: "",
													fit: "fill",
													loading: getLoadingLazyAtYPosition(
														(componentViewport?.y || 0) +
															0 +
															(((componentViewport?.height || 200) - 0 - 3997) /
																2 +
																0 +
																0) +
															0 +
															141.6 +
															-120,
													),
													sizes: `calc((${componentViewport?.width || "100vw"} - 64px) * 1.1)`,
													...toResponsiveImage(l19wRZOJl),
													...{
														positionX: "center",
														positionY: "center",
													},
												},
											},
											nU7I1YtGa: {
												__framer__speed: 90,
												background: {
													alt: "",
													fit: "fit",
													loading: getLoadingLazyAtYPosition(
														(componentViewport?.y || 0) +
															0 +
															(((componentViewport?.height || 200) -
																0 -
																2350.2) /
																2 +
																0 +
																0) +
															0 +
															121.6 +
															-58,
													),
													sizes: `calc((${componentViewport?.width || "100vw"} - 32px) * 1.4)`,
													...toResponsiveImage(l19wRZOJl),
													...{
														positionX: "center",
														positionY: "center",
													},
												},
											},
										},
										baseVariant,
										gestureVariant,
									)}
								/>
							</motion.div>
						</motion.section>
						<motion.section
							className={"framer-2jwi0c"}
							data-framer-name={"Details"}
							layoutDependency={layoutDependency}
							layoutId={"sz1SnZ8rT"}
						>
							<motion.div
								className={"framer-1t8hj17"}
								data-framer-name={"Text"}
								layoutDependency={layoutDependency}
								layoutId={"HOXvpUFhG"}
							>
								<RichText
									__fromCanvasComponent={true}
									className={"framer-113vhs6"}
									data-framer-name={"Text"}
									fonts={["Inter"]}
									layoutDependency={layoutDependency}
									layoutId={"fkSHYO7_u"}
									style={{
										"--framer-link-text-color": "rgb(0, 153, 255)",
										"--framer-link-text-decoration": "underline",
									}}
									text={Px_uoypCH}
									verticalAlignment={"top"}
									withExternalLayout={true}
								>
									<React.Fragment>
										<motion.p
											className={"framer-styles-preset-1jepal"}
											data-styles-preset={"LM8JVdUMr"}
										>
											{
												"Our Nike Air campaign captures the essence of the brand. Refreshingly modern and inspiring. The iconic Nike swoosh is featured prominently, symbolizing innovation and boundary pushing. Our photos showcase the Nike Air collection, capturing the feeling of liberation and self-expression that comes with wearing the sneakers. The moon features prominently, evoking feelings of yearning and possibility. Nike Air offers the perfect balance of form and function. Our campaign invites viewers to embody the Nike spirit and reach for the stars."
											}
										</motion.p>
									</React.Fragment>
								</RichText>
							</motion.div>
							<motion.div
								className={"framer-1y2uzlp"}
								data-framer-name={"Text"}
								layoutDependency={layoutDependency}
								layoutId={"KewqlNuu_"}
							>
								<motion.div
									className={"framer-1qbivlm"}
									data-framer-name={"Client"}
									layoutDependency={layoutDependency}
									layoutId={"zSwRlgT3H"}
								>
									<RichText
										__fromCanvasComponent={true}
										className={"framer-102nl4v"}
										data-framer-name={"Text"}
										fonts={["Inter"]}
										layoutDependency={layoutDependency}
										layoutId={"A0X028MwE"}
										style={{
											"--framer-link-text-color": "rgb(0, 153, 255)",
											"--framer-link-text-decoration": "underline",
											opacity: 0.5,
										}}
										verticalAlignment={"top"}
										withExternalLayout={true}
									>
										<React.Fragment>
											<motion.p
												className={"framer-styles-preset-1jepal"}
												data-styles-preset={"LM8JVdUMr"}
											>
												{"Client:"}
											</motion.p>
										</React.Fragment>
									</RichText>
									<RichText
										__fromCanvasComponent={true}
										className={"framer-1tdj66x"}
										data-framer-name={"Text"}
										fonts={["Inter"]}
										layoutDependency={layoutDependency}
										layoutId={"iwtNpx6rZ"}
										style={{
											"--framer-link-text-color": "rgb(0, 153, 255)",
											"--framer-link-text-decoration": "underline",
										}}
										text={fkZQL44FD}
										verticalAlignment={"top"}
										withExternalLayout={true}
									>
										<React.Fragment>
											<motion.p
												className={"framer-styles-preset-1jepal"}
												data-styles-preset={"LM8JVdUMr"}
											>
												{"Warduo"}
											</motion.p>
										</React.Fragment>
									</RichText>
								</motion.div>
								<motion.div
									className={"framer-9c6ja9"}
									data-framer-name={"Role"}
									layoutDependency={layoutDependency}
									layoutId={"Sj3tJgD7y"}
								>
									<RichText
										__fromCanvasComponent={true}
										className={"framer-128jbnb"}
										data-framer-name={"Text"}
										fonts={["Inter"]}
										layoutDependency={layoutDependency}
										layoutId={"GcYa3hLCQ"}
										style={{
											"--framer-link-text-color": "rgb(0, 153, 255)",
											"--framer-link-text-decoration": "underline",
											opacity: 0.5,
										}}
										verticalAlignment={"top"}
										withExternalLayout={true}
									>
										<React.Fragment>
											<motion.p
												className={"framer-styles-preset-1jepal"}
												data-styles-preset={"LM8JVdUMr"}
											>
												{"Role:"}
											</motion.p>
										</React.Fragment>
									</RichText>
									<RichText
										__fromCanvasComponent={true}
										className={"framer-uwv6x9"}
										data-framer-name={"Text"}
										fonts={["Inter"]}
										layoutDependency={layoutDependency}
										layoutId={"YAhOhgweT"}
										style={{
											"--framer-link-text-color": "rgb(0, 153, 255)",
											"--framer-link-text-decoration": "underline",
										}}
										text={oRd6CbCVT}
										verticalAlignment={"top"}
										withExternalLayout={true}
									>
										<React.Fragment>
											<motion.p
												className={"framer-styles-preset-1jepal"}
												data-styles-preset={"LM8JVdUMr"}
											>
												{"Product Designer"}
											</motion.p>
										</React.Fragment>
									</RichText>
								</motion.div>
								<motion.div
									className={"framer-1qr084g"}
									data-framer-name={"Year"}
									layoutDependency={layoutDependency}
									layoutId={"GShpeO33X"}
								>
									<RichText
										__fromCanvasComponent={true}
										className={"framer-hcdcux"}
										data-framer-name={"Text"}
										fonts={["Inter"]}
										layoutDependency={layoutDependency}
										layoutId={"ChfTGHhgT"}
										style={{
											"--framer-link-text-color": "rgb(0, 153, 255)",
											"--framer-link-text-decoration": "underline",
											opacity: 0.5,
										}}
										verticalAlignment={"top"}
										withExternalLayout={true}
									>
										<React.Fragment>
											<motion.p
												className={"framer-styles-preset-1jepal"}
												data-styles-preset={"LM8JVdUMr"}
											>
												{"Year:"}
											</motion.p>
										</React.Fragment>
									</RichText>
									<RichText
										__fromCanvasComponent={true}
										className={"framer-1l6lhhz"}
										data-framer-name={"Text"}
										fonts={["Inter"]}
										layoutDependency={layoutDependency}
										layoutId={"clNTZYJWD"}
										style={{
											"--framer-link-text-color": "rgb(0, 153, 255)",
											"--framer-link-text-decoration": "underline",
										}}
										text={EULy8_Q5_}
										verticalAlignment={"top"}
										withExternalLayout={true}
									>
										<React.Fragment>
											<motion.p
												className={"framer-styles-preset-1jepal"}
												data-styles-preset={"LM8JVdUMr"}
											>
												{"2022"}
											</motion.p>
										</React.Fragment>
									</RichText>
								</motion.div>
							</motion.div>
						</motion.section>
						<motion.section
							className={"framer-1ilzg0z"}
							data-framer-name={"Images"}
							layoutDependency={layoutDependency}
							layoutId={"yu9RZFYRZ"}
						>
							<motion.div
								className={"framer-dopl8m"}
								data-framer-name={"Image"}
								layoutDependency={layoutDependency}
								layoutId={"FE0U0yWCi"}
								style={{
									borderBottomLeftRadius: 32,
									borderBottomRightRadius: 32,
									borderTopLeftRadius: 32,
									borderTopRightRadius: 32,
								}}
								variants={{
									BR2UTbsAs: {
										borderBottomLeftRadius: 24,
										borderBottomRightRadius: 24,
										borderTopLeftRadius: 24,
										borderTopRightRadius: 24,
									},
									nU7I1YtGa: {
										borderBottomLeftRadius: 16,
										borderBottomRightRadius: 16,
										borderTopLeftRadius: 16,
										borderTopRightRadius: 16,
									},
								}}
							>
								<ImageWithFX
									__framer__adjustPosition={true}
									__framer__offset={0}
									__framer__parallaxTransformEnabled={true}
									__framer__speed={85}
									__perspectiveFX={false}
									__smartComponentFX={true}
									__targetOpacity={1}
									background={{
										alt: "",
										fit: "fit",
										intrinsicHeight: 1707,
										intrinsicWidth: 2560,
										loading: getLoadingLazyAtYPosition(
											(componentViewport?.y || 0) +
												0 +
												(((componentViewport?.height || 200) - 0 - 3997) / 2 +
													1132 +
													128) +
												0 +
												0 +
												0 +
												-120,
										),
										pixelHeight: 1667,
										pixelWidth: 2500,
										sizes: `calc((${componentViewport?.width || "100vw"} - 64px) * 1.1)`,
										...toResponsiveImage(C22cdIE2E),
										...{
											positionX: "center",
											positionY: "center",
										},
									}}
									className={"framer-jkx4if"}
									data-framer-name={"Image"}
									layoutDependency={layoutDependency}
									layoutId={"IZhjzgQMO"}
									{...addPropertyOverrides(
										{
											BR2UTbsAs: {
												background: {
													alt: "",
													fit: "fit",
													intrinsicHeight: 1707,
													intrinsicWidth: 2560,
													loading: getLoadingLazyAtYPosition(
														(componentViewport?.y || 0) +
															0 +
															(((componentViewport?.height || 200) - 0 - 3965) /
																2 +
																1132 +
																128) +
															0 +
															0 +
															0 +
															-120,
													),
													pixelHeight: 1667,
													pixelWidth: 2500,
													sizes: `calc((${componentViewport?.width || "100vw"} - 48px) * 1.1)`,
													...toResponsiveImage(C22cdIE2E),
													...{
														positionX: "center",
														positionY: "center",
													},
												},
											},
											nU7I1YtGa: {
												__framer__speed: 90,
												background: {
													alt: "",
													fit: "fit",
													intrinsicHeight: 1707,
													intrinsicWidth: 2560,
													loading: getLoadingLazyAtYPosition(
														(componentViewport?.y || 0) +
															0 +
															(((componentViewport?.height || 200) -
																0 -
																2350.2) /
																2 +
																734 +
																96) +
															0 +
															0 +
															0 +
															-58,
													),
													pixelHeight: 1667,
													pixelWidth: 2500,
													sizes: `calc((${componentViewport?.width || "100vw"} - 32px) * 1.4)`,
													...toResponsiveImage(C22cdIE2E),
													...{
														positionX: "center",
														positionY: "center",
													},
												},
											},
										},
										baseVariant,
										gestureVariant,
									)}
								/>
							</motion.div>
							<motion.div
								className={"framer-18z0wdq"}
								data-framer-name={"Image"}
								layoutDependency={layoutDependency}
								layoutId={"Ws5CHPHny"}
								style={{
									borderBottomLeftRadius: 32,
									borderBottomRightRadius: 32,
									borderTopLeftRadius: 32,
									borderTopRightRadius: 32,
								}}
								variants={{
									BR2UTbsAs: {
										borderBottomLeftRadius: 24,
										borderBottomRightRadius: 24,
										borderTopLeftRadius: 24,
										borderTopRightRadius: 24,
									},
									nU7I1YtGa: {
										borderBottomLeftRadius: 16,
										borderBottomRightRadius: 16,
										borderTopLeftRadius: 16,
										borderTopRightRadius: 16,
									},
								}}
							>
								<ImageWithFX
									__framer__adjustPosition={true}
									__framer__offset={0}
									__framer__parallaxTransformEnabled={true}
									__framer__speed={85}
									__perspectiveFX={false}
									__smartComponentFX={true}
									__targetOpacity={1}
									background={{
										alt: "",
										fit: "fit",
										intrinsicHeight: 1707,
										intrinsicWidth: 2560,
										loading: getLoadingLazyAtYPosition(
											(componentViewport?.y || 0) +
												0 +
												(((componentViewport?.height || 200) - 0 - 3997) / 2 +
													1132 +
													128) +
												0 +
												824 +
												0 +
												-120,
										),
										pixelHeight: 2346,
										pixelWidth: 2e3,
										sizes: `calc((${componentViewport?.width || "100vw"} - 64px) * 1.1)`,
										...toResponsiveImage(uy_Svr1ZS),
										...{
											positionX: "center",
											positionY: "center",
										},
									}}
									className={"framer-1dqgui8"}
									data-framer-name={"Image"}
									layoutDependency={layoutDependency}
									layoutId={"e4DzMT4hG"}
									{...addPropertyOverrides(
										{
											BR2UTbsAs: {
												background: {
													alt: "",
													fit: "fit",
													intrinsicHeight: 1707,
													intrinsicWidth: 2560,
													loading: getLoadingLazyAtYPosition(
														(componentViewport?.y || 0) +
															0 +
															(((componentViewport?.height || 200) - 0 - 3965) /
																2 +
																1132 +
																128) +
															0 +
															824 +
															0 +
															-120,
													),
													pixelHeight: 2346,
													pixelWidth: 2e3,
													sizes: `calc((${componentViewport?.width || "100vw"} - 48px) * 1.1)`,
													...toResponsiveImage(uy_Svr1ZS),
													...{
														positionX: "center",
														positionY: "center",
													},
												},
											},
											nU7I1YtGa: {
												__framer__speed: 90,
												background: {
													alt: "",
													fit: "fit",
													intrinsicHeight: 1707,
													intrinsicWidth: 2560,
													loading: getLoadingLazyAtYPosition(
														(componentViewport?.y || 0) +
															0 +
															(((componentViewport?.height || 200) -
																0 -
																2350.2) /
																2 +
																734 +
																96) +
															0 +
															306 +
															0 +
															-58,
													),
													pixelHeight: 2346,
													pixelWidth: 2e3,
													sizes: `calc((${componentViewport?.width || "100vw"} - 32px) * 1.4)`,
													...toResponsiveImage(uy_Svr1ZS),
													...{
														positionX: "center",
														positionY: "center",
													},
												},
											},
										},
										baseVariant,
										gestureVariant,
									)}
								/>
							</motion.div>
						</motion.section>
						<motion.section
							className={"framer-k8u014"}
							data-framer-name={"Ticker"}
							layoutDependency={layoutDependency}
							layoutId={"UAFbd73_l"}
						>
							<ComponentViewportProvider
								height={96}
								width={`max(${componentViewport?.width || "100vw"}, 1px)`}
								y={
									(componentViewport?.y || 0) +
									0 +
									(((componentViewport?.height || 200) - 0 - 3997) / 2 +
										2756 +
										192) +
									48
								}
								{...addPropertyOverrides(
									{
										BR2UTbsAs: {
											y:
												(componentViewport?.y || 0) +
												0 +
												(((componentViewport?.height || 200) - 0 - 3965) / 2 +
													2756 +
													192) +
												48,
										},
										nU7I1YtGa: {
											y:
												(componentViewport?.y || 0) +
												0 +
												(((componentViewport?.height || 200) - 0 - 2350.2) / 2 +
													1330 +
													144) +
												0,
										},
									},
									baseVariant,
									gestureVariant,
								)}
							>
								<SmartComponentScopedContainer
									className={"framer-167t67c-container"}
									layoutDependency={layoutDependency}
									layoutId={"pYNzUiP_T-container"}
									nodeId={"pYNzUiP_T"}
									rendersWithMotion={true}
									scopeId={"Oh3EUIZdn"}
								>
									{_jsx(stdin_default2, {
										AW9pUoArR: "",
										height: "100%",
										id: "pYNzUiP_T",
										layoutId: "pYNzUiP_T",
										Oho2iCzl9: 80,
										px8arhzxh: " Explore the full story \u22C5",
										style: {
											width: "100%",
										},
										width: "100%",
										YqnkipU9c: "",
										...addPropertyOverrides(
											{
												nU7I1YtGa: {
													Oho2iCzl9: 40,
												},
											},
											baseVariant,
											gestureVariant,
										),
									})}
								</SmartComponentScopedContainer>
							</ComponentViewportProvider>
						</motion.section>
						<motion.section
							className={"framer-qgh701"}
							data-framer-name={"Details"}
							layoutDependency={layoutDependency}
							layoutId={"e4YYtEsLO"}
						>
							<motion.div
								className={"framer-1pqswew"}
								data-framer-name={"Line"}
								layoutDependency={layoutDependency}
								layoutId={"YZfbBNoU5"}
								style={{
									backgroundColor:
										"var(--token-5fde730a-8086-4528-a317-d71b3bf4efde, rgb(255, 255, 255))",
									opacity: 0.16,
								}}
							/>
							<motion.div
								className={"framer-1dzxp7c"}
								data-framer-name={"Content"}
								layoutDependency={layoutDependency}
								layoutId={"pFJiAOQ0P"}
							>
								<motion.div
									className={"framer-1tun5"}
									data-framer-name={"Challenge"}
									layoutDependency={layoutDependency}
									layoutId={"HbrKXtjpi"}
								>
									<motion.div
										className={"framer-11baelz"}
										data-framer-name={"Title"}
										layoutDependency={layoutDependency}
										layoutId={"I6QZOPpaA"}
									>
										<RichText
											__fromCanvasComponent={true}
											className={"framer-1ihaybd"}
											data-framer-name={"Text"}
											fonts={["Inter"]}
											layoutDependency={layoutDependency}
											layoutId={"G5dowU_nR"}
											style={{
												"--framer-link-text-color": "rgb(0, 153, 255)",
												"--framer-link-text-decoration": "underline",
											}}
											verticalAlignment={"top"}
											withExternalLayout={true}
										>
											<React.Fragment>
												<motion.p
													className={"framer-styles-preset-1jepal"}
													data-styles-preset={"LM8JVdUMr"}
												>
													{"Challenge"}
												</motion.p>
											</React.Fragment>
										</RichText>
									</motion.div>
									<motion.div
										className={"framer-1ppad26"}
										data-framer-name={"Text"}
										layoutDependency={layoutDependency}
										layoutId={"dlBpO_wJO"}
									>
										<RichText
											__fromCanvasComponent={true}
											className={"framer-tc6brz"}
											data-framer-name={"Text"}
											fonts={["Inter"]}
											layoutDependency={layoutDependency}
											layoutId={"gHVdb1EYH"}
											style={{
												"--framer-link-text-color": "rgb(0, 153, 255)",
												"--framer-link-text-decoration": "underline",
											}}
											text={PceLctrYV}
											verticalAlignment={"top"}
											withExternalLayout={true}
										>
											<React.Fragment>
												<motion.p
													className={"framer-styles-preset-1jepal"}
													data-styles-preset={"LM8JVdUMr"}
												>
													{
														"Pathfinder, a navigation app designed for outdoor enthusiasts, approached me to redesign their user experience. The app aimed to provide detailed hiking trails, real-time weather updates, and safety alerts, but users reported difficulty navigating the interface. The feedback highlighted a cluttered layout, poor readability in bright sunlight, and a lack of intuitive features for route planning."
													}
												</motion.p>
											</React.Fragment>
										</RichText>
									</motion.div>
								</motion.div>
								{visible && (
									<motion.div
										className={"framer-10uw935"}
										data-framer-name={"Objective"}
										layoutDependency={layoutDependency}
										layoutId={"bWOb3RNxU"}
									>
										<motion.div
											className={"framer-2mf8v8"}
											data-framer-name={"Title"}
											layoutDependency={layoutDependency}
											layoutId={"e02hXvIjF"}
										>
											<RichText
												__fromCanvasComponent={true}
												className={"framer-14wxakw"}
												data-framer-name={"Text"}
												fonts={["Inter"]}
												layoutDependency={layoutDependency}
												layoutId={"NfgOCvPEW"}
												style={{
													"--framer-link-text-color": "rgb(0, 153, 255)",
													"--framer-link-text-decoration": "underline",
												}}
												verticalAlignment={"top"}
												withExternalLayout={true}
											>
												<React.Fragment>
													<motion.p
														className={"framer-styles-preset-1jepal"}
														data-styles-preset={"LM8JVdUMr"}
													>
														{"Objective"}
													</motion.p>
												</React.Fragment>
											</RichText>
										</motion.div>
										<motion.div
											className={"framer-xrtmd0"}
											data-framer-name={"Text"}
											layoutDependency={layoutDependency}
											layoutId={"K5FLMv4J9"}
										>
											<RichText
												__fromCanvasComponent={true}
												className={"framer-3u1se4"}
												data-framer-name={"Text"}
												fonts={["Inter"]}
												layoutDependency={layoutDependency}
												layoutId={"gCDtx6g6l"}
												style={{
													"--framer-link-text-color": "rgb(0, 153, 255)",
													"--framer-link-text-decoration": "underline",
												}}
												text={Z9ngVeKB2}
												verticalAlignment={"top"}
												withExternalLayout={true}
											>
												<React.Fragment>
													<motion.p
														className={"framer-styles-preset-1jepal"}
														data-styles-preset={"LM8JVdUMr"}
													>
														{
															"To create a streamlined and visually clear user interface that supports quick decision-making and intuitive navigation, even in challenging outdoor environments."
														}
													</motion.p>
												</React.Fragment>
											</RichText>
										</motion.div>
									</motion.div>
								)}
								{visible1 && (
									<motion.div
										className={"framer-1d1a38e"}
										data-framer-name={"Results"}
										layoutDependency={layoutDependency}
										layoutId={"Giz_S5dwJ"}
									>
										<motion.div
											className={"framer-ylng0r"}
											data-framer-name={"Title"}
											layoutDependency={layoutDependency}
											layoutId={"xso0kNZZJ"}
										>
											<RichText
												__fromCanvasComponent={true}
												className={"framer-16b0uos"}
												data-framer-name={"Text"}
												fonts={["Inter"]}
												layoutDependency={layoutDependency}
												layoutId={"cMh70AiZq"}
												style={{
													"--framer-link-text-color": "rgb(0, 153, 255)",
													"--framer-link-text-decoration": "underline",
												}}
												verticalAlignment={"top"}
												withExternalLayout={true}
											>
												<React.Fragment>
													<motion.p
														className={"framer-styles-preset-1jepal"}
														data-styles-preset={"LM8JVdUMr"}
													>
														{"Results"}
													</motion.p>
												</React.Fragment>
											</RichText>
										</motion.div>
										<motion.div
											className={"framer-kpat3u"}
											data-framer-name={"Text"}
											layoutDependency={layoutDependency}
											layoutId={"gUkotvCsR"}
										>
											<RichText
												__fromCanvasComponent={true}
												className={"framer-vrdnx7"}
												data-framer-name={"Text"}
												fonts={["Inter"]}
												layoutDependency={layoutDependency}
												layoutId={"JIQUTTq7e"}
												style={{
													"--framer-link-text-color": "rgb(0, 153, 255)",
													"--framer-link-text-decoration": "underline",
												}}
												text={ZQSM5PkKU}
												verticalAlignment={"top"}
												withExternalLayout={true}
											>
												<React.Fragment>
													<motion.p
														className={"framer-styles-preset-1jepal"}
														data-styles-preset={"LM8JVdUMr"}
													>
														{
															"he redesigned Pathfinder app launched to overwhelmingly positive reviews, with a 45% increase in user retention within the first three months. Users praised the intuitive interface, enhanced visibility, and thoughtful features tailored to outdoor use."
														}
													</motion.p>
												</React.Fragment>
											</RichText>
										</motion.div>
									</motion.div>
								)}
							</motion.div>
						</motion.section>
						<motion.section
							className={"framer-1r0crxv"}
							data-framer-name={"Images"}
							layoutDependency={layoutDependency}
							layoutId={"TDtFmVuha"}
						>
							{visible2 && (
								<motion.div
									className={"framer-1wh8mhl"}
									data-framer-name={"Image"}
									layoutDependency={layoutDependency}
									layoutId={"N9OSCwRk5"}
									style={{
										borderBottomLeftRadius: 32,
										borderBottomRightRadius: 32,
										borderTopLeftRadius: 32,
										borderTopRightRadius: 32,
									}}
									variants={{
										BR2UTbsAs: {
											borderBottomLeftRadius: 24,
											borderBottomRightRadius: 24,
											borderTopLeftRadius: 24,
											borderTopRightRadius: 24,
										},
										nU7I1YtGa: {
											borderBottomLeftRadius: 16,
											borderBottomRightRadius: 16,
											borderTopLeftRadius: 16,
											borderTopRightRadius: 16,
										},
									}}
								>
									<ImageWithFX
										__framer__adjustPosition={true}
										__framer__offset={0}
										__framer__parallaxTransformEnabled={true}
										__framer__speed={85}
										__perspectiveFX={false}
										__smartComponentFX={true}
										__targetOpacity={1}
										background={{
											alt: "",
											fit: "fit",
											intrinsicHeight: 1707,
											intrinsicWidth: 2560,
											loading: getLoadingLazyAtYPosition(
												(componentViewport?.y || 0) +
													0 +
													(((componentViewport?.height || 200) - 0 - 3997) / 2 +
														3437 +
														320) +
													0 +
													0 +
													0 +
													-120,
											),
											pixelHeight: 4160,
											pixelWidth: 6240,
											sizes: `calc((${componentViewport?.width || "100vw"} - 64px) * 1.1)`,
											...toResponsiveImage(GVR4L0JmR),
											...{
												positionX: "center",
												positionY: "center",
											},
										}}
										className={"framer-1edit9e"}
										data-framer-name={"Image"}
										layoutDependency={layoutDependency}
										layoutId={"cxpSiW4H0"}
										{...addPropertyOverrides(
											{
												BR2UTbsAs: {
													background: {
														alt: "",
														fit: "fit",
														intrinsicHeight: 1707,
														intrinsicWidth: 2560,
														loading: getLoadingLazyAtYPosition(
															(componentViewport?.y || 0) +
																0 +
																(((componentViewport?.height || 200) -
																	0 -
																	3965) /
																	2 +
																	3437 +
																	320) +
																0 +
																0 +
																0 +
																-120,
														),
														pixelHeight: 4160,
														pixelWidth: 6240,
														sizes: `calc((${componentViewport?.width || "100vw"} - 48px) * 1.1)`,
														...toResponsiveImage(GVR4L0JmR),
														...{
															positionX: "center",
															positionY: "center",
														},
													},
												},
												nU7I1YtGa: {
													__framer__speed: 90,
													background: {
														alt: "",
														fit: "fit",
														intrinsicHeight: 1707,
														intrinsicWidth: 2560,
														loading: getLoadingLazyAtYPosition(
															(componentViewport?.y || 0) +
																0 +
																(((componentViewport?.height || 200) -
																	0 -
																	2350.2) /
																	2 +
																	2022.2 +
																	240) +
																0 +
																0 +
																0 +
																-58,
														),
														pixelHeight: 4160,
														pixelWidth: 6240,
														sizes: `calc((${componentViewport?.width || "100vw"} - 32px) * 1.4)`,
														...toResponsiveImage(GVR4L0JmR),
														...{
															positionX: "center",
															positionY: "center",
														},
													},
												},
											},
											baseVariant,
											gestureVariant,
										)}
									/>
								</motion.div>
							)}
							{visible3 && (
								<motion.div
									className={"framer-2kom3r"}
									data-framer-name={"Image"}
									layoutDependency={layoutDependency}
									layoutId={"fkdYWtGXX"}
									style={{
										borderBottomLeftRadius: 32,
										borderBottomRightRadius: 32,
										borderTopLeftRadius: 32,
										borderTopRightRadius: 32,
									}}
									variants={{
										BR2UTbsAs: {
											borderBottomLeftRadius: 24,
											borderBottomRightRadius: 24,
											borderTopLeftRadius: 24,
											borderTopRightRadius: 24,
										},
										nU7I1YtGa: {
											borderBottomLeftRadius: 16,
											borderBottomRightRadius: 16,
											borderTopLeftRadius: 16,
											borderTopRightRadius: 16,
										},
									}}
								>
									<ImageWithFX
										__framer__adjustPosition={true}
										__framer__offset={0}
										__framer__parallaxTransformEnabled={true}
										__framer__speed={85}
										__perspectiveFX={false}
										__smartComponentFX={true}
										__targetOpacity={1}
										background={{
											alt: "",
											fit: "fit",
											intrinsicHeight: 1707,
											intrinsicWidth: 2560,
											loading: getLoadingLazyAtYPosition(
												(componentViewport?.y || 0) +
													0 +
													(((componentViewport?.height || 200) - 0 - 3997) / 2 +
														3437 +
														320) +
													0 +
													0 +
													-120,
											),
											pixelHeight: 2160,
											pixelWidth: 3840,
											sizes: `calc((${componentViewport?.width || "100vw"} - 64px) * 1.1)`,
											...toResponsiveImage(KL36dHpa5),
											...{
												positionX: "center",
												positionY: "center",
											},
										}}
										className={"framer-19k67ef"}
										data-framer-name={"Image"}
										layoutDependency={layoutDependency}
										layoutId={"Z4Rr2rFW2"}
										{...addPropertyOverrides(
											{
												BR2UTbsAs: {
													background: {
														alt: "",
														fit: "fit",
														intrinsicHeight: 1707,
														intrinsicWidth: 2560,
														loading: getLoadingLazyAtYPosition(
															(componentViewport?.y || 0) +
																0 +
																(((componentViewport?.height || 200) -
																	0 -
																	3965) /
																	2 +
																	3437 +
																	320) +
																0 +
																0 +
																-120,
														),
														pixelHeight: 2160,
														pixelWidth: 3840,
														sizes: `calc((${componentViewport?.width || "100vw"} - 48px) * 1.1)`,
														...toResponsiveImage(KL36dHpa5),
														...{
															positionX: "center",
															positionY: "center",
														},
													},
												},
												nU7I1YtGa: {
													__framer__speed: 90,
													background: {
														alt: "",
														fit: "fit",
														intrinsicHeight: 1707,
														intrinsicWidth: 2560,
														loading: getLoadingLazyAtYPosition(
															(componentViewport?.y || 0) +
																0 +
																(((componentViewport?.height || 200) -
																	0 -
																	2350.2) /
																	2 +
																	2022.2 +
																	240) +
																0 +
																0 +
																-58,
														),
														pixelHeight: 2160,
														pixelWidth: 3840,
														sizes: `calc((${componentViewport?.width || "100vw"} - 32px) * 1.4)`,
														...toResponsiveImage(KL36dHpa5),
														...{
															positionX: "center",
															positionY: "center",
														},
													},
												},
											},
											baseVariant,
											gestureVariant,
										)}
									/>
								</motion.div>
							)}
							<motion.div
								className={"framer-15chpct"}
								data-framer-name={"Images"}
								layoutDependency={layoutDependency}
								layoutId={"ePjdLpJYP"}
							>
								{visible4 && (
									<motion.div
										className={"framer-1d6rjxc"}
										data-framer-name={"Image"}
										layoutDependency={layoutDependency}
										layoutId={"jMQq8iNP1"}
										style={{
											borderBottomLeftRadius: 32,
											borderBottomRightRadius: 32,
											borderTopLeftRadius: 32,
											borderTopRightRadius: 32,
										}}
										variants={{
											BR2UTbsAs: {
												borderBottomLeftRadius: 24,
												borderBottomRightRadius: 24,
												borderTopLeftRadius: 24,
												borderTopRightRadius: 24,
											},
											nU7I1YtGa: {
												borderBottomLeftRadius: 16,
												borderBottomRightRadius: 16,
												borderTopLeftRadius: 16,
												borderTopRightRadius: 16,
											},
										}}
									>
										<ImageWithFX
											__framer__adjustPosition={true}
											__framer__offset={0}
											__framer__parallaxTransformEnabled={true}
											__framer__speed={85}
											__perspectiveFX={false}
											__smartComponentFX={true}
											__targetOpacity={1}
											background={{
												alt: "",
												fit: "fill",
												intrinsicHeight: 1707,
												intrinsicWidth: 2560,
												loading: getLoadingLazyAtYPosition(
													(componentViewport?.y || 0) +
														0 +
														(((componentViewport?.height || 200) - 0 - 3997) /
															2 +
															3437 +
															320) +
														0 +
														0 +
														-400 +
														-120,
												),
												pixelHeight: 5464,
												pixelWidth: 8192,
												sizes: `calc(max((${componentViewport?.width || "100vw"} - 40px) / 0, 1px) * 1.1)`,
												...toResponsiveImage(J_BryPek2),
												...{
													positionX: "center",
													positionY: "center",
												},
											}}
											className={"framer-kpg0p7"}
											data-framer-name={"Image"}
											layoutDependency={layoutDependency}
											layoutId={"Wp4URSijb"}
											{...addPropertyOverrides(
												{
													BR2UTbsAs: {
														background: {
															alt: "",
															fit: "fill",
															intrinsicHeight: 1707,
															intrinsicWidth: 2560,
															loading: getLoadingLazyAtYPosition(
																(componentViewport?.y || 0) +
																	0 +
																	(((componentViewport?.height || 200) -
																		0 -
																		3965) /
																		2 +
																		3437 +
																		320) +
																	0 +
																	0 +
																	-400 +
																	-120,
															),
															pixelHeight: 5464,
															pixelWidth: 8192,
															sizes: `calc(max((${componentViewport?.width || "100vw"} - 24px) / 0, 1px) * 1.1)`,
															...toResponsiveImage(J_BryPek2),
															...{
																positionX: "center",
																positionY: "center",
															},
														},
													},
													nU7I1YtGa: {
														__framer__speed: 90,
														background: {
															alt: "",
															fit: "fit",
															intrinsicHeight: 1707,
															intrinsicWidth: 2560,
															loading: getLoadingLazyAtYPosition(
																(componentViewport?.y || 0) +
																	0 +
																	(((componentViewport?.height || 200) -
																		0 -
																		2350.2) /
																		2 +
																		2022.2 +
																		240) +
																	0 +
																	0 +
																	0 +
																	8 +
																	-58,
															),
															pixelHeight: 5464,
															pixelWidth: 8192,
															sizes: `calc((${componentViewport?.width || "100vw"} - 32px) * 1.4)`,
															...toResponsiveImage(J_BryPek2),
															...{
																positionX: "center",
																positionY: "center",
															},
														},
													},
												},
												baseVariant,
												gestureVariant,
											)}
										/>
									</motion.div>
								)}
								{visible5 && (
									<motion.div
										className={"framer-j45joy"}
										data-framer-name={"Image"}
										layoutDependency={layoutDependency}
										layoutId={"COcx6qIv3"}
										style={{
											borderBottomLeftRadius: 32,
											borderBottomRightRadius: 32,
											borderTopLeftRadius: 32,
											borderTopRightRadius: 32,
										}}
										variants={{
											BR2UTbsAs: {
												borderBottomLeftRadius: 24,
												borderBottomRightRadius: 24,
												borderTopLeftRadius: 24,
												borderTopRightRadius: 24,
											},
											nU7I1YtGa: {
												borderBottomLeftRadius: 16,
												borderBottomRightRadius: 16,
												borderTopLeftRadius: 16,
												borderTopRightRadius: 16,
											},
										}}
									>
										<ImageWithFX
											__framer__adjustPosition={true}
											__framer__offset={0}
											__framer__parallaxTransformEnabled={true}
											__framer__speed={85}
											__perspectiveFX={false}
											__smartComponentFX={true}
											__targetOpacity={1}
											background={{
												alt: "",
												fit: "fill",
												intrinsicHeight: 1707,
												intrinsicWidth: 2560,
												loading: getLoadingLazyAtYPosition(
													(componentViewport?.y || 0) +
														0 +
														(((componentViewport?.height || 200) - 0 - 3997) /
															2 +
															3437 +
															320) +
														0 +
														0 +
														-400 +
														-120,
												),
												pixelHeight: 3882,
												pixelWidth: 5815,
												sizes: `calc(max((${componentViewport?.width || "100vw"} - 40px) / 0, 1px) * 1.1)`,
												...toResponsiveImage(tttpWdpG6),
											}}
											className={"framer-4hks0f"}
											data-framer-name={"Image"}
											layoutDependency={layoutDependency}
											layoutId={"IZOLh1NAp"}
											{...addPropertyOverrides(
												{
													BR2UTbsAs: {
														background: {
															alt: "",
															fit: "fill",
															intrinsicHeight: 1707,
															intrinsicWidth: 2560,
															loading: getLoadingLazyAtYPosition(
																(componentViewport?.y || 0) +
																	0 +
																	(((componentViewport?.height || 200) -
																		0 -
																		3965) /
																		2 +
																		3437 +
																		320) +
																	0 +
																	0 +
																	-400 +
																	-120,
															),
															pixelHeight: 3882,
															pixelWidth: 5815,
															sizes: `calc(max((${componentViewport?.width || "100vw"} - 24px) / 0, 1px) * 1.1)`,
															...toResponsiveImage(tttpWdpG6),
														},
													},
													nU7I1YtGa: {
														__framer__speed: 90,
														background: {
															alt: "",
															fit: "fit",
															intrinsicHeight: 1707,
															intrinsicWidth: 2560,
															loading: getLoadingLazyAtYPosition(
																(componentViewport?.y || 0) +
																	0 +
																	(((componentViewport?.height || 200) -
																		0 -
																		2350.2) /
																		2 +
																		2022.2 +
																		240) +
																	0 +
																	0 +
																	0 +
																	8 +
																	-58,
															),
															pixelHeight: 3882,
															pixelWidth: 5815,
															sizes: `calc((${componentViewport?.width || "100vw"} - 32px) * 1.4)`,
															...toResponsiveImage(tttpWdpG6),
															...{
																positionX: "center",
																positionY: "center",
															},
														},
													},
												},
												baseVariant,
												gestureVariant,
											)}
										/>
									</motion.div>
								)}
							</motion.div>
						</motion.section>
						<motion.section
							className={"framer-1jguw23"}
							data-framer-name={"Bottom"}
							layoutDependency={layoutDependency}
							layoutId={"VTs4NHowt"}
						>
							<motion.section
								className={"framer-kt2vd6"}
								data-framer-name={"Next + Previous"}
								layoutDependency={layoutDependency}
								layoutId={"SNTMr1wB0"}
							>
								{isDisplayed(visible6) && (
									<motion.div
										className={"framer-1pbu6on"}
										data-framer-name={"Prev"}
										layoutDependency={layoutDependency}
										layoutId={"eF2_6_o1r"}
									>
										{visible7 && (
											<ResolveLinks
												links={[
													{
														href: {
															pathVariables: {
																T7gBS1DsS: previousItemId_T7gBS1DsSBI7ZQ0OEo,
															},
															webPageId: "BI7ZQ0OEo",
														},
														implicitPathVariables: void 0,
													},
													{
														href: {
															pathVariables: {
																T7gBS1DsS: previousItemId_T7gBS1DsSBI7ZQ0OEo,
															},
															webPageId: "BI7ZQ0OEo",
														},
														implicitPathVariables: void 0,
													},
													{
														href: {
															pathVariables: {
																T7gBS1DsS: previousItemId_T7gBS1DsSBI7ZQ0OEo,
															},
															webPageId: "BI7ZQ0OEo",
														},
														implicitPathVariables: void 0,
													},
													{
														href: {
															pathVariables: {
																T7gBS1DsS: previousItemId_T7gBS1DsSBI7ZQ0OEo,
															},
															webPageId: "BI7ZQ0OEo",
														},
														implicitPathVariables: void 0,
													},
												]}
											>
												{(resolvedLinks) => (
													<ComponentViewportProvider
														height={96}
														y={
															(componentViewport?.y || 0) +
															0 +
															(((componentViewport?.height || 200) - 0 - 3997) /
																2 +
																3437 +
																384) +
															80 +
															0 +
															0 +
															0 +
															53
														}
														{...addPropertyOverrides(
															{
																BR2UTbsAs: {
																	y:
																		(componentViewport?.y || 0) +
																		0 +
																		(((componentViewport?.height || 200) -
																			0 -
																			3965) /
																			2 +
																			3437 +
																			384) +
																		48 +
																		0 +
																		0 +
																		0 +
																		53,
																},
																nU7I1YtGa: {
																	y:
																		(componentViewport?.y || 0) +
																		0 +
																		(((componentViewport?.height || 200) -
																			0 -
																			2350.2) /
																			2 +
																			2022.2 +
																			288) +
																		40 +
																		0 +
																		0 +
																		16 +
																		0 +
																		53,
																},
															},
															baseVariant,
															gestureVariant,
														)}
													>
														<SmartComponentScopedContainer
															className={"framer-1lgdrny-container"}
															layoutDependency={layoutDependency}
															layoutId={"wp1JME3ga-container"}
															nodeId={"wp1JME3ga"}
															rendersWithMotion={true}
															scopeId={"Oh3EUIZdn"}
														>
															{_jsx(stdin_default, {
																Br5XOxMIq: resolvedLinks[0],
																cnBh8EvXv: 16,
																height: "100%",
																id: "wp1JME3ga",
																layoutId: "wp1JME3ga",
																ScpacHm8i: "Prev",
																variant: "eknfygkCZ",
																width: "100%",
																...addPropertyOverrides(
																	{
																		BR2UTbsAs: {
																			Br5XOxMIq: resolvedLinks[2],
																			cnBh8EvXv: 8,
																			variant: "PCFXTmKxA",
																		},
																		e_UYxB7Zy: {
																			Br5XOxMIq: resolvedLinks[1],
																		},
																		nU7I1YtGa: {
																			Br5XOxMIq: resolvedLinks[3],
																			cnBh8EvXv: 4,
																			variant: "irrzlh0xs",
																		},
																	},
																	baseVariant,
																	gestureVariant,
																),
															})}
														</SmartComponentScopedContainer>
													</ComponentViewportProvider>
												)}
											</ResolveLinks>
										)}
									</motion.div>
								)}
								{isDisplayed(visible8) && (
									<motion.div
										className={"framer-bcq3pg"}
										data-framer-name={"Next"}
										layoutDependency={layoutDependency}
										layoutId={"znhNDbe6u"}
									>
										{visible9 && (
											<ResolveLinks
												links={[
													{
														href: {
															pathVariables: {
																T7gBS1DsS: nextItemId_T7gBS1DsSBI7ZQ0OEo,
															},
															webPageId: "BI7ZQ0OEo",
														},
														implicitPathVariables: void 0,
													},
													{
														href: {
															pathVariables: {
																T7gBS1DsS: nextItemId_T7gBS1DsSBI7ZQ0OEo,
															},
															webPageId: "BI7ZQ0OEo",
														},
														implicitPathVariables: void 0,
													},
													{
														href: {
															pathVariables: {
																T7gBS1DsS: nextItemId_T7gBS1DsSBI7ZQ0OEo,
															},
															webPageId: "BI7ZQ0OEo",
														},
														implicitPathVariables: void 0,
													},
													{
														href: {
															pathVariables: {
																T7gBS1DsS: nextItemId_T7gBS1DsSBI7ZQ0OEo,
															},
															webPageId: "BI7ZQ0OEo",
														},
														implicitPathVariables: void 0,
													},
												]}
											>
												{(resolvedLinks1) => (
													<ComponentViewportProvider
														height={96}
														y={
															(componentViewport?.y || 0) +
															0 +
															(((componentViewport?.height || 200) - 0 - 3997) /
																2 +
																3437 +
																384) +
															80 +
															0 +
															48 +
															0 +
															5
														}
														{...addPropertyOverrides(
															{
																BR2UTbsAs: {
																	y:
																		(componentViewport?.y || 0) +
																		0 +
																		(((componentViewport?.height || 200) -
																			0 -
																			3965) /
																			2 +
																			3437 +
																			384) +
																		48 +
																		0 +
																		48 +
																		0 +
																		5,
																},
																nU7I1YtGa: {
																	y:
																		(componentViewport?.y || 0) +
																		0 +
																		(((componentViewport?.height || 200) -
																			0 -
																			2350.2) /
																			2 +
																			2022.2 +
																			288) +
																		40 +
																		0 +
																		0 +
																		16 +
																		0 +
																		5,
																},
															},
															baseVariant,
															gestureVariant,
														)}
													>
														<SmartComponentScopedContainer
															className={"framer-1n6yi2d-container"}
															layoutDependency={layoutDependency}
															layoutId={"ypBWkyvmj-container"}
															nodeId={"ypBWkyvmj"}
															rendersWithMotion={true}
															scopeId={"Oh3EUIZdn"}
														>
															{_jsx(stdin_default, {
																Br5XOxMIq: resolvedLinks1[0],
																cnBh8EvXv: 16,
																height: "100%",
																id: "ypBWkyvmj",
																layoutId: "ypBWkyvmj",
																ScpacHm8i: "Next",
																variant: "eknfygkCZ",
																width: "100%",
																...addPropertyOverrides(
																	{
																		BR2UTbsAs: {
																			Br5XOxMIq: resolvedLinks1[2],
																			cnBh8EvXv: 8,
																			variant: "PCFXTmKxA",
																		},
																		e_UYxB7Zy: {
																			Br5XOxMIq: resolvedLinks1[1],
																		},
																		nU7I1YtGa: {
																			Br5XOxMIq: resolvedLinks1[3],
																			cnBh8EvXv: 4,
																			variant: "irrzlh0xs",
																		},
																	},
																	baseVariant,
																	gestureVariant,
																),
															})}
														</SmartComponentScopedContainer>
													</ComponentViewportProvider>
												)}
											</ResolveLinks>
										)}
									</motion.div>
								)}
							</motion.section>
						</motion.section>
					</motion.main>
				</Transition>
			</Variants>
		</LayoutGroup>
	);
});
var css4 = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-5EwEW.framer-wyxx0d, .framer-5EwEW .framer-wyxx0d { display: block; }",
	".framer-5EwEW.framer-9ladjt { align-content: center; align-items: center; display: flex; flex-direction: column; flex-wrap: nowrap; gap: 64px; height: min-content; justify-content: center; max-width: 1920px; overflow: hidden; padding: 0px; position: relative; width: 1440px; }",
	".framer-5EwEW .framer-1o3laja { align-content: center; align-items: center; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 48px; height: min-content; justify-content: center; overflow: hidden; padding: 0px 32px 0px 32px; position: relative; width: 100%; }",
	".framer-5EwEW .framer-1kdlw5h { align-content: flex-start; align-items: flex-start; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 12px; height: min-content; justify-content: center; overflow: visible; padding: 0px; position: relative; width: 100%; }",
	".framer-5EwEW .framer-1vojahi { flex: none; height: auto; position: relative; white-space: pre-wrap; width: 100%; word-break: break-word; word-wrap: break-word; }",
	".framer-5EwEW .framer-clst47 { flex: none; height: auto; position: relative; white-space: pre; width: auto; }",
	".framer-5EwEW .framer-1fg0yzc { align-content: center; align-items: center; aspect-ratio: 1.62 / 1; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: var(--framer-aspect-ratio-supported, 849px); justify-content: center; overflow: hidden; padding: 0px; position: relative; width: 100%; will-change: var(--framer-will-change-override, transform); }",
	".framer-5EwEW .framer-9su0hj { flex: none; height: 130%; overflow: hidden; position: relative; width: 110%; will-change: var(--framer-will-change-override, transform); z-index: 1; }",
	".framer-5EwEW .framer-2jwi0c { align-content: flex-start; align-items: flex-start; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; height: min-content; justify-content: space-between; overflow: hidden; padding: 0px 80px 0px 80px; position: relative; width: 100%; }",
	".framer-5EwEW .framer-1t8hj17 { align-content: center; align-items: center; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: center; overflow: hidden; padding: 0px; position: relative; width: 35%; }",
	".framer-5EwEW .framer-113vhs6, .framer-5EwEW .framer-tc6brz, .framer-5EwEW .framer-3u1se4, .framer-5EwEW .framer-vrdnx7 { --framer-text-wrap-override: balance; flex: none; height: auto; position: relative; width: 100%; }",
	".framer-5EwEW .framer-1y2uzlp { align-content: flex-start; align-items: flex-start; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 16px; height: min-content; justify-content: center; overflow: hidden; padding: 0px; position: relative; width: 40%; }",
	".framer-5EwEW .framer-1qbivlm, .framer-5EwEW .framer-9c6ja9, .framer-5EwEW .framer-1qr084g { align-content: flex-start; align-items: flex-start; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 8px; height: min-content; justify-content: center; overflow: hidden; padding: 0px; position: relative; width: 100%; }",
	".framer-5EwEW .framer-102nl4v, .framer-5EwEW .framer-1tdj66x, .framer-5EwEW .framer-128jbnb, .framer-5EwEW .framer-uwv6x9, .framer-5EwEW .framer-hcdcux, .framer-5EwEW .framer-1l6lhhz, .framer-5EwEW .framer-1ihaybd, .framer-5EwEW .framer-14wxakw, .framer-5EwEW .framer-16b0uos { --framer-text-wrap-override: balance; flex: none; height: auto; position: relative; width: auto; }",
	".framer-5EwEW .framer-1ilzg0z, .framer-5EwEW .framer-1r0crxv { align-content: center; align-items: center; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 24px; height: min-content; justify-content: center; overflow: hidden; padding: 0px 32px 0px 32px; position: relative; width: 100%; }",
	".framer-5EwEW .framer-dopl8m, .framer-5EwEW .framer-1wh8mhl { align-content: center; align-items: center; aspect-ratio: 1.62 / 1; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 0px; height: var(--framer-aspect-ratio-supported, 850px); justify-content: center; overflow: hidden; padding: 0px; position: relative; width: 100%; will-change: var(--framer-will-change-override, transform); }",
	".framer-5EwEW .framer-jkx4if, .framer-5EwEW .framer-1dqgui8, .framer-5EwEW .framer-1edit9e, .framer-5EwEW .framer-19k67ef, .framer-5EwEW .framer-kpg0p7, .framer-5EwEW .framer-4hks0f { flex: none; height: 130%; position: relative; width: 110%; }",
	".framer-5EwEW .framer-18z0wdq { align-content: center; align-items: center; aspect-ratio: 1.62 / 1; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 0px; height: var(--framer-aspect-ratio-supported, 849px); justify-content: center; overflow: hidden; padding: 0px; position: relative; width: 100%; will-change: var(--framer-will-change-override, transform); }",
	".framer-5EwEW .framer-k8u014 { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: center; overflow: hidden; padding: 48px 0px 48px 0px; position: relative; width: 100%; }",
	".framer-5EwEW .framer-167t67c-container { flex: 1 0 0px; height: auto; position: relative; width: 1px; }",
	".framer-5EwEW .framer-qgh701 { align-content: flex-start; align-items: flex-start; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 24px; height: min-content; justify-content: center; overflow: hidden; padding: 0px 80px 0px 80px; position: relative; width: 100%; }",
	".framer-5EwEW .framer-1pqswew { flex: none; height: 1px; overflow: hidden; position: relative; width: 100%; }",
	".framer-5EwEW .framer-1dzxp7c { align-content: flex-start; align-items: flex-start; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 64px; height: min-content; justify-content: center; overflow: hidden; padding: 0px; position: relative; width: 100%; }",
	".framer-5EwEW .framer-1tun5, .framer-5EwEW .framer-10uw935, .framer-5EwEW .framer-1d1a38e { align-content: flex-start; align-items: flex-start; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; height: min-content; justify-content: space-between; overflow: hidden; padding: 0px; position: relative; width: 100%; }",
	".framer-5EwEW .framer-11baelz, .framer-5EwEW .framer-2mf8v8, .framer-5EwEW .framer-ylng0r { align-content: flex-start; align-items: flex-start; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 8px; height: min-content; justify-content: center; overflow: hidden; padding: 0px; position: relative; width: 35%; }",
	".framer-5EwEW .framer-1ppad26, .framer-5EwEW .framer-xrtmd0, .framer-5EwEW .framer-kpat3u { align-content: flex-start; align-items: flex-start; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 8px; height: min-content; justify-content: center; overflow: hidden; padding: 0px; position: relative; width: 40%; }",
	".framer-5EwEW .framer-2kom3r { align-content: center; align-items: center; aspect-ratio: 1.62 / 1; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 0px; height: var(--framer-aspect-ratio-supported, 849px); justify-content: center; overflow: hidden; padding: 0px; position: relative; width: 100%; will-change: var(--framer-will-change-override, transform); }",
	".framer-5EwEW .framer-15chpct { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 24px; height: min-content; justify-content: center; overflow: hidden; padding: 0px; position: relative; width: 100%; }",
	".framer-5EwEW .framer-1d6rjxc, .framer-5EwEW .framer-j45joy { align-content: center; align-items: center; aspect-ratio: 0.795 / 1; display: flex; flex: 1 0 0px; flex-direction: row; flex-wrap: nowrap; gap: 0px; height: var(--framer-aspect-ratio-supported, 851px); justify-content: center; overflow: hidden; padding: 0px; position: relative; width: 1px; will-change: var(--framer-will-change-override, transform); }",
	".framer-5EwEW .framer-1jguw23 { align-content: center; align-items: center; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 120px; height: min-content; justify-content: center; overflow: hidden; padding: 80px 32px 0px 32px; position: relative; width: 100%; }",
	".framer-5EwEW .framer-kt2vd6 { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; height: min-content; justify-content: space-between; overflow: hidden; padding: 0px; position: relative; width: 100%; }",
	".framer-5EwEW .framer-1pbu6on, .framer-5EwEW .framer-bcq3pg { align-content: center; align-items: center; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: center; overflow: hidden; padding: 0px; position: relative; width: min-content; }",
	".framer-5EwEW .framer-1lgdrny-container, .framer-5EwEW .framer-1n6yi2d-container { flex: none; height: auto; position: relative; width: auto; }",
	".framer-5EwEW.framer-v-153rblq.framer-9ladjt { width: 1025px; }",
	".framer-5EwEW.framer-v-153rblq .framer-1fg0yzc, .framer-5EwEW.framer-v-153rblq .framer-dopl8m, .framer-5EwEW.framer-v-153rblq .framer-18z0wdq, .framer-5EwEW.framer-v-153rblq .framer-1wh8mhl, .framer-5EwEW.framer-v-153rblq .framer-2kom3r, .framer-5EwEW.framer-v-1vcff77 .framer-1fg0yzc, .framer-5EwEW.framer-v-1vcff77 .framer-dopl8m, .framer-5EwEW.framer-v-1vcff77 .framer-18z0wdq, .framer-5EwEW.framer-v-1vcff77 .framer-1wh8mhl, .framer-5EwEW.framer-v-1vcff77 .framer-2kom3r { height: var(--framer-aspect-ratio-supported, 123px); }",
	".framer-5EwEW.framer-v-153rblq .framer-1d6rjxc, .framer-5EwEW.framer-v-153rblq .framer-j45joy, .framer-5EwEW.framer-v-1vcff77 .framer-1d6rjxc, .framer-5EwEW.framer-v-1vcff77 .framer-j45joy { height: var(--framer-aspect-ratio-supported, 252px); }",
	".framer-5EwEW.framer-v-1vcff77.framer-9ladjt { width: 700px; }",
	".framer-5EwEW.framer-v-1vcff77 .framer-1o3laja, .framer-5EwEW.framer-v-1vcff77 .framer-1ilzg0z, .framer-5EwEW.framer-v-1vcff77 .framer-1r0crxv { padding: 0px 24px 0px 24px; }",
	".framer-5EwEW.framer-v-1vcff77 .framer-2jwi0c, .framer-5EwEW.framer-v-1vcff77 .framer-qgh701 { padding: 0px 48px 0px 48px; }",
	".framer-5EwEW.framer-v-1vcff77 .framer-1t8hj17 { width: 45%; }",
	".framer-5EwEW.framer-v-1vcff77 .framer-1y2uzlp { width: 30%; }",
	".framer-5EwEW.framer-v-1vcff77 .framer-1jguw23 { gap: 100px; padding: 48px 24px 0px 24px; }",
	".framer-5EwEW.framer-v-1n9pnbf.framer-9ladjt { gap: 48px; width: 390px; }",
	".framer-5EwEW.framer-v-1n9pnbf .framer-1o3laja { gap: 32px; padding: 0px 16px 0px 16px; }",
	".framer-5EwEW.framer-v-1n9pnbf .framer-1kdlw5h { gap: 8px; }",
	".framer-5EwEW.framer-v-1n9pnbf .framer-1fg0yzc, .framer-5EwEW.framer-v-1n9pnbf .framer-dopl8m, .framer-5EwEW.framer-v-1n9pnbf .framer-18z0wdq, .framer-5EwEW.framer-v-1n9pnbf .framer-1wh8mhl, .framer-5EwEW.framer-v-1n9pnbf .framer-2kom3r { aspect-ratio: 1.2344827586206897 / 1; height: var(--framer-aspect-ratio-supported, 162px); }",
	".framer-5EwEW.framer-v-1n9pnbf .framer-9su0hj, .framer-5EwEW.framer-v-1n9pnbf .framer-jkx4if, .framer-5EwEW.framer-v-1n9pnbf .framer-1dqgui8, .framer-5EwEW.framer-v-1n9pnbf .framer-1edit9e, .framer-5EwEW.framer-v-1n9pnbf .framer-19k67ef, .framer-5EwEW.framer-v-1n9pnbf .framer-kpg0p7, .framer-5EwEW.framer-v-1n9pnbf .framer-4hks0f { height: 140%; width: 140%; }",
	".framer-5EwEW.framer-v-1n9pnbf .framer-2jwi0c { flex-direction: column; gap: 32px; justify-content: center; padding: 0px 16px 0px 16px; }",
	".framer-5EwEW.framer-v-1n9pnbf .framer-1t8hj17, .framer-5EwEW.framer-v-1n9pnbf .framer-11baelz, .framer-5EwEW.framer-v-1n9pnbf .framer-1ppad26, .framer-5EwEW.framer-v-1n9pnbf .framer-2mf8v8, .framer-5EwEW.framer-v-1n9pnbf .framer-xrtmd0, .framer-5EwEW.framer-v-1n9pnbf .framer-ylng0r, .framer-5EwEW.framer-v-1n9pnbf .framer-kpat3u { width: 100%; }",
	".framer-5EwEW.framer-v-1n9pnbf .framer-1qbivlm, .framer-5EwEW.framer-v-1n9pnbf .framer-9c6ja9, .framer-5EwEW.framer-v-1n9pnbf .framer-1qr084g { gap: 4px; }",
	".framer-5EwEW.framer-v-1n9pnbf .framer-1ilzg0z, .framer-5EwEW.framer-v-1n9pnbf .framer-1r0crxv { gap: 16px; padding: 0px 16px 0px 16px; }",
	".framer-5EwEW.framer-v-1n9pnbf .framer-k8u014 { padding: 0px; }",
	".framer-5EwEW.framer-v-1n9pnbf .framer-qgh701 { padding: 0px 16px 0px 16px; }",
	".framer-5EwEW.framer-v-1n9pnbf .framer-1dzxp7c { gap: 48px; }",
	".framer-5EwEW.framer-v-1n9pnbf .framer-1tun5, .framer-5EwEW.framer-v-1n9pnbf .framer-10uw935, .framer-5EwEW.framer-v-1n9pnbf .framer-1d1a38e { flex-direction: column; gap: 24px; justify-content: center; }",
	".framer-5EwEW.framer-v-1n9pnbf .framer-15chpct { flex-direction: column; gap: 16px; }",
	".framer-5EwEW.framer-v-1n9pnbf .framer-1d6rjxc, .framer-5EwEW.framer-v-1n9pnbf .framer-j45joy { aspect-ratio: 1.2344827586206897 / 1; flex: none; height: var(--framer-aspect-ratio-supported, 162px); width: 100%; }",
	".framer-5EwEW.framer-v-1n9pnbf .framer-1jguw23 { gap: 80px; padding: 40px 16px 0px 16px; }",
	".framer-5EwEW.framer-v-1n9pnbf .framer-kt2vd6 { flex-direction: column; gap: 32px; justify-content: center; }",
	".framer-5EwEW.framer-v-1n9pnbf .framer-1pbu6on { align-content: flex-start; align-items: flex-start; width: 100%; }",
	".framer-5EwEW.framer-v-1n9pnbf .framer-bcq3pg { align-content: flex-end; align-items: flex-end; width: 100%; }",
	...css2,
	...css3,
	...css,
];
var FramerOh3EUIZdn = withCSS(Component, css4, "framer-5EwEW");
var stdin_default3 = FramerOh3EUIZdn;
FramerOh3EUIZdn.displayName = "Edu";
FramerOh3EUIZdn.defaultProps = {
	height: 4100,
	width: 1440,
};
addPropertyControls(FramerOh3EUIZdn, {
	variant: {
		options: ["NYf9d8K13", "e_UYxB7Zy", "BR2UTbsAs", "nU7I1YtGa"],
		optionTitles: ["Desktop", "Laptop", "Tablet", "Phone"],
		title: "Variant",
		type: ControlType.Enum,
	},
	Ma3jyzJmc: {
		defaultValue: "Edbost",
		displayTextArea: false,
		title: "Project Title",
		type: ControlType.String,
	},
	zGrq8FZEk: {
		defaultValue: "Visual Design",
		title: "Category",
		type: ControlType.String,
	},
	l19wRZOJl: {
		title: "Thumbnail",
		type: ControlType.ResponsiveImage,
	},
	Px_uoypCH: {
		defaultValue:
			"High-end VFX and editing tools required steep learning curves and costly subscriptions, putting them out of reach for small studios and solo creators. Edbost identified the need for democratized AI-powered creative tools that simplified advanced workflows.",
		displayTextArea: true,
		title: "Background",
		type: ControlType.String,
	},
	fkZQL44FD: {
		defaultValue: "Alex T.",
		title: "Client",
		type: ControlType.String,
	},
	oRd6CbCVT: {
		defaultValue: "UX Designer",
		title: "Role",
		type: ControlType.String,
	},
	EULy8_Q5_: {
		defaultValue: "2025",
		title: "Year",
		type: ControlType.String,
	},
	C22cdIE2E: {
		title: "Image 1",
		type: ControlType.ResponsiveImage,
	},
	uy_Svr1ZS: {
		title: "Image 2",
		type: ControlType.ResponsiveImage,
	},
	PceLctrYV: {
		defaultValue:
			"Independent filmmakers and digital artists lacked access to affordable, user-friendly AI tools, forcing them to rely on expensive, complex software or outsource effects work\u2014limiting creative control and scalability.",
		displayTextArea: true,
		title: "Challenge",
		type: ControlType.String,
	},
	Z9ngVeKB2: {
		defaultValue:
			"The mission was to build an accessible, cloud-based platform offering AI-driven video editing, green screen removal, and text-to-video generation. By integrating machine learning into an intuitive interface, Edbost aimed to empower creators without technical expertise.",
		displayTextArea: true,
		title: "Objective",
		type: ControlType.String,
	},
	ZQSM5PkKU: {
		defaultValue:
			"Edbost became a game-changer for indie artists, enabling professional-grade results at a fraction of the cost. Its tools have been used in award-winning projects, proving that AI could level the playing field in creative industries.",
		displayTextArea: true,
		title: "Results",
		type: ControlType.String,
	},
	GVR4L0JmR: {
		title: "Image 3",
		type: ControlType.ResponsiveImage,
	},
	KL36dHpa5: {
		title: "Image 4",
		type: ControlType.ResponsiveImage,
	},
	J_BryPek2: {
		title: "Image 5",
		type: ControlType.ResponsiveImage,
	},
	tttpWdpG6: {
		title: "Image 6",
		type: ControlType.ResponsiveImage,
	},
	ZnDf43hgQ: {
		dataIdentifier: "local-module:collection/avuvYYzgc:default",
		defaultValue: "f0LvCUSVK",
		title: "Previous",
		type: ControlType.CollectionReference,
	},
	B01XONVu3: {
		dataIdentifier: "local-module:collection/avuvYYzgc:default",
		title: "Next",
		type: ControlType.CollectionReference,
	},
});
addFonts(
	FramerOh3EUIZdn,
	[
		{
			explicitInter: true,
			fonts: [
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
					url: "https://framerusercontent.com/assets/5vvr9Vy74if2I6bQbJvbw7SY1pQ.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
					url: "https://framerusercontent.com/assets/EOr0mi4hNtlgWNn9if640EZzXCo.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+1F00-1FFF",
					url: "https://framerusercontent.com/assets/Y9k9QrlZAqio88Klkmbd8VoMQc.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+0370-03FF",
					url: "https://framerusercontent.com/assets/OYrD2tBIBPvoJXiIHnLoOXnY9M.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
					url: "https://framerusercontent.com/assets/JeYwfuaPfZHQhEG8U5gtPDZ7WQ.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2070, U+2074-207E, U+2080-208E, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
					url: "https://framerusercontent.com/assets/GrgcKwrN6d3Uz8EwcLHZxwEfC4.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
					url: "https://framerusercontent.com/assets/b6Y37FthZeALduNqHicBT6FutY.woff2",
					weight: "400",
				},
			],
		},
		...TickerFonts,
		...LinkPortfolioFonts,
		...getFontsFromSharedStyle(fonts2),
		...getFontsFromSharedStyle(fonts3),
		...getFontsFromSharedStyle(fonts),
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// virtual:edu
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {
	base: "BR2UTbsAs",
	lg: "e_UYxB7Zy",
	xl: "NYf9d8K13",
};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"cde98c358c3069ef2a8dce28a8c2c8459e940a47824cf38ac0a6e3a305f8bfbb"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default3, {
				...rest,
			})}
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders EduFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"cde98c358c3069ef2a8dce28a8c2c8459e940a47824cf38ac0a6e3a305f8bfbb"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				Component={stdin_default3}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default3);
var edu_default = ComponentWithRoot;
export { edu_default as default };
