// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project cde98c358c3069ef "matt.buzz", do not edit manually */
"use client";

/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
}} Props

 */
import { className, css, fonts } from "./chunks/heading-typography.js";
import { routes } from "./chunks/routes.js";

// virtual:footer
import { Fragment as Fragment3 } from "react";
import { ContextProviders } from "unframer";

// /:https://framerusercontent.com/modules/uNHLcDI4j2UFMpgGrEHE/QknEzDPjtP4aIV0GfVQR/kpLHgrhc3.js
import { jsx as _jsx2, jsxs as _jsxs2 } from "react/jsx-runtime";
import {
	addFonts as addFonts2,
	addPropertyControls as addPropertyControls2,
	ComponentViewportProvider,
	ControlType as ControlType2,
	cx as cx2,
	getFonts,
	SmartComponentScopedContainer,
	useComponentViewport as useComponentViewport2,
	useLocaleInfo as useLocaleInfo2,
	useVariantState as useVariantState2,
	withCSS as withCSS2,
} from "unframer";
import {
	LayoutGroup as LayoutGroup2,
	motion as motion2,
	MotionConfigContext as MotionConfigContext2,
} from "unframer";
import * as React2 from "react";
import { useRef as useRef2 } from "react";

// /:https://framerusercontent.com/modules/eNWMbQJvPEj6lz1ocHUm/5DDhKgdQ9LdDn1dGNKlN/Dd3ylhXi7.js
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import {
	addFonts,
	addPropertyControls,
	ControlType,
	cx,
	getFontsFromSharedStyle,
	Link,
	RichText,
	useComponentViewport,
	useLocaleInfo,
	useVariantState,
	withCSS,
} from "unframer";
import { LayoutGroup, motion, MotionConfigContext } from "unframer";
import * as React from "react";
import { useRef } from "react";
var enabledGestures = {
	gZZq7oJv9: {
		hover: true,
	},
	JpxTAmqKP: {
		hover: true,
	},
};
var cycleOrder = ["JpxTAmqKP", "gZZq7oJv9"];
var serializationHash = "framer-WN3my";
var variantClassNames = {
	gZZq7oJv9: "framer-v-bxccak",
	JpxTAmqKP: "framer-v-g0vkp2",
};
function addPropertyOverrides(overrides, ...variants) {
	const nextOverrides = {};
	variants?.forEach(
		(variant) => variant && Object.assign(nextOverrides, overrides[variant]),
	);
	return nextOverrides;
}
var transition1 = {
	damping: 80,
	delay: 0,
	mass: 1,
	stiffness: 400,
	type: "spring",
};
var Transition = ({ value, children }) => {
	const config = React.useContext(MotionConfigContext);
	const transition = value ?? config.transition;
	const contextValue = React.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext.Provider value={contextValue}>
			{children}
		</MotionConfigContext.Provider>
	);
};
var Variants = motion.create(React.Fragment);
var humanReadableVariantMap = {
	Desktop: "JpxTAmqKP",
	Phone: "gZZq7oJv9",
};
var getProps = ({ height, id, label, link, newTab, width, ...props }) => {
	return {
		...props,
		gaudSAYyV: link ?? props.gaudSAYyV,
		gnxB9JgXH: label ?? props.gnxB9JgXH ?? "hello@adam.com",
		Ke1ihOPDv: newTab ?? props.Ke1ihOPDv,
		variant:
			humanReadableVariantMap[props.variant] ?? props.variant ?? "JpxTAmqKP",
	};
};
var createLayoutDependency = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
	const fallbackRef = useRef(null);
	const refBinding = ref ?? fallbackRef;
	const defaultLayoutId = React.useId();
	const { activeLocale, setLocale } = useLocaleInfo();
	const componentViewport = useComponentViewport();
	const {
		style,
		className: className2,
		layoutId,
		variant,
		gnxB9JgXH,
		gaudSAYyV,
		Ke1ihOPDv,
		...restProps
	} = getProps(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState({
		cycleOrder,
		defaultVariant: "JpxTAmqKP",
		enabledGestures,
		ref: refBinding,
		variant,
		variantClassNames,
	});
	const layoutDependency = createLayoutDependency(props, variants);
	const sharedStyleClassNames = [className];
	const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
	return (
		<LayoutGroup id={layoutId ?? defaultLayoutId}>
			<Variants animate={variants} initial={false}>
				<Transition value={transition1}>
					<Link
						href={gaudSAYyV}
						motionChild={true}
						nodeId={"JpxTAmqKP"}
						openInNewTab={Ke1ihOPDv}
						scopeId={"Dd3ylhXi7"}
						smoothScroll={true}
					>
						<motion.a
							{...restProps}
							{...gestureHandlers}
							className={`${cx(scopingClassNames, "framer-g0vkp2", className2, classNames)} framer-zrjort`}
							data-framer-name={"Desktop"}
							layoutDependency={layoutDependency}
							layoutId={"JpxTAmqKP"}
							ref={refBinding}
							style={{
								...style,
							}}
							{...addPropertyOverrides(
								{
									"gZZq7oJv9-hover": {
										"data-framer-name": void 0,
									},
									"JpxTAmqKP-hover": {
										"data-framer-name": void 0,
									},
									gZZq7oJv9: {
										"data-framer-name": "Phone",
									},
								},
								baseVariant,
								gestureVariant,
							)}
						>
							<motion.div
								className={"framer-1l4i4ql"}
								data-framer-name={"Text"}
								layoutDependency={layoutDependency}
								layoutId={"ef8P68jtD"}
							>
								<RichText
									__fromCanvasComponent={true}
									className={"framer-1bweqmc"}
									data-framer-name={"Text"}
									fonts={["Inter"]}
									layoutDependency={layoutDependency}
									layoutId={"kHTl9YERS"}
									style={{
										skewY: 0,
									}}
									text={gnxB9JgXH}
									variants={{
										"gZZq7oJv9-hover": {
											skewY: 12,
										},
										"JpxTAmqKP-hover": {
											skewY: 12,
										},
									}}
									verticalAlignment={"top"}
									withExternalLayout={true}
								>
									<React.Fragment>
										<motion.p
											className={"framer-styles-preset-wgkidr"}
											data-styles-preset={"NLZz2_xo1"}
										>
											{"hello@adam.com"}
										</motion.p>
									</React.Fragment>
								</RichText>
								<RichText
									__fromCanvasComponent={true}
									className={"framer-7e2nip"}
									data-framer-name={"Text"}
									fonts={["Inter"]}
									layoutDependency={layoutDependency}
									layoutId={"rmJUbBmxC"}
									style={{
										skewY: 12,
									}}
									text={gnxB9JgXH}
									variants={{
										"gZZq7oJv9-hover": {
											skewY: 0,
										},
										"JpxTAmqKP-hover": {
											skewY: 0,
										},
									}}
									verticalAlignment={"top"}
									withExternalLayout={true}
								>
									<React.Fragment>
										<motion.p
											className={"framer-styles-preset-wgkidr"}
											data-styles-preset={"NLZz2_xo1"}
										>
											{"hello@adam.com"}
										</motion.p>
									</React.Fragment>
								</RichText>
							</motion.div>
						</motion.a>
					</Link>
				</Transition>
			</Variants>
		</LayoutGroup>
	);
});
var css2 = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-WN3my.framer-zrjort, .framer-WN3my .framer-zrjort { display: block; }",
	".framer-WN3my.framer-g0vkp2 { align-content: center; align-items: center; cursor: pointer; display: flex; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: center; overflow: hidden; padding: 0px; position: relative; text-decoration: none; width: min-content; }",
	".framer-WN3my .framer-1l4i4ql { align-content: center; align-items: center; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 24px; height: 29px; justify-content: flex-start; overflow: hidden; padding: 0px; position: relative; width: min-content; }",
	".framer-WN3my .framer-1bweqmc, .framer-WN3my .framer-7e2nip { flex: none; height: auto; position: relative; white-space: pre; width: auto; }",
	".framer-WN3my.framer-v-bxccak .framer-1l4i4ql { gap: 14px; height: 22px; }",
	".framer-WN3my.framer-v-g0vkp2.hover .framer-1l4i4ql, .framer-WN3my.framer-v-bxccak.hover .framer-1l4i4ql { justify-content: flex-end; }",
	...css,
];
var FramerDd3ylhXi7 = withCSS(Component, css2, "framer-WN3my");
var stdin_default = FramerDd3ylhXi7;
FramerDd3ylhXi7.displayName = "Link";
FramerDd3ylhXi7.defaultProps = {
	height: 29,
	width: 198.5,
};
addPropertyControls(FramerDd3ylhXi7, {
	variant: {
		options: ["JpxTAmqKP", "gZZq7oJv9"],
		optionTitles: ["Desktop", "Phone"],
		title: "Variant",
		type: ControlType.Enum,
	},
	gnxB9JgXH: {
		defaultValue: "hello@adam.com",
		description: "Write the label of the link",
		displayTextArea: false,
		title: "Label",
		type: ControlType.String,
	},
	gaudSAYyV: {
		description: "Put the URL of the link",
		title: "Link",
		type: ControlType.Link,
	},
	Ke1ihOPDv: {
		defaultValue: false,
		description: "Shall this link open in a new tab?",
		title: "New Tab",
		type: ControlType.Boolean,
	},
});
addFonts(
	FramerDd3ylhXi7,
	[
		{
			explicitInter: true,
			fonts: [
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
					url: "https://framerusercontent.com/assets/5vvr9Vy74if2I6bQbJvbw7SY1pQ.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
					url: "https://framerusercontent.com/assets/EOr0mi4hNtlgWNn9if640EZzXCo.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+1F00-1FFF",
					url: "https://framerusercontent.com/assets/Y9k9QrlZAqio88Klkmbd8VoMQc.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+0370-03FF",
					url: "https://framerusercontent.com/assets/OYrD2tBIBPvoJXiIHnLoOXnY9M.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
					url: "https://framerusercontent.com/assets/JeYwfuaPfZHQhEG8U5gtPDZ7WQ.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2074, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
					url: "https://framerusercontent.com/assets/vQyevYAyHtARFwPqUzQGpnDs.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
					url: "https://framerusercontent.com/assets/b6Y37FthZeALduNqHicBT6FutY.woff2",
					weight: "400",
				},
			],
		},
		...getFontsFromSharedStyle(fonts),
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// /:https://framerusercontent.com/modules/uNHLcDI4j2UFMpgGrEHE/QknEzDPjtP4aIV0GfVQR/kpLHgrhc3.js
var LinkFonts = getFonts(stdin_default);
var cycleOrder2 = ["AFkpjYh_H", "U5yzKEDkE", "EurGjOUOI"];
var serializationHash2 = "framer-NZgWP";
var variantClassNames2 = {
	AFkpjYh_H: "framer-v-gps2w5",
	EurGjOUOI: "framer-v-1g61dpi",
	U5yzKEDkE: "framer-v-ivvdrh",
};
function addPropertyOverrides2(overrides, ...variants) {
	const nextOverrides = {};
	variants?.forEach(
		(variant) => variant && Object.assign(nextOverrides, overrides[variant]),
	);
	return nextOverrides;
}
var transition12 = {
	damping: 80,
	delay: 0,
	mass: 1,
	stiffness: 400,
	type: "spring",
};
var Transition2 = ({ value, children }) => {
	const config = React2.useContext(MotionConfigContext2);
	const transition = value ?? config.transition;
	const contextValue = React2.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext2.Provider value={contextValue}>
			{children}
		</MotionConfigContext2.Provider>
	);
};
var Variants2 = motion2.create(React2.Fragment);
var humanReadableVariantMap2 = {
	Desktop: "AFkpjYh_H",
	Phone: "EurGjOUOI",
	Tablet: "U5yzKEDkE",
};
var getProps2 = ({
	dribbbleLink,
	email,
	emailLink,
	height,
	id,
	instaLink,
	linkedInLink,
	width,
	xLink,
	...props
}) => {
	return {
		...props,
		CuGjdLQSD: xLink ?? props.CuGjdLQSD,
		i1Th9dBCn: dribbbleLink ?? props.i1Th9dBCn,
		ONRhF8PGW: instaLink ?? props.ONRhF8PGW,
		QMzucCgJB: emailLink ?? props.QMzucCgJB,
		sa3JjZyM6: email ?? props.sa3JjZyM6 ?? "hello@adam.com",
		Um3MzkX6l: linkedInLink ?? props.Um3MzkX6l,
		variant:
			humanReadableVariantMap2[props.variant] ?? props.variant ?? "AFkpjYh_H",
	};
};
var createLayoutDependency2 = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component2 = /* @__PURE__ */ React2.forwardRef(function (props, ref) {
	const fallbackRef = useRef2(null);
	const refBinding = ref ?? fallbackRef;
	const defaultLayoutId = React2.useId();
	const { activeLocale, setLocale } = useLocaleInfo2();
	const componentViewport = useComponentViewport2();
	const {
		style,
		className: className2,
		layoutId,
		variant,
		sa3JjZyM6,
		QMzucCgJB,
		ONRhF8PGW,
		Um3MzkX6l,
		i1Th9dBCn,
		CuGjdLQSD,
		...restProps
	} = getProps2(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState2({
		cycleOrder: cycleOrder2,
		defaultVariant: "AFkpjYh_H",
		ref: refBinding,
		variant,
		variantClassNames: variantClassNames2,
	});
	const layoutDependency = createLayoutDependency2(props, variants);
	const sharedStyleClassNames = [];
	const scopingClassNames = cx2(serializationHash2, ...sharedStyleClassNames);
	return (
		<LayoutGroup2 id={layoutId ?? defaultLayoutId}>
			<Variants2 animate={variants} initial={false}>
				<Transition2 value={transition12}>
					<motion2.footer
						{...restProps}
						{...gestureHandlers}
						className={cx2(
							scopingClassNames,
							"framer-gps2w5",
							className2,
							classNames,
						)}
						data-framer-name={"Desktop"}
						layoutDependency={layoutDependency}
						layoutId={"AFkpjYh_H"}
						ref={refBinding}
						style={{
							...style,
						}}
						{...addPropertyOverrides2(
							{
								EurGjOUOI: {
									"data-framer-name": "Phone",
								},
								U5yzKEDkE: {
									"data-framer-name": "Tablet",
								},
							},
							baseVariant,
							gestureVariant,
						)}
					>
						<motion2.div
							className={"framer-2w9pmh"}
							data-framer-name={"Divider"}
							layoutDependency={layoutDependency}
							layoutId={"er_YNqa2D"}
							style={{
								backgroundColor:
									"var(--token-5fde730a-8086-4528-a317-d71b3bf4efde, rgb(255, 255, 255))",
								opacity: 0.16,
							}}
						/>
						<motion2.div
							className={"framer-f3uqbn"}
							data-framer-name={"Content"}
							layoutDependency={layoutDependency}
							layoutId={"AndxGJEod"}
						>
							<motion2.div
								className={"framer-1u6xn8i"}
								data-framer-name={"Left"}
								layoutDependency={layoutDependency}
								layoutId={"Ux9s7hX6O"}
							>
								<ComponentViewportProvider
									height={29}
									y={
										(componentViewport?.y || 0) +
										0 +
										(((componentViewport?.height || 177) - 0 - 177) / 2 +
											1 +
											24) +
										0 +
										0 +
										0
									}
									{...addPropertyOverrides2(
										{
											EurGjOUOI: {
												y:
													(componentViewport?.y || 0) +
													0 +
													(((componentViewport?.height || 181) - 0 - 216) / 2 +
														1 +
														16) +
													0 +
													0 +
													0 +
													0,
											},
											U5yzKEDkE: {
												y:
													(componentViewport?.y || 0) +
													0 +
													(((componentViewport?.height || 149) - 0 - 177) / 2 +
														1 +
														24) +
													0 +
													0 +
													0,
											},
										},
										baseVariant,
										gestureVariant,
									)}
								>
									<SmartComponentScopedContainer
										className={"framer-1c1m9c6-container"}
										layoutDependency={layoutDependency}
										layoutId={"ZF_oUfHYD-container"}
										nodeId={"ZF_oUfHYD"}
										rendersWithMotion={true}
										scopeId={"kpLHgrhc3"}
									>
										{_jsx2(stdin_default, {
											gaudSAYyV: QMzucCgJB,
											gnxB9JgXH: sa3JjZyM6,
											height: "100%",
											id: "ZF_oUfHYD",
											Ke1ihOPDv: true,
											layoutId: "ZF_oUfHYD",
											variant: "JpxTAmqKP",
											width: "100%",
											...addPropertyOverrides2(
												{
													EurGjOUOI: {
														variant: "gZZq7oJv9",
													},
													U5yzKEDkE: {
														variant: "gZZq7oJv9",
													},
												},
												baseVariant,
												gestureVariant,
											),
										})}
									</SmartComponentScopedContainer>
								</ComponentViewportProvider>
							</motion2.div>
							<motion2.div
								className={"framer-14rn0t1"}
								data-framer-name={"Right"}
								layoutDependency={layoutDependency}
								layoutId={"s2PK2KA0f"}
							>
								<ComponentViewportProvider
									height={29}
									y={
										(componentViewport?.y || 0) +
										0 +
										(((componentViewport?.height || 177) - 0 - 177) / 2 +
											1 +
											24) +
										0 +
										0 +
										0
									}
									{...addPropertyOverrides2(
										{
											EurGjOUOI: {
												y:
													(componentViewport?.y || 0) +
													0 +
													(((componentViewport?.height || 181) - 0 - 216) / 2 +
														1 +
														16) +
													0 +
													53 +
													0 +
													0,
											},
											U5yzKEDkE: {
												y:
													(componentViewport?.y || 0) +
													0 +
													(((componentViewport?.height || 149) - 0 - 177) / 2 +
														1 +
														24) +
													0 +
													0 +
													0,
											},
										},
										baseVariant,
										gestureVariant,
									)}
								>
									<SmartComponentScopedContainer
										className={"framer-b0s8qq-container"}
										layoutDependency={layoutDependency}
										layoutId={"XjPKEzVZJ-container"}
										nodeId={"XjPKEzVZJ"}
										rendersWithMotion={true}
										scopeId={"kpLHgrhc3"}
									>
										{_jsx2(stdin_default, {
											gaudSAYyV: ONRhF8PGW,
											gnxB9JgXH: "Instagram",
											height: "100%",
											id: "XjPKEzVZJ",
											Ke1ihOPDv: true,
											layoutId: "XjPKEzVZJ",
											variant: "JpxTAmqKP",
											width: "100%",
											...addPropertyOverrides2(
												{
													EurGjOUOI: {
														variant: "gZZq7oJv9",
													},
													U5yzKEDkE: {
														variant: "gZZq7oJv9",
													},
												},
												baseVariant,
												gestureVariant,
											),
										})}
									</SmartComponentScopedContainer>
								</ComponentViewportProvider>
								<ComponentViewportProvider
									height={29}
									y={
										(componentViewport?.y || 0) +
										0 +
										(((componentViewport?.height || 177) - 0 - 177) / 2 +
											1 +
											24) +
										0 +
										0 +
										41
									}
									{...addPropertyOverrides2(
										{
											EurGjOUOI: {
												y:
													(componentViewport?.y || 0) +
													0 +
													(((componentViewport?.height || 181) - 0 - 216) / 2 +
														1 +
														16) +
													0 +
													53 +
													0 +
													39,
											},
											U5yzKEDkE: {
												y:
													(componentViewport?.y || 0) +
													0 +
													(((componentViewport?.height || 149) - 0 - 177) / 2 +
														1 +
														24) +
													0 +
													0 +
													41,
											},
										},
										baseVariant,
										gestureVariant,
									)}
								>
									<SmartComponentScopedContainer
										className={"framer-8ccc4f-container"}
										layoutDependency={layoutDependency}
										layoutId={"aGLc0d8s7-container"}
										nodeId={"aGLc0d8s7"}
										rendersWithMotion={true}
										scopeId={"kpLHgrhc3"}
									>
										{_jsx2(stdin_default, {
											gaudSAYyV: Um3MzkX6l,
											gnxB9JgXH: "LinkedIn",
											height: "100%",
											id: "aGLc0d8s7",
											Ke1ihOPDv: true,
											layoutId: "aGLc0d8s7",
											variant: "JpxTAmqKP",
											width: "100%",
											...addPropertyOverrides2(
												{
													EurGjOUOI: {
														variant: "gZZq7oJv9",
													},
													U5yzKEDkE: {
														variant: "gZZq7oJv9",
													},
												},
												baseVariant,
												gestureVariant,
											),
										})}
									</SmartComponentScopedContainer>
								</ComponentViewportProvider>
								<ComponentViewportProvider
									height={29}
									y={
										(componentViewport?.y || 0) +
										0 +
										(((componentViewport?.height || 177) - 0 - 177) / 2 +
											1 +
											24) +
										0 +
										0 +
										82
									}
									{...addPropertyOverrides2(
										{
											EurGjOUOI: {
												y:
													(componentViewport?.y || 0) +
													0 +
													(((componentViewport?.height || 181) - 0 - 216) / 2 +
														1 +
														16) +
													0 +
													53 +
													0 +
													78,
											},
											U5yzKEDkE: {
												y:
													(componentViewport?.y || 0) +
													0 +
													(((componentViewport?.height || 149) - 0 - 177) / 2 +
														1 +
														24) +
													0 +
													0 +
													82,
											},
										},
										baseVariant,
										gestureVariant,
									)}
								>
									<SmartComponentScopedContainer
										className={"framer-1n7ikb1-container"}
										layoutDependency={layoutDependency}
										layoutId={"Ua5NTHAYr-container"}
										nodeId={"Ua5NTHAYr"}
										rendersWithMotion={true}
										scopeId={"kpLHgrhc3"}
									>
										{_jsx2(stdin_default, {
											gaudSAYyV: i1Th9dBCn,
											gnxB9JgXH: "Dribbble",
											height: "100%",
											id: "Ua5NTHAYr",
											Ke1ihOPDv: true,
											layoutId: "Ua5NTHAYr",
											variant: "JpxTAmqKP",
											width: "100%",
											...addPropertyOverrides2(
												{
													EurGjOUOI: {
														variant: "gZZq7oJv9",
													},
													U5yzKEDkE: {
														variant: "gZZq7oJv9",
													},
												},
												baseVariant,
												gestureVariant,
											),
										})}
									</SmartComponentScopedContainer>
								</ComponentViewportProvider>
								<ComponentViewportProvider
									height={29}
									y={
										(componentViewport?.y || 0) +
										0 +
										(((componentViewport?.height || 177) - 0 - 177) / 2 +
											1 +
											24) +
										0 +
										0 +
										123
									}
									{...addPropertyOverrides2(
										{
											EurGjOUOI: {
												y:
													(componentViewport?.y || 0) +
													0 +
													(((componentViewport?.height || 181) - 0 - 216) / 2 +
														1 +
														16) +
													0 +
													53 +
													0 +
													117,
											},
											U5yzKEDkE: {
												y:
													(componentViewport?.y || 0) +
													0 +
													(((componentViewport?.height || 149) - 0 - 177) / 2 +
														1 +
														24) +
													0 +
													0 +
													123,
											},
										},
										baseVariant,
										gestureVariant,
									)}
								>
									<SmartComponentScopedContainer
										className={"framer-1rmy39l-container"}
										layoutDependency={layoutDependency}
										layoutId={"GZ9iIEKbh-container"}
										nodeId={"GZ9iIEKbh"}
										rendersWithMotion={true}
										scopeId={"kpLHgrhc3"}
									>
										{_jsx2(stdin_default, {
											gaudSAYyV: CuGjdLQSD,
											gnxB9JgXH: "Twitter (X)",
											height: "100%",
											id: "GZ9iIEKbh",
											Ke1ihOPDv: true,
											layoutId: "GZ9iIEKbh",
											variant: "JpxTAmqKP",
											width: "100%",
											...addPropertyOverrides2(
												{
													EurGjOUOI: {
														variant: "gZZq7oJv9",
													},
													U5yzKEDkE: {
														variant: "gZZq7oJv9",
													},
												},
												baseVariant,
												gestureVariant,
											),
										})}
									</SmartComponentScopedContainer>
								</ComponentViewportProvider>
							</motion2.div>
						</motion2.div>
					</motion2.footer>
				</Transition2>
			</Variants2>
		</LayoutGroup2>
	);
});
var css3 = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-NZgWP.framer-fl5quq, .framer-NZgWP .framer-fl5quq { display: block; }",
	".framer-NZgWP.framer-gps2w5 { align-content: center; align-items: center; display: flex; flex-direction: column; flex-wrap: nowrap; gap: 24px; height: min-content; justify-content: center; overflow: hidden; padding: 0px; position: relative; width: 1200px; }",
	".framer-NZgWP .framer-2w9pmh { flex: none; height: 1px; overflow: hidden; position: relative; width: 100%; }",
	".framer-NZgWP .framer-f3uqbn { align-content: flex-start; align-items: flex-start; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 32px; height: min-content; justify-content: center; overflow: hidden; padding: 0px; position: relative; width: 100%; }",
	".framer-NZgWP .framer-1u6xn8i { align-content: flex-start; align-items: flex-start; display: flex; flex: 1 0 0px; flex-direction: column; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: center; overflow: hidden; padding: 0px; position: relative; width: 1px; }",
	".framer-NZgWP .framer-1c1m9c6-container, .framer-NZgWP .framer-b0s8qq-container, .framer-NZgWP .framer-8ccc4f-container, .framer-NZgWP .framer-1n7ikb1-container, .framer-NZgWP .framer-1rmy39l-container { flex: none; height: auto; position: relative; width: auto; }",
	".framer-NZgWP .framer-14rn0t1 { align-content: flex-start; align-items: flex-start; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 12px; height: min-content; justify-content: center; overflow: hidden; padding: 0px; position: relative; width: 50%; }",
	".framer-NZgWP.framer-v-ivvdrh.framer-gps2w5 { width: 700px; }",
	".framer-NZgWP.framer-v-1g61dpi.framer-gps2w5 { gap: 16px; width: 390px; }",
	".framer-NZgWP.framer-v-1g61dpi .framer-f3uqbn { flex-direction: column; gap: 24px; }",
	".framer-NZgWP.framer-v-1g61dpi .framer-1u6xn8i { flex: none; width: 100%; }",
	".framer-NZgWP.framer-v-1g61dpi .framer-14rn0t1 { gap: 10px; }",
];
var FramerkpLHgrhc3 = withCSS2(Component2, css3, "framer-NZgWP");
var stdin_default2 = FramerkpLHgrhc3;
FramerkpLHgrhc3.displayName = "Footer";
FramerkpLHgrhc3.defaultProps = {
	height: 177,
	width: 1200,
};
addPropertyControls2(FramerkpLHgrhc3, {
	variant: {
		options: ["AFkpjYh_H", "U5yzKEDkE", "EurGjOUOI"],
		optionTitles: ["Desktop", "Tablet", "Phone"],
		title: "Variant",
		type: ControlType2.Enum,
	},
	sa3JjZyM6: {
		defaultValue: "hello@adam.com",
		description: "Write your email address here",
		displayTextArea: false,
		title: "Email",
		type: ControlType2.String,
	},
	QMzucCgJB: {
		description:
			'Put the email link here (start with "mailto:" then your email)',
		title: "Email Link",
		type: ControlType2.Link,
	},
	ONRhF8PGW: {
		description: "Put the link here",
		title: "Insta Link",
		type: ControlType2.Link,
	},
	Um3MzkX6l: {
		description: "Put the link here",
		title: "LinkedIn Link",
		type: ControlType2.Link,
	},
	i1Th9dBCn: {
		description: "Put the link here",
		title: "Dribbble Link",
		type: ControlType2.Link,
	},
	CuGjdLQSD: {
		description: "Put the link here",
		title: "X Link",
		type: ControlType2.Link,
	},
});
addFonts2(
	FramerkpLHgrhc3,
	[
		{
			explicitInter: true,
			fonts: [],
		},
		...LinkFonts,
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// virtual:footer
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {
	base: "EurGjOUOI",
	xl: "AFkpjYh_H",
};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"cde98c358c3069ef2a8dce28a8c2c8459e940a47824cf38ac0a6e3a305f8bfbb"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default2, {
				...rest,
			})}
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders FooterFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"cde98c358c3069ef2a8dce28a8c2c8459e940a47824cf38ac0a6e3a305f8bfbb"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				Component={stdin_default2}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default2);
var footer_default = ComponentWithRoot;
export { footer_default as default };
