// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project cde98c358c3069ef "matt.buzz", do not edit manually */
"use client";

/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
}} Props

 */
import { stdin_default as stdin_default2 } from "./chunks/chunk-CB5YAPNW.js";
import "./chunks/chunk-MGC5HSAG.js";
import "./chunks/chunk-JNGIXIAD.js";
import {
	className,
	css,
	fonts,
	stdin_default,
} from "./chunks/chunk-EFMHCGGP.js";
import "./chunks/chunk-TEOP6HVR.js";
import "./chunks/chunk-INOGGZPE.js";
import "./chunks/chunk-ERT25UFQ.js";
import "./chunks/chunk-DUXOTEEB.js";
import "./chunks/chunk-V2U57ZQI.js";
import { routes } from "./chunks/chunk-54YFTX6O.js";

// virtual:main
import { Fragment as Fragment2 } from "react";
import { ContextProviders } from "unframer";

// /:https://framerusercontent.com/modules/LHg58jGJnKavpGM0hlqy/2CqIrHQvDUmwBQrWYHnl/paXme5D_B.js
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import {
	addFonts,
	addPropertyControls,
	ComponentViewportProvider,
	ControlType,
	cx,
	getFonts,
	getFontsFromSharedStyle,
	RichText,
	SmartComponentScopedContainer,
	useComponentViewport,
	useLocaleInfo,
	useVariantState,
	withCSS,
} from "unframer";
import { LayoutGroup, motion, MotionConfigContext } from "unframer";
import * as React from "react";
import { useRef } from "react";
var NavFonts = getFonts(stdin_default2);
var HeaderFonts = getFonts(stdin_default);
var cycleOrder = ["eDsVreBLY", "xizfm9lN8", "v813QapNw", "kFvLPda15"];
var serializationHash = "framer-71xho";
var variantClassNames = {
	eDsVreBLY: "framer-v-k6grlf",
	kFvLPda15: "framer-v-1dyr4d3",
	v813QapNw: "framer-v-wk99yq",
	xizfm9lN8: "framer-v-8jtlao",
};
function addPropertyOverrides(overrides, ...variants) {
	const nextOverrides = {};
	variants?.forEach(
		(variant) => variant && Object.assign(nextOverrides, overrides[variant]),
	);
	return nextOverrides;
}
var transition1 = {
	bounce: 0.2,
	delay: 0,
	duration: 0.4,
	type: "spring",
};
var transformTemplate1 = (_, t) => `translateX(-50%) ${t}`;
var animation = {
	opacity: 1e-3,
	rotate: 0,
	scale: 1,
	skewX: 0,
	skewY: 2,
	x: 0,
	y: 20,
};
var transition2 = {
	damping: 80,
	delay: 0.02,
	mass: 1,
	stiffness: 400,
	type: "spring",
};
var textEffect = {
	effect: animation,
	repeat: false,
	startDelay: 0.25,
	tokenization: "character",
	transition: transition2,
	trigger: "onMount",
	type: "appear",
};
var Transition = ({ value, children }) => {
	const config = React.useContext(MotionConfigContext);
	const transition = value ?? config.transition;
	const contextValue = React.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext.Provider value={contextValue}>
			{children}
		</MotionConfigContext.Provider>
	);
};
var Variants = motion.create(React.Fragment);
var humanReadableVariantMap = {
	Desktop: "eDsVreBLY",
	Laptop: "xizfm9lN8",
	Phone: "kFvLPda15",
	Tablet: "v813QapNw",
};
var getProps = ({ height, id, width, ...props }) => {
	return {
		...props,
		variant:
			humanReadableVariantMap[props.variant] ?? props.variant ?? "eDsVreBLY",
	};
};
var createLayoutDependency = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
	const fallbackRef = useRef(null);
	const refBinding = ref ?? fallbackRef;
	const defaultLayoutId = React.useId();
	const { activeLocale, setLocale } = useLocaleInfo();
	const componentViewport = useComponentViewport();
	const {
		style,
		className: className2,
		layoutId,
		variant,
		...restProps
	} = getProps(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState({
		cycleOrder,
		defaultVariant: "eDsVreBLY",
		ref: refBinding,
		variant,
		variantClassNames,
	});
	const layoutDependency = createLayoutDependency(props, variants);
	const sharedStyleClassNames = [className];
	const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
	const isDisplayed = () => {
		if (baseVariant === "kFvLPda15") return true;
		return false;
	};
	return (
		<LayoutGroup id={layoutId ?? defaultLayoutId}>
			<Variants animate={variants} initial={false}>
				<Transition value={transition1}>
					<motion.main
						{...restProps}
						{...gestureHandlers}
						className={cx(
							scopingClassNames,
							"framer-k6grlf",
							className2,
							classNames,
						)}
						data-framer-name={"Desktop"}
						layoutDependency={layoutDependency}
						layoutId={"eDsVreBLY"}
						ref={refBinding}
						style={{
							...style,
						}}
						{...addPropertyOverrides(
							{
								kFvLPda15: {
									"data-framer-name": "Phone",
								},
								v813QapNw: {
									"data-framer-name": "Tablet",
								},
								xizfm9lN8: {
									"data-framer-name": "Laptop",
								},
							},
							baseVariant,
							gestureVariant,
						)}
					>
						<ComponentViewportProvider
							height={76}
							width={componentViewport?.width || "100vw"}
							y={(componentViewport?.y || 0) + 0 + 0}
							{...addPropertyOverrides(
								{
									kFvLPda15: {
										y: (componentViewport?.y || 0) + 0,
									},
								},
								baseVariant,
								gestureVariant,
							)}
						>
							<SmartComponentScopedContainer
								className={"framer-1qwpwn6-container"}
								layoutDependency={layoutDependency}
								layoutId={"tSnat81tx-container"}
								nodeId={"tSnat81tx"}
								rendersWithMotion={true}
								scopeId={"paXme5D_B"}
							>
								{_jsx(stdin_default2, {
									cAtzncPer: "Matt Akins",
									height: "100%",
									id: "tSnat81tx",
									layoutId: "tSnat81tx",
									MjfGjNDud: "Meta Ads, Ecommerce, & Marketing Leader",
									NFDjggJY2: false,
									style: {
										width: "100%",
									},
									variant: "RSqCSoNz4",
									width: "100%",
									...addPropertyOverrides(
										{
											kFvLPda15: {
												variant: "NktlPJpSy",
											},
											v813QapNw: {
												variant: "nrfrLHug9",
											},
										},
										baseVariant,
										gestureVariant,
									),
								})}
							</SmartComponentScopedContainer>
						</ComponentViewportProvider>
						{isDisplayed() && (
							<motion.div
								className={"framer-x3nxqr"}
								data-framer-name={"Title"}
								layoutDependency={layoutDependency}
								layoutId={"qjIrzsRLR"}
							>
								<RichText
									__fromCanvasComponent={true}
									className={"framer-ttdtt7"}
									data-framer-name={"Name"}
									effect={textEffect}
									fonts={["Inter"]}
									layoutDependency={layoutDependency}
									layoutId={"lQwOhjojD"}
									style={{
										"--framer-link-text-color": "rgb(0, 153, 255)",
										"--framer-link-text-decoration": "underline",
									}}
									transformTemplate={transformTemplate1}
									verticalAlignment={"top"}
									withExternalLayout={true}
								>
									<React.Fragment>
										<motion.h1
											className={"framer-styles-preset-kavgul"}
											data-styles-preset={"UsLKbKwka"}
											style={{
												"--framer-text-alignment": "center",
											}}
										>
											{"Nolan Carter"}
										</motion.h1>
									</React.Fragment>
								</RichText>
							</motion.div>
						)}
						<ComponentViewportProvider
							height={
								Math.max(0, ((componentViewport?.height || 900) - 0 - 92) / 1) *
								1
							}
							width={componentViewport?.width || "100vw"}
							y={(componentViewport?.y || 0) + 0 + 92}
							{...addPropertyOverrides(
								{
									kFvLPda15: {
										height: 821,
										y: (componentViewport?.y || 0) + 0 + 0,
									},
									v813QapNw: {
										height:
											Math.max(
												0,
												((componentViewport?.height || 800) - 0 - 92) / 1,
											) * 1,
									},
								},
								baseVariant,
								gestureVariant,
							)}
						>
							<SmartComponentScopedContainer
								className={"framer-1300c66-container"}
								layoutDependency={layoutDependency}
								layoutId={"TuX3h53if-container"}
								nodeId={"TuX3h53if"}
								rendersWithMotion={true}
								scopeId={"paXme5D_B"}
							>
								{_jsx(stdin_default, {
									height: "100%",
									id: "TuX3h53if",
									igxWhXtvE: "Matt Akins",
									layoutId: "TuX3h53if",
									lNFPUHIlO: "32px",
									style: {
										height: "100%",
										width: "100%",
									},
									variant: "M6uxoYlpQ",
									wEsuC2TJ_: "100px 0px 0px 0px",
									width: "100%",
									xkZqPjDGX: "ZPWoiskeZ",
									zS6lIL7vu:
										"https://drive.google.com/file/d/167um-hT0g-Xc2ClPDNb0z40feV9LT7e2/view?usp=drive_link",
									...addPropertyOverrides(
										{
											kFvLPda15: {
												lNFPUHIlO: "24px",
												style: {
													width: "100%",
												},
												variant: "F4efXvL8k",
												wEsuC2TJ_: "120px 0px 16px 0px",
											},
											v813QapNw: {
												variant: "RzLCXAmZS",
												wEsuC2TJ_: "60px 0px 0px 0px",
											},
											xizfm9lN8: {
												wEsuC2TJ_: "80px 0px 0px 0px",
											},
										},
										baseVariant,
										gestureVariant,
									),
								})}
							</SmartComponentScopedContainer>
						</ComponentViewportProvider>
					</motion.main>
				</Transition>
			</Variants>
		</LayoutGroup>
	);
});
var css2 = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-71xho.framer-1y6oh9h, .framer-71xho .framer-1y6oh9h { display: block; }",
	".framer-71xho.framer-k6grlf { align-content: center; align-items: center; display: flex; flex-direction: column; flex-wrap: nowrap; gap: 16px; height: 900px; justify-content: flex-start; max-width: 1920px; min-height: 800px; overflow: hidden; padding: 0px; position: relative; width: 1440px; }",
	".framer-71xho .framer-1qwpwn6-container { flex: none; height: auto; mix-blend-mode: difference; position: relative; width: 100%; z-index: 4; }",
	".framer-71xho .framer-x3nxqr { align-content: center; align-items: center; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 24px; height: min-content; justify-content: center; left: 16px; min-height: 60px; overflow: visible; padding: 0px; position: absolute; right: 16px; top: 90px; z-index: 1; }",
	".framer-71xho .framer-ttdtt7 { flex: none; height: auto; left: 50%; position: absolute; top: 0px; white-space: pre-wrap; width: 100%; word-break: break-word; word-wrap: break-word; z-index: 1; }",
	".framer-71xho .framer-1300c66-container { flex: 1 0 0px; height: 1px; position: relative; width: 100%; z-index: 2; }",
	".framer-71xho.framer-v-8jtlao.framer-k6grlf { width: 1025px; }",
	".framer-71xho.framer-v-wk99yq.framer-k6grlf { height: 800px; width: 700px; }",
	".framer-71xho.framer-v-1dyr4d3.framer-k6grlf { gap: 12px; height: 844px; width: 390px; }",
	".framer-71xho.framer-v-1dyr4d3 .framer-1qwpwn6-container { left: 0px; order: 0; position: absolute; right: 0px; top: 0px; width: unset; }",
	".framer-71xho.framer-v-1dyr4d3 .framer-x3nxqr { order: 1; }",
	".framer-71xho.framer-v-1dyr4d3 .framer-1300c66-container { flex: none; height: auto; order: 2; }",
	...css,
];
var FramerpaXme5D_B = withCSS(Component, css2, "framer-71xho");
var stdin_default3 = FramerpaXme5D_B;
FramerpaXme5D_B.displayName = "Main";
FramerpaXme5D_B.defaultProps = {
	height: 900,
	width: 1440,
};
addPropertyControls(FramerpaXme5D_B, {
	variant: {
		options: ["eDsVreBLY", "xizfm9lN8", "v813QapNw", "kFvLPda15"],
		optionTitles: ["Desktop", "Laptop", "Tablet", "Phone"],
		title: "Variant",
		type: ControlType.Enum,
	},
});
addFonts(
	FramerpaXme5D_B,
	[
		{
			explicitInter: true,
			fonts: [
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
					url: "https://framerusercontent.com/assets/5vvr9Vy74if2I6bQbJvbw7SY1pQ.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
					url: "https://framerusercontent.com/assets/EOr0mi4hNtlgWNn9if640EZzXCo.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+1F00-1FFF",
					url: "https://framerusercontent.com/assets/Y9k9QrlZAqio88Klkmbd8VoMQc.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+0370-03FF",
					url: "https://framerusercontent.com/assets/OYrD2tBIBPvoJXiIHnLoOXnY9M.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
					url: "https://framerusercontent.com/assets/JeYwfuaPfZHQhEG8U5gtPDZ7WQ.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2070, U+2074-207E, U+2080-208E, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
					url: "https://framerusercontent.com/assets/GrgcKwrN6d3Uz8EwcLHZxwEfC4.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
					url: "https://framerusercontent.com/assets/b6Y37FthZeALduNqHicBT6FutY.woff2",
					weight: "400",
				},
			],
		},
		...NavFonts,
		...HeaderFonts,
		...getFontsFromSharedStyle(fonts),
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// virtual:main
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {
	base: "kFvLPda15",
	lg: "xizfm9lN8",
	xl: "eDsVreBLY",
};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"cde98c358c3069ef2a8dce28a8c2c8459e940a47824cf38ac0a6e3a305f8bfbb"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default3, {
				...rest,
			})}
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders MainFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"cde98c358c3069ef2a8dce28a8c2c8459e940a47824cf38ac0a6e3a305f8bfbb"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				Component={stdin_default3}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default3);
var main_default = ComponentWithRoot;
export { main_default as default };
