// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project cde98c358c3069ef "matt.buzz", do not edit manually */
"use client";

/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
}} Props

 */
import { Ticker } from "./chunks/chunk-DUXOTEEB.js";
import { routes } from "./chunks/chunk-54YFTX6O.js";

// virtual:stack-phone
import { Fragment as Fragment2 } from "react";
import { ContextProviders } from "unframer";

// /:https://framerusercontent.com/modules/2eL2iB19ldF1vgf3trfF/llsysmTZaMBJAmAZAxSy/LzLEJm3wA.js
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import {
	addFonts,
	addPropertyControls,
	ComponentViewportProvider,
	ControlType,
	cx,
	getFonts,
	Image,
	SmartComponentScopedContainer,
	useComponentViewport,
	useLocaleInfo,
	useVariantState,
	withCSS,
} from "unframer";
import { LayoutGroup, motion, MotionConfigContext } from "unframer";
import * as React from "react";
import { useRef } from "react";
var TickerFonts = getFonts(Ticker);
var serializationHash = "framer-GpMko";
var variantClassNames = {
	kbm8vl_uJ: "framer-v-otnia9",
};
var transition1 = {
	damping: 60,
	delay: 0,
	mass: 1,
	stiffness: 500,
	type: "spring",
};
var Transition = ({ value, children }) => {
	const config = React.useContext(MotionConfigContext);
	const transition = value ?? config.transition;
	const contextValue = React.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext.Provider value={contextValue}>
			{children}
		</MotionConfigContext.Provider>
	);
};
var Variants = motion.create(React.Fragment);
var getProps = ({
	arc,
	chatGPT,
	cleanshotX,
	eagle,
	figma,
	framer,
	height,
	id,
	lemonSqueezy,
	notion,
	screenStudio,
	slack,
	todoist,
	width,
	...props
}) => {
	return {
		...props,
		bpy2eO3qs: screenStudio ?? props.bpy2eO3qs ?? true,
		GnCjBQvOz: cleanshotX ?? props.GnCjBQvOz ?? true,
		HkaaGvVyC: slack ?? props.HkaaGvVyC ?? true,
		jB8tXJpTC: notion ?? props.jB8tXJpTC ?? true,
		lPo95_jsk: framer ?? props.lPo95_jsk ?? true,
		m1j5G2jz5: todoist ?? props.m1j5G2jz5 ?? true,
		NNT__C6zQ: figma ?? props.NNT__C6zQ ?? true,
		oQbrY7Sbe: eagle ?? props.oQbrY7Sbe ?? true,
		OYcWLqnA_: arc ?? props.OYcWLqnA_ ?? true,
		SUA4ENaky: lemonSqueezy ?? props.SUA4ENaky ?? true,
		uXV2ahTre: chatGPT ?? props.uXV2ahTre ?? true,
	};
};
var createLayoutDependency = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
	const fallbackRef = useRef(null);
	const refBinding = ref ?? fallbackRef;
	const defaultLayoutId = React.useId();
	const { activeLocale, setLocale } = useLocaleInfo();
	const componentViewport = useComponentViewport();
	const {
		style,
		className,
		layoutId,
		variant,
		NNT__C6zQ,
		lPo95_jsk,
		jB8tXJpTC,
		m1j5G2jz5,
		OYcWLqnA_,
		HkaaGvVyC,
		uXV2ahTre,
		GnCjBQvOz,
		SUA4ENaky,
		oQbrY7Sbe,
		bpy2eO3qs,
		...restProps
	} = getProps(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState({
		defaultVariant: "kbm8vl_uJ",
		ref: refBinding,
		variant,
		variantClassNames,
	});
	const layoutDependency = createLayoutDependency(props, variants);
	const sharedStyleClassNames = [];
	const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
	return (
		<LayoutGroup id={layoutId ?? defaultLayoutId}>
			<Variants animate={variants} initial={false}>
				<Transition value={transition1}>
					<motion.div
						{...restProps}
						{...gestureHandlers}
						className={cx(
							scopingClassNames,
							"framer-otnia9",
							className,
							classNames,
						)}
						data-framer-name={"Default"}
						layoutDependency={layoutDependency}
						layoutId={"kbm8vl_uJ"}
						ref={refBinding}
						style={{
							...style,
						}}
					>
						<ComponentViewportProvider>
							<SmartComponentScopedContainer
								className={"framer-189d1n4-container"}
								data-framer-name={"Ticker"}
								isAuthoredByUser={true}
								isModuleExternal={true}
								layoutDependency={layoutDependency}
								layoutId={"PAy_lMylN-container"}
								name={"Ticker"}
								nodeId={"PAy_lMylN"}
								rendersWithMotion={true}
								scopeId={"LzLEJm3wA"}
							>
								<Ticker
									alignment={"center"}
									direction={"left"}
									fadeOptions={{
										fadeAlpha: 0,
										fadeContent: true,
										fadeInset: 0,
										fadeWidth: 25,
										overflow: false,
									}}
									gap={8}
									height={"100%"}
									hoverFactor={0.5}
									id={"PAy_lMylN"}
									layoutId={"PAy_lMylN"}
									name={"Ticker"}
									padding={0}
									paddingBottom={0}
									paddingLeft={0}
									paddingPerSide={false}
									paddingRight={0}
									paddingTop={0}
									sizingOptions={{
										heightType: true,
										widthType: true,
									}}
									slots={[
										NNT__C6zQ && (
											<motion.div
												className={"framer-1n6plnc"}
												data-framer-name={"Figma"}
												layoutDependency={layoutDependency}
												layoutId={"DZaHGQz6Z"}
												style={{
													borderBottomLeftRadius: 12,
													borderBottomRightRadius: 12,
													borderTopLeftRadius: 12,
													borderTopRightRadius: 12,
												}}
											>
												<Image
													background={{
														alt: "Figma logo",
														fit: "fit",
														intrinsicHeight: 500,
														intrinsicWidth: 334,
														pixelHeight: 500,
														pixelWidth: 334,
														positionX: "center",
														positionY: "center",
														src: "https://framerusercontent.com/images/YSG9Il0233T2Woq4Fpetvt6FxGA.webp",
													}}
													className={"framer-17stpwo"}
													data-framer-name={"Logo"}
													layoutDependency={layoutDependency}
													layoutId={"Fjs07myoD"}
												/>
												<motion.div
													className={"framer-1cd17wh"}
													data-framer-name={"BG"}
													layoutDependency={layoutDependency}
													layoutId={"gXXex9jvc"}
													style={{
														backgroundColor:
															"var(--token-5fde730a-8086-4528-a317-d71b3bf4efde, rgb(0, 0, 0))",
														opacity: 0.06,
													}}
												/>
											</motion.div>
										),
										lPo95_jsk && (
											<motion.div
												className={"framer-1bynfb1"}
												data-framer-name={"Framer"}
												layoutDependency={layoutDependency}
												layoutId={"CiqFiUHJL"}
												style={{
													borderBottomLeftRadius: 12,
													borderBottomRightRadius: 12,
													borderTopLeftRadius: 12,
													borderTopRightRadius: 12,
												}}
											>
												<Image
													background={{
														alt: "Figma logo",
														fit: "fit",
														intrinsicHeight: 500,
														intrinsicWidth: 334,
														pixelHeight: 500,
														pixelWidth: 340,
														positionX: "center",
														positionY: "center",
														src: "https://framerusercontent.com/images/0j5gYeoRsZG8PJ9hniVzHMcaYo.webp",
													}}
													className={"framer-bnmo96"}
													data-framer-name={"Logo"}
													layoutDependency={layoutDependency}
													layoutId={"KdFlMHoLr"}
												/>
												<motion.div
													className={"framer-n29enr"}
													data-framer-name={"BG"}
													layoutDependency={layoutDependency}
													layoutId={"Z5JcQL6IB"}
													style={{
														backgroundColor:
															"var(--token-5fde730a-8086-4528-a317-d71b3bf4efde, rgb(0, 0, 0))",
														opacity: 0.06,
													}}
												/>
											</motion.div>
										),
										OYcWLqnA_ && (
											<motion.div
												className={"framer-wtscq4"}
												data-framer-name={"Arc"}
												layoutDependency={layoutDependency}
												layoutId={"x8Dq7q7X2"}
												style={{
													borderBottomLeftRadius: 12,
													borderBottomRightRadius: 12,
													borderTopLeftRadius: 12,
													borderTopRightRadius: 12,
												}}
											>
												<Image
													background={{
														alt: "Figma logo",
														fit: "fit",
														intrinsicHeight: 500,
														intrinsicWidth: 334,
														pixelHeight: 427,
														pixelWidth: 500,
														positionX: "center",
														positionY: "center",
														src: "https://framerusercontent.com/images/Jo45NE9cozyWEGOc3q5r66Sl98.webp",
													}}
													className={"framer-zc71at"}
													data-framer-name={"Logo"}
													layoutDependency={layoutDependency}
													layoutId={"eDfthZ9_v"}
												/>
												<motion.div
													className={"framer-1yerztf"}
													data-framer-name={"BG"}
													layoutDependency={layoutDependency}
													layoutId={"S4SrZGQud"}
													style={{
														backgroundColor:
															"var(--token-5fde730a-8086-4528-a317-d71b3bf4efde, rgb(0, 0, 0))",
														opacity: 0.06,
													}}
												/>
											</motion.div>
										),
										bpy2eO3qs && (
											<motion.div
												className={"framer-uknvnn"}
												data-framer-name={"Screen Studio"}
												layoutDependency={layoutDependency}
												layoutId={"tlMEKcwkx"}
												style={{
													borderBottomLeftRadius: 12,
													borderBottomRightRadius: 12,
													borderTopLeftRadius: 12,
													borderTopRightRadius: 12,
												}}
											>
												<Image
													background={{
														alt: "Figma logo",
														fit: "fit",
														intrinsicHeight: 500,
														intrinsicWidth: 334,
														pixelHeight: 500,
														pixelWidth: 500,
														positionX: "center",
														positionY: "center",
														src: "https://framerusercontent.com/images/9RCvsOul5SzZBJr1jZ2P5dKjLc.webp",
													}}
													className={"framer-lgs4n8"}
													data-framer-name={"Logo"}
													layoutDependency={layoutDependency}
													layoutId={"JLNGTOOjw"}
												/>
												<motion.div
													className={"framer-1n5yity"}
													data-framer-name={"BG"}
													layoutDependency={layoutDependency}
													layoutId={"yawSsQKLc"}
													style={{
														backgroundColor:
															"var(--token-5fde730a-8086-4528-a317-d71b3bf4efde, rgb(0, 0, 0))",
														opacity: 0.06,
													}}
												/>
											</motion.div>
										),
										jB8tXJpTC && (
											<motion.div
												className={"framer-14jyqst"}
												data-framer-name={"Notion"}
												layoutDependency={layoutDependency}
												layoutId={"bYKq8qzo5"}
												style={{
													borderBottomLeftRadius: 12,
													borderBottomRightRadius: 12,
													borderTopLeftRadius: 12,
													borderTopRightRadius: 12,
												}}
											>
												<Image
													background={{
														alt: "Figma logo",
														fit: "fit",
														intrinsicHeight: 500,
														intrinsicWidth: 334,
														pixelHeight: 500,
														pixelWidth: 480,
														positionX: "center",
														positionY: "center",
														src: "https://framerusercontent.com/images/DqvuS90E062F5mQTYxRztACjEWs.webp",
													}}
													className={"framer-1utqf1i"}
													data-framer-name={"Logo"}
													layoutDependency={layoutDependency}
													layoutId={"i4PVjJxFv"}
												/>
												<motion.div
													className={"framer-1k4j1fg"}
													data-framer-name={"BG"}
													layoutDependency={layoutDependency}
													layoutId={"aQSA11sVg"}
													style={{
														backgroundColor:
															"var(--token-5fde730a-8086-4528-a317-d71b3bf4efde, rgb(0, 0, 0))",
														opacity: 0.06,
													}}
												/>
											</motion.div>
										),
										m1j5G2jz5 && (
											<motion.div
												className={"framer-1khef8l"}
												data-framer-name={"Todoist"}
												layoutDependency={layoutDependency}
												layoutId={"UMoTP9dPH"}
												style={{
													borderBottomLeftRadius: 12,
													borderBottomRightRadius: 12,
													borderTopLeftRadius: 12,
													borderTopRightRadius: 12,
												}}
											>
												<Image
													background={{
														alt: "Figma logo",
														fit: "fit",
														intrinsicHeight: 500,
														intrinsicWidth: 334,
														pixelHeight: 499,
														pixelWidth: 500,
														positionX: "center",
														positionY: "center",
														src: "https://framerusercontent.com/images/U3ylarrpMUFRxnC3Nt8EXST36U0.webp",
													}}
													className={"framer-1tj067u"}
													data-framer-name={"Logo"}
													layoutDependency={layoutDependency}
													layoutId={"Odtd8tt6a"}
													style={{
														borderBottomLeftRadius: 6,
														borderBottomRightRadius: 6,
														borderTopLeftRadius: 6,
														borderTopRightRadius: 6,
													}}
												/>
												<motion.div
													className={"framer-103ntoy"}
													data-framer-name={"BG"}
													layoutDependency={layoutDependency}
													layoutId={"IPXNjSkzQ"}
													style={{
														backgroundColor:
															"var(--token-5fde730a-8086-4528-a317-d71b3bf4efde, rgb(0, 0, 0))",
														opacity: 0.06,
													}}
												/>
											</motion.div>
										),
										HkaaGvVyC && (
											<motion.div
												className={"framer-17mvmtd"}
												data-framer-name={"Slack"}
												layoutDependency={layoutDependency}
												layoutId={"hFqh2B8QA"}
												style={{
													borderBottomLeftRadius: 12,
													borderBottomRightRadius: 12,
													borderTopLeftRadius: 12,
													borderTopRightRadius: 12,
												}}
											>
												<Image
													background={{
														alt: "Figma logo",
														fit: "fit",
														intrinsicHeight: 500,
														intrinsicWidth: 334,
														pixelHeight: 460,
														pixelWidth: 460,
														positionX: "center",
														positionY: "center",
														src: "https://framerusercontent.com/images/i1gTadwK9NZWMnCrXF46beqYL6I.webp",
													}}
													className={"framer-gvd3w2"}
													data-framer-name={"Logo"}
													layoutDependency={layoutDependency}
													layoutId={"VmfrIqlwS"}
													style={{
														borderBottomLeftRadius: 6,
														borderBottomRightRadius: 6,
														borderTopLeftRadius: 6,
														borderTopRightRadius: 6,
													}}
												/>
												<motion.div
													className={"framer-viau6s"}
													data-framer-name={"BG"}
													layoutDependency={layoutDependency}
													layoutId={"lE5BzAmJG"}
													style={{
														backgroundColor:
															"var(--token-5fde730a-8086-4528-a317-d71b3bf4efde, rgb(0, 0, 0))",
														opacity: 0.06,
													}}
												/>
											</motion.div>
										),
										uXV2ahTre && (
											<motion.div
												className={"framer-m43mlf"}
												data-framer-name={"ChatGPT"}
												layoutDependency={layoutDependency}
												layoutId={"xLprf9NTZ"}
												style={{
													borderBottomLeftRadius: 12,
													borderBottomRightRadius: 12,
													borderTopLeftRadius: 12,
													borderTopRightRadius: 12,
												}}
											>
												<Image
													background={{
														alt: "Figma logo",
														fit: "fit",
														intrinsicHeight: 500,
														intrinsicWidth: 334,
														pixelHeight: 460,
														pixelWidth: 460,
														positionX: "center",
														positionY: "center",
														src: "https://framerusercontent.com/images/dn7QoOO5bw8IB8S45pqyNaWr1RI.webp",
													}}
													className={"framer-1tld1g7"}
													data-framer-name={"Logo"}
													layoutDependency={layoutDependency}
													layoutId={"PoBe_MoPd"}
													style={{
														borderBottomLeftRadius: 6,
														borderBottomRightRadius: 6,
														borderTopLeftRadius: 6,
														borderTopRightRadius: 6,
													}}
												/>
												<motion.div
													className={"framer-1cg6qpw"}
													data-framer-name={"BG"}
													layoutDependency={layoutDependency}
													layoutId={"LSDPncoNh"}
													style={{
														backgroundColor:
															"var(--token-5fde730a-8086-4528-a317-d71b3bf4efde, rgb(0, 0, 0))",
														opacity: 0.06,
													}}
												/>
											</motion.div>
										),
										SUA4ENaky && (
											<motion.div
												className={"framer-1vaf9hp"}
												data-framer-name={"Lemon Squeezy"}
												layoutDependency={layoutDependency}
												layoutId={"KJYhpArHK"}
												style={{
													borderBottomLeftRadius: 12,
													borderBottomRightRadius: 12,
													borderTopLeftRadius: 12,
													borderTopRightRadius: 12,
												}}
											>
												<Image
													background={{
														alt: "Figma logo",
														fit: "fit",
														intrinsicHeight: 500,
														intrinsicWidth: 334,
														pixelHeight: 500,
														pixelWidth: 500,
														positionX: "center",
														positionY: "center",
														src: "https://framerusercontent.com/images/O04c1vkhn73dPjg0bBMR5PCp0.webp",
													}}
													className={"framer-mnx19l"}
													data-framer-name={"Logo"}
													layoutDependency={layoutDependency}
													layoutId={"aJ5Enm7iz"}
													style={{
														borderBottomLeftRadius: 6,
														borderBottomRightRadius: 6,
														borderTopLeftRadius: 6,
														borderTopRightRadius: 6,
													}}
												/>
												<motion.div
													className={"framer-13on5d1"}
													data-framer-name={"BG"}
													layoutDependency={layoutDependency}
													layoutId={"Ug6MYP13D"}
													style={{
														backgroundColor:
															"var(--token-5fde730a-8086-4528-a317-d71b3bf4efde, rgb(0, 0, 0))",
														opacity: 0.06,
													}}
												/>
											</motion.div>
										),
										GnCjBQvOz && (
											<motion.div
												className={"framer-1q11vyg"}
												data-framer-name={"Cleanshot X"}
												layoutDependency={layoutDependency}
												layoutId={"guqlkor1E"}
												style={{
													borderBottomLeftRadius: 12,
													borderBottomRightRadius: 12,
													borderTopLeftRadius: 12,
													borderTopRightRadius: 12,
												}}
											>
												<Image
													background={{
														alt: "Figma logo",
														fit: "fit",
														intrinsicHeight: 500,
														intrinsicWidth: 334,
														pixelHeight: 500,
														pixelWidth: 494,
														positionX: "center",
														positionY: "center",
														src: "https://framerusercontent.com/images/QTKgXhnox8vWW0STsITqITFKF0.webp",
													}}
													className={"framer-r6hvjq"}
													data-framer-name={"Logo"}
													layoutDependency={layoutDependency}
													layoutId={"GxpUqvFPp"}
												/>
												<motion.div
													className={"framer-u75lpu"}
													data-framer-name={"BG"}
													layoutDependency={layoutDependency}
													layoutId={"MMyugaB71"}
													style={{
														backgroundColor:
															"var(--token-5fde730a-8086-4528-a317-d71b3bf4efde, rgb(0, 0, 0))",
														opacity: 0.06,
													}}
												/>
											</motion.div>
										),
										oQbrY7Sbe && (
											<motion.div
												className={"framer-1bjc9ve"}
												data-framer-name={"Eagle"}
												layoutDependency={layoutDependency}
												layoutId={"KfHhUcZUp"}
												style={{
													borderBottomLeftRadius: 12,
													borderBottomRightRadius: 12,
													borderTopLeftRadius: 12,
													borderTopRightRadius: 12,
												}}
											>
												<Image
													background={{
														alt: "Figma logo",
														fit: "fit",
														intrinsicHeight: 500,
														intrinsicWidth: 334,
														pixelHeight: 412,
														pixelWidth: 412,
														positionX: "center",
														positionY: "center",
														src: "https://framerusercontent.com/images/6iUqSWA8HhqKewIWzauruisFCkE.webp",
													}}
													className={"framer-1smuo5e"}
													data-framer-name={"Logo"}
													layoutDependency={layoutDependency}
													layoutId={"PoHgdIiWC"}
												/>
												<motion.div
													className={"framer-nxqroi"}
													data-framer-name={"BG"}
													layoutDependency={layoutDependency}
													layoutId={"Px6zrCDyq"}
													style={{
														backgroundColor:
															"var(--token-5fde730a-8086-4528-a317-d71b3bf4efde, rgb(0, 0, 0))",
														opacity: 0.06,
													}}
												/>
											</motion.div>
										),
									]}
									speed={20}
									style={{
										height: "100%",
										width: "100%",
									}}
									width={"100%"}
								/>
							</SmartComponentScopedContainer>
						</ComponentViewportProvider>
					</motion.div>
				</Transition>
			</Variants>
		</LayoutGroup>
	);
});
var css = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-GpMko.framer-120kk54, .framer-GpMko .framer-120kk54 { display: block; }",
	".framer-GpMko.framer-otnia9 { align-content: center; align-items: center; display: flex; flex-direction: column; flex-wrap: nowrap; gap: 0px; height: 48px; justify-content: center; overflow: hidden; padding: 0px; position: relative; width: 248px; }",
	".framer-GpMko .framer-189d1n4-container { flex: none; height: 48px; position: relative; width: 100%; z-index: 1; }",
	".framer-GpMko .framer-1n6plnc, .framer-GpMko .framer-1bynfb1, .framer-GpMko .framer-wtscq4, .framer-GpMko .framer-uknvnn, .framer-GpMko .framer-14jyqst, .framer-GpMko .framer-1khef8l, .framer-GpMko .framer-17mvmtd, .framer-GpMko .framer-m43mlf, .framer-GpMko .framer-1vaf9hp, .framer-GpMko .framer-1q11vyg, .framer-GpMko .framer-1bjc9ve { align-content: center; align-items: center; aspect-ratio: 1 / 1; display: flex; flex-direction: row; flex-wrap: nowrap; gap: 0px; height: var(--framer-aspect-ratio-supported, 72px); justify-content: center; overflow: hidden; padding: 0px; position: relative; width: 48px; will-change: var(--framer-will-change-override, transform); }",
	".framer-GpMko .framer-17stpwo, .framer-GpMko .framer-bnmo96, .framer-GpMko .framer-zc71at, .framer-GpMko .framer-lgs4n8, .framer-GpMko .framer-1utqf1i, .framer-GpMko .framer-r6hvjq, .framer-GpMko .framer-1smuo5e { bottom: 12px; flex: none; left: 12px; overflow: hidden; position: absolute; right: 12px; top: 12px; z-index: 2; }",
	".framer-GpMko .framer-1cd17wh, .framer-GpMko .framer-n29enr, .framer-GpMko .framer-1yerztf, .framer-GpMko .framer-1n5yity, .framer-GpMko .framer-1k4j1fg, .framer-GpMko .framer-103ntoy, .framer-GpMko .framer-viau6s, .framer-GpMko .framer-1cg6qpw, .framer-GpMko .framer-13on5d1, .framer-GpMko .framer-u75lpu, .framer-GpMko .framer-nxqroi { bottom: 0px; flex: none; left: 0px; overflow: visible; position: absolute; right: 0px; top: 0px; z-index: 1; }",
	".framer-GpMko .framer-1tj067u, .framer-GpMko .framer-gvd3w2, .framer-GpMko .framer-1tld1g7, .framer-GpMko .framer-mnx19l { bottom: 12px; flex: none; left: 12px; overflow: hidden; position: absolute; right: 12px; top: 12px; will-change: var(--framer-will-change-override, transform); z-index: 2; }",
];
var FramerLzLEJm3wA = withCSS(Component, css, "framer-GpMko");
var stdin_default = FramerLzLEJm3wA;
FramerLzLEJm3wA.displayName = "Stack (Phone)";
FramerLzLEJm3wA.defaultProps = {
	height: 48,
	width: 248,
};
addPropertyControls(FramerLzLEJm3wA, {
	NNT__C6zQ: {
		defaultValue: true,
		title: "Figma",
		type: ControlType.Boolean,
	},
	lPo95_jsk: {
		defaultValue: true,
		title: "Framer",
		type: ControlType.Boolean,
	},
	jB8tXJpTC: {
		defaultValue: true,
		title: "Notion",
		type: ControlType.Boolean,
	},
	m1j5G2jz5: {
		defaultValue: true,
		title: "Todoist",
		type: ControlType.Boolean,
	},
	OYcWLqnA_: {
		defaultValue: true,
		title: "Arc",
		type: ControlType.Boolean,
	},
	HkaaGvVyC: {
		defaultValue: true,
		title: "Slack",
		type: ControlType.Boolean,
	},
	uXV2ahTre: {
		defaultValue: true,
		title: "ChatGPT",
		type: ControlType.Boolean,
	},
	GnCjBQvOz: {
		defaultValue: true,
		title: "Cleanshot X",
		type: ControlType.Boolean,
	},
	SUA4ENaky: {
		defaultValue: true,
		title: "Lemon Squeezy",
		type: ControlType.Boolean,
	},
	oQbrY7Sbe: {
		defaultValue: true,
		title: "Eagle",
		type: ControlType.Boolean,
	},
	bpy2eO3qs: {
		defaultValue: true,
		title: "Screen Studio",
		type: ControlType.Boolean,
	},
});
addFonts(
	FramerLzLEJm3wA,
	[
		{
			explicitInter: true,
			fonts: [],
		},
		...TickerFonts,
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// virtual:stack-phone
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"cde98c358c3069ef2a8dce28a8c2c8459e940a47824cf38ac0a6e3a305f8bfbb"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default, {
				...rest,
			})}
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders StackPhoneFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"cde98c358c3069ef2a8dce28a8c2c8459e940a47824cf38ac0a6e3a305f8bfbb"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				Component={stdin_default}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default);
var stack_phone_default = ComponentWithRoot;
export { stack_phone_default as default };
