// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project cde98c358c3069ef "matt.buzz", do not edit manually */

//=====================================================================================
// IMPORTS & DEPENDENCIES
//=====================================================================================

// Stack Desktop component import
import {
  stdin_default
} from "./layout-container.js";

// Framer/React imports
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import {
  addFonts,
  addPropertyControls,
  ComponentViewportProvider,
  ControlType,
  cx,
  getFonts,
  getFontsFromSharedStyle,
  getLoadingLazyAtYPosition,
  Image,
  Link,
  RichText,
  SmartComponentScopedContainer,
  SVG,
  useActiveVariantCallback,
  useComponentViewport,
  useLocaleInfo,
  useVariantState,
  withCSS
} from "unframer";
import { LayoutGroup, motion, MotionConfigContext } from "unframer";
import * as React from "react";
import { useRef } from "react";

//=====================================================================================
// TYPOGRAPHY & STYLE DEFINITIONS
//=====================================================================================

// Load custom fonts
import { fontStore } from "unframer";
fontStore.loadFonts(["BI;Open Sauce Sans/Medium/v0"]);

// Font definitions with Open Sauce Sans
var fonts = [{
  explicitInter: true,
  fonts: [{
    family: "Open Sauce Sans",
    source: "builtIn",
    style: "normal",
    url: "https://framerusercontent.com/assets/O2R7AhA6wjBk0GHLJl0N8fqxN0.woff2",
    weight: "500"
  }]
}];

// Responsive typography styles for text elements
var css = [
  // Base desktop styles (18px font size)
  '.framer-eig1F .framer-styles-preset-fxkedf:not(.rich-text-wrapper), .framer-eig1F .framer-styles-preset-fxkedf.rich-text-wrapper p { --framer-font-family: "Open Sauce Sans", "Open Sauce Sans Placeholder", sans-serif; --framer-font-open-type-features: normal; --framer-font-size: 18px; --framer-font-style: normal; --framer-font-variation-axes: normal; --framer-font-weight: 500; --framer-letter-spacing: -0.02em; --framer-line-height: 1.2em; --framer-paragraph-spacing: 0px; --framer-text-alignment: start; --framer-text-color: var(--token-5fde730a-8086-4528-a317-d71b3bf4efde, #ffffff); --framer-text-decoration: none; --framer-text-stroke-color: initial; --framer-text-stroke-width: initial; --framer-text-transform: none; }',

  // Large desktop (1025px - 1439px) - same as base
  '@media (max-width: 1439px) and (min-width: 1025px) { .framer-eig1F .framer-styles-preset-fxkedf:not(.rich-text-wrapper), .framer-eig1F .framer-styles-preset-fxkedf.rich-text-wrapper p { --framer-font-family: "Open Sauce Sans", "Open Sauce Sans Placeholder", sans-serif; --framer-font-open-type-features: normal; --framer-font-size: 18px; --framer-font-style: normal; --framer-font-variation-axes: normal; --framer-font-weight: 500; --framer-letter-spacing: -0.02em; --framer-line-height: 1.2em; --framer-paragraph-spacing: 0px; --framer-text-alignment: start; --framer-text-color: var(--token-5fde730a-8086-4528-a317-d71b3bf4efde, #ffffff); --framer-text-decoration: none; --framer-text-stroke-color: initial; --framer-text-stroke-width: initial; --framer-text-transform: none; } }',

  // Tablet (700px - 1024px) - same as base
  '@media (max-width: 1024px) and (min-width: 700px) { .framer-eig1F .framer-styles-preset-fxkedf:not(.rich-text-wrapper), .framer-eig1F .framer-styles-preset-fxkedf.rich-text-wrapper p { --framer-font-family: "Open Sauce Sans", "Open Sauce Sans Placeholder", sans-serif; --framer-font-open-type-features: normal; --framer-font-size: 18px; --framer-font-style: normal; --framer-font-variation-axes: normal; --framer-font-weight: 500; --framer-letter-spacing: -0.02em; --framer-line-height: 1.2em; --framer-paragraph-spacing: 0px; --framer-text-alignment: start; --framer-text-color: var(--token-5fde730a-8086-4528-a317-d71b3bf4efde, #ffffff); --framer-text-decoration: none; --framer-text-stroke-color: initial; --framer-text-stroke-width: initial; --framer-text-transform: none; } }',

  // Mobile (0px - 699px) - reduced to 16px
  '@media (max-width: 699px) and (min-width: 0px) { .framer-eig1F .framer-styles-preset-fxkedf:not(.rich-text-wrapper), .framer-eig1F .framer-styles-preset-fxkedf.rich-text-wrapper p { --framer-font-family: "Open Sauce Sans", "Open Sauce Sans Placeholder", sans-serif; --framer-font-open-type-features: normal; --framer-font-size: 16px; --framer-font-style: normal; --framer-font-variation-axes: normal; --framer-font-weight: 500; --framer-letter-spacing: -0.02em; --framer-line-height: 1.2em; --framer-paragraph-spacing: 0px; --framer-text-alignment: start; --framer-text-color: var(--token-5fde730a-8086-4528-a317-d71b3bf4efde, #ffffff); --framer-text-decoration: none; --framer-text-stroke-color: initial; --framer-text-stroke-width: initial; --framer-text-transform: none; } }'
];

// CSS class name for typography
var className = "framer-eig1F";

//=====================================================================================
// CONFIGURATION & CONSTANTS
//=====================================================================================

// Font configuration for Stack Desktop component
var StackDesktopFonts = getFonts(stdin_default);

// Gesture configuration for hover effects
var enabledGestures = {
  fx6U7VIVw: { hover: true },   // Contacts hover
  Nv38W5Tsu: { hover: true },   // Desktop hover
  OGXHpotWX: { hover: true },   // Stack hover
  xdiOya1aU: { hover: true }    // Phone hover
};

// Variant cycle order for switching between states
var cycleOrder = ["Nv38W5Tsu", "OGXHpotWX", "xdiOya1aU", "fx6U7VIVw", "dvvNQHRiV"];

// Component serialization hash for CSS scoping
var serializationHash = "framer-CTg5A";

// Variant class names mapping
var variantClassNames = {
  dvvNQHRiV: "framer-v-mz1i6h",   // Variant
  fx6U7VIVw: "framer-v-11w9w5n",  // Contacts
  Nv38W5Tsu: "framer-v-b3980a",   // Desktop
  OGXHpotWX: "framer-v-152idn9",  // Stack
  xdiOya1aU: "framer-v-1cyedt2"   // Phone
};

// Spring transition configuration
var transition1 = {
  damping: 80,
  delay: 0,
  mass: 1,
  stiffness: 400,
  type: "spring"
};

// Human readable variant mapping
var humanReadableVariantMap = {
  Contacts: "fx6U7VIVw",
  Desktop: "Nv38W5Tsu",
  Phone: "xdiOya1aU",
  Stack: "OGXHpotWX",
  Variant: "dvvNQHRiV"
};

//=====================================================================================
// UTILITY FUNCTIONS
//=====================================================================================

// Adds property overrides based on variant states
function addPropertyOverrides(overrides, ...variants) {
  const nextOverrides = {};
  variants?.forEach((variant) => variant && Object.assign(nextOverrides, overrides[variant]));
  return nextOverrides;
}

// Converts number to pixel string
var numberToPixelString = (value) => {
  if (typeof value !== "number") return value;
  if (!Number.isFinite(value)) return void 0;
  return Math.max(0, value) + "px";
};

// Calculates radius for specific corner based on border radius value
var radiusForCorner = (value, cornerIndex) => {
  if (typeof value === "number" && Number.isFinite(value)) return Math.max(0, value) + "px";
  if (typeof value !== "string" || typeof cornerIndex !== "number") return void 0;
  const segments = value.split(" ");
  return segments[cornerIndex] || segments[cornerIndex - 2] || segments[0];
};

// Converts image value to responsive image format
var toResponsiveImage = (value) => {
  if (typeof value === "object" && value !== null && typeof value.src === "string") {
    return value;
  }
  return typeof value === "string" ? { src: value } : void 0;
};

// Transition wrapper component for motion config
var Transition = ({ value, children }) => {
  const config = React.useContext(MotionConfigContext);
  const transition = value ?? config.transition;
  const contextValue = React.useMemo(() => ({ ...config, transition }), [JSON.stringify(transition)]);
  return /* @__PURE__ */ _jsx(MotionConfigContext.Provider, { value: contextValue, children });
};

// Variants wrapper for motion fragments
var Variants = motion.create(React.Fragment);

//=====================================================================================
// PROPS MAPPING & UTILITIES
//=====================================================================================

// Maps external prop names to internal prop names
var getProps = ({
  bGBlur,
  height,
  id,
  image2,
  label,
  link,
  mouseEnter,
  mouseLeave,
  newTab,
  padding,
  radius,
  width,
  ...props
}) => {
  return {
    ...props,
    // Background image for the component
    Gafzg9nL9: image2 ?? props.Gafzg9nL9 ?? {
      alt: "",
      pixelHeight: 5472,
      pixelWidth: 3648,
      src: "https://framerusercontent.com/images/lvGu7F0gtoBT5Bv16auZ5ADVaM.jpg?scale-down-to=512&width=3648&height=5472",
      srcSet: "https://framerusercontent.com/images/lvGu7F0gtoBT5Bv16auZ5ADVaM.jpg?scale-down-to=1024&width=3648&height=5472 682w,https://framerusercontent.com/images/lvGu7F0gtoBT5Bv16auZ5ADVaM.jpg?scale-down-to=2048&width=3648&height=5472 1365w,https://framerusercontent.com/images/lvGu7F0gtoBT5Bv16auZ5ADVaM.jpg?scale-down-to=4096&width=3648&height=5472 2730w,https://framerusercontent.com/images/lvGu7F0gtoBT5Bv16auZ5ADVaM.jpg?width=3648&height=5472 3648w"
    },
    // Component styling properties
    IjIe6W9ul: padding ?? props.IjIe6W9ul ?? "32px",         // Padding
    Iy5zBGhef: newTab ?? props.Iy5zBGhef,                    // Open in new tab
    L_eB2gWj1: label ?? props.L_eB2gWj1 ?? "About",          // Label text
    N1CQJWodn: bGBlur ?? props.N1CQJWodn ?? 10,              // Background blur amount
    RiNaLEmTk: mouseLeave ?? props.RiNaLEmTk,                // Mouse leave callback
    toX_51tQK: mouseEnter ?? props.toX_51tQK,                // Mouse enter callback
    tULH8ktmi: link ?? props.tULH8ktmi,                      // Link URL
    variant: humanReadableVariantMap[props.variant] ?? props.variant ?? "Nv38W5Tsu", // Variant
    wqT46RT44: radius ?? props.wqT46RT44 ?? "24px"           // Border radius
  };
};

// Creates layout dependency string from props and variants
var createLayoutDependency = (props, variants) => {
  if (props.layoutDependency) return variants.join("-") + props.layoutDependency;
  return variants.join("-");
};

//=====================================================================================
// MAIN COMPONENT - HEADER BOX
//=====================================================================================

// Header box component with multiple variants and hover effects
var Component = /* @__PURE__ */ React.forwardRef(function(props, ref) {
  // Ref handling
  const fallbackRef = useRef(null);
  const refBinding = ref ?? fallbackRef;

  // Layout and locale setup
  const defaultLayoutId = React.useId();
  const { activeLocale, setLocale } = useLocaleInfo();
  const componentViewport = useComponentViewport();

  // Extract props with proper mapping
  const {
    style,
    className: className2,
    layoutId,
    variant,
    // Component properties
    L_eB2gWj1,    // label text
    IjIe6W9ul,    // padding
    wqT46RT44,    // radius
    N1CQJWodn,    // background blur
    toX_51tQK,    // mouse enter callback
    RiNaLEmTk,    // mouse leave callback
    tULH8ktmi,    // link URL
    Iy5zBGhef,    // new tab setting
    Gafzg9nL9,    // background image
    ...restProps
  } = getProps(props);

  // Variant state management with gesture support
  const {
    baseVariant,
    classNames,
    clearLoadingGesture,
    gestureHandlers,
    gestureVariant,
    isLoading,
    setGestureState,
    setVariant,
    variants
  } = useVariantState({
    cycleOrder,
    defaultVariant: "Nv38W5Tsu",
    enabledGestures,
    ref: refBinding,
    variant,
    variantClassNames
  });

  // Layout dependency and active variant callback
  const layoutDependency = createLayoutDependency(props, variants);
  const { activeVariantCallback, delay } = useActiveVariantCallback(baseVariant);

  // Mouse event handlers
  const onMouseEnterh7csd7 = activeVariantCallback(async (...args) => {
    setGestureState({ isHovered: true });
    if (toX_51tQK) {
      const res = await toX_51tQK(...args);
      if (res === false) return false;
    }
  });

  const onMouseLeave1tcs09t = activeVariantCallback(async (...args) => {
    setGestureState({ isHovered: false });
    if (RiNaLEmTk) {
      const res = await RiNaLEmTk(...args);
      if (res === false) return false;
    }
  });

  // Styling setup
  const sharedStyleClassNames = [className];
  const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);

  // Display logic for conditional rendering
  const isDisplayed = () => {
    if (gestureVariant === "OGXHpotWX-hover") return true;
    if (baseVariant === "OGXHpotWX") return true;
    return false;
  };

  const isDisplayed1 = () => {
    if (gestureVariant === "OGXHpotWX-hover") return false;
    if (baseVariant === "OGXHpotWX") return false;
    return true;
  };

  //===================================================================================
  // RENDER
  //===================================================================================

  return _jsx(LayoutGroup, {
    id: layoutId ?? defaultLayoutId,
    children: _jsx(Variants, {
      animate: variants,
      initial: false,
      children: _jsx(Transition, {
        value: transition1,
        children: _jsx(Link, {
          href: tULH8ktmi,
          motionChild: true,
          nodeId: "Nv38W5Tsu",
          openInNewTab: Iy5zBGhef,
          scopeId: "SlYfGW2gH",
          smoothScroll: true,
          // Variant-specific link overrides
          ...addPropertyOverrides({
            "OGXHpotWX-hover": { href: void 0 },
            OGXHpotWX: { href: void 0 }
          }, baseVariant, gestureVariant),
          children: _jsxs(Image, {
            ...restProps,
            ...gestureHandlers,
            className: `${cx(scopingClassNames, "framer-b3980a", className2, classNames)} framer-y1tnc3`,
            "data-framer-name": "Desktop",
            "data-highlight": true,
            layoutDependency,
            layoutId: "Nv38W5Tsu",
            onMouseEnter: onMouseEnterh7csd7,
            onMouseLeave: onMouseLeave1tcs09t,
            ref: refBinding,
            style: {
              // CSS custom property for padding
              "--1etlsou": numberToPixelString(IjIe6W9ul),
              // Glass morphism effect
              backdropFilter: `blur(${N1CQJWodn}px)`,
              // Dynamic border radius
              borderBottomLeftRadius: radiusForCorner(wqT46RT44, 3),
              borderBottomRightRadius: radiusForCorner(wqT46RT44, 2),
              borderTopLeftRadius: radiusForCorner(wqT46RT44, 0),
              borderTopRightRadius: radiusForCorner(wqT46RT44, 1),
              // Subtle border highlight
              boxShadow: "inset 0px 1px 0px 1px var(--token-4ad2450b-089e-49a2-b079-884bae7e4c6d, rgba(255, 255, 255, 0.06))",
              ...style
            },
            // Variant-specific property overrides
            ...addPropertyOverrides({
              "fx6U7VIVw-hover": {
                "data-framer-name": void 0,
                as: "a",
                background: {
                  alt: "",
                  fit: "fill",
                  loading: getLoadingLazyAtYPosition(componentViewport?.y || 0),
                  pixelHeight: 775,
                  pixelWidth: 1707,
                  sizes: componentViewport?.width || "100vw",
                  src: "https://framerusercontent.com/images/vJxqj3bQlRltpy88lvgtUdos.jpg?width=1707&height=775",
                  srcSet: "https://framerusercontent.com/images/vJxqj3bQlRltpy88lvgtUdos.jpg?scale-down-to=512&width=1707&height=775 512w,https://framerusercontent.com/images/vJxqj3bQlRltpy88lvgtUdos.jpg?scale-down-to=1024&width=1707&height=775 1024w,https://framerusercontent.com/images/vJxqj3bQlRltpy88lvgtUdos.jpg?width=1707&height=775 1707w"
                }
              },
              "Nv38W5Tsu-hover": { "data-framer-name": void 0 },
              "OGXHpotWX-hover": { "data-framer-name": void 0 },
              "xdiOya1aU-hover": { "data-framer-name": void 0 },
              dvvNQHRiV: { "data-framer-name": void 0 },
              fx6U7VIVw: { "data-framer-name": "Contacts" },
              OGXHpotWX: { "data-framer-name": "Stack" },
              xdiOya1aU: { "data-framer-name": "Phone" }
            }, baseVariant, gestureVariant),
            children: [
              //===============================================================================
              // STACK DESKTOP COMPONENT (conditional)
              //===============================================================================

              isDisplayed() && _jsx(ComponentViewportProvider, {
                ...addPropertyOverrides({
                  OGXHpotWX: {
                    height: 72,
                    width: `calc(${componentViewport?.width || "100vw"} - ${IjIe6W9ul * 2}px)`
                  }
                }, baseVariant, gestureVariant),
                children: _jsx(SmartComponentScopedContainer, {
                  className: "framer-zzloin-container",
                  layoutDependency,
                  layoutId: "k72_9M7bq-container",
                  nodeId: "k72_9M7bq",
                  rendersWithMotion: true,
                  scopeId: "SlYfGW2gH",
                  children: _jsx(stdin_default, {
                    // Stack Desktop component configuration
                    bpy2eO3qs: true,    // Screen Studio
                    GnCjBQvOz: false,   // CleanShot X
                    height: "100%",
                    HkaaGvVyC: false,   // Slack
                    id: "k72_9M7bq",
                    jB8tXJpTC: true,    // Notion
                    layoutId: "k72_9M7bq",
                    lPo95_jsk: true,    // Framer
                    m1j5G2jz5: false,   // Todoist
                    NNT__C6zQ: true,    // Figma
                    oQbrY7Sbe: true,    // Eagle
                    OYcWLqnA_: true,    // Arc
                    style: { width: "100%" },
                    SUA4ENaky: true,    // Lemon Squeezy
                    uXV2ahTre: true,    // ChatGPT
                    width: "100%"
                  })
                })
              }),

              //===============================================================================
              // TITLE AND ICON SECTION (conditional)
              //===============================================================================

              isDisplayed1() && _jsxs(motion.div, {
                className: "framer-2yvwc7",
                "data-framer-name": "Title",
                layoutDependency,
                layoutId: "glUk3EoB7",
                children: [
                  // Text container with skew effect
                  _jsxs(motion.div, {
                    className: "framer-17ev1q9",
                    "data-framer-name": "Text",
                    layoutDependency,
                    layoutId: "h9PlYsPKR",
                    children: [
                      // Main text (normal state)
                      _jsx(RichText, {
                        __fromCanvasComponent: true,
                        children: _jsx(React.Fragment, {
                          children: _jsx(motion.p, {
                            className: "framer-styles-preset-fxkedf",
                            "data-styles-preset": "eZzRnnvfO",
                            children: "About"
                          })
                        }),
                        className: "framer-196o8av",
                        "data-framer-name": "Text",
                        fonts: ["Inter"],
                        layoutDependency,
                        layoutId: "cnbHjymwZ",
                        style: {
                          "--framer-link-text-color": "rgb(0, 153, 255)",
                          "--framer-link-text-decoration": "underline",
                          skewY: 0
                        },
                        text: L_eB2gWj1,
                        // Skew animation variants
                        variants: {
                          "fx6U7VIVw-hover": { skewY: 0 },
                          "Nv38W5Tsu-hover": { skewY: 12 },
                          "xdiOya1aU-hover": { skewY: 12 }
                        },
                        verticalAlignment: "top",
                        withExternalLayout: true
                      }),

                      // Duplicate text for smooth skew transition
                      _jsx(RichText, {
                        __fromCanvasComponent: true,
                        children: _jsx(React.Fragment, {
                          children: _jsx(motion.p, {
                            className: "framer-styles-preset-fxkedf",
                            "data-styles-preset": "eZzRnnvfO",
                            children: "About"
                          })
                        }),
                        className: "framer-3c1z9t",
                        "data-framer-name": "Text",
                        fonts: ["Inter"],
                        layoutDependency,
                        layoutId: "Wzvz3w0QL",
                        style: {
                          "--framer-link-text-color": "rgb(0, 153, 255)",
                          "--framer-link-text-decoration": "underline",
                          skewY: 12
                        },
                        text: L_eB2gWj1,
                        // Reverse skew animation variants
                        variants: {
                          "Nv38W5Tsu-hover": { skewY: 0 },
                          "xdiOya1aU-hover": { skewY: 0 }
                        },
                        verticalAlignment: "top",
                        withExternalLayout: true
                      })
                    ]
                  }),

                  // Arrow icon container
                  _jsx(motion.div, {
                    className: "framer-1q1abns",
                    "data-framer-name": "Icon",
                    layoutDependency,
                    layoutId: "ju1Kno2Ta",
                    children: _jsx(motion.div, {
                      className: "framer-1sreug4",
                      "data-framer-name": "Icon",
                      layoutDependency,
                      layoutId: "NlnsEMzt3",
                      style: { rotate: -45 },
                      children: _jsx(SVG, {
                        className: "framer-cmxh54",
                        "data-framer-name": "Arrow-right",
                        layout: "position",
                        layoutDependency,
                        layoutId: "O9P25t9av",
                        opacity: 1,
                        svg: '<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="0 0 18 16"><path d="M 0.667 7 L 14.958 7 L 8.833 0.875 L 9.603 0 L 17.187 7.583 L 9.603 15.167 L 8.833 14.292 L 14.958 8.167 L 0.667 8.167 Z" fill="var(--token-5fde730a-8086-4528-a317-d71b3bf4efde, rgb(0, 0, 0))"></path></svg>',
                        svgContentId: 9794630709,
                        withExternalLayout: true,
                        // Variant-specific SVG overrides for different arrow sizes
                        ...addPropertyOverrides({
                          "xdiOya1aU-hover": {
                            svg: '<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="0 0 16 14"><path d="M 0.595 6.152 L 13.342 6.152 L 7.879 0.769 L 8.566 0 L 15.33 6.665 L 8.566 13.33 L 7.879 12.561 L 13.342 7.178 L 0.595 7.178 Z" fill="var(--token-5fde730a-8086-4528-a317-d71b3bf4efde, rgb(0, 0, 0))"></path></svg>',
                            svgContentId: 12484514364
                          },
                          xdiOya1aU: {
                            svg: '<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="0 0 17 15"><path d="M 1.595 7.152 L 14.342 7.152 L 8.879 1.769 L 9.566 1 L 16.33 7.665 L 9.566 14.33 L 8.879 13.561 L 14.342 8.178 L 1.595 8.178 Z" fill="var(--token-5fde730a-8086-4528-a317-d71b3bf4efde, rgb(0, 0, 0))"></path></svg>',
                            svgContentId: 12372259597
                          }
                        }, baseVariant, gestureVariant)
                      })
                    })
                  })
                ]
              }),

              //===============================================================================
              // UNIFIED BACKGROUND IMAGE
              //===============================================================================

              _jsx(Image, {
                background: {
                  alt: "",
                  fit: "fill",
                  loading: getLoadingLazyAtYPosition((componentViewport?.y || 0) + 0),
                  pixelHeight: 5472,
                  pixelWidth: 3648,
                  sizes: componentViewport?.width || "100vw",
                  src: "https://framerusercontent.com/images/WkhfKz1YJ2Y3ADVaM.jpg",
                  srcSet: "https://framerusercontent.com/images/WkhfKz1YJ2Y3ADVaM.jpg 3648w"
                },
                className: "framer-1dretve unified-tile-bg",
                "data-framer-name": "BG",
                layoutDependency,
                layoutId: "EOW2DOgSb",
                style: {
                  backdropFilter: "blur(0px)",
                  opacity: 0.31,
                  WebkitBackdropFilter: "blur(0px)"
                },
                // Opacity change variants on hover
                variants: {
                  "Nv38W5Tsu-hover": { opacity: 0.02 },
                  "OGXHpotWX-hover": { opacity: 0.02 },
                  "xdiOya1aU-hover": { opacity: 0.02 }
                },
                // Variant-specific background overrides
                ...addPropertyOverrides({
                  "Nv38W5Tsu-hover": { background: void 0 },
                  fx6U7VIVw: {
                    background: {
                      alt: "",
                      fit: "fill",
                      loading: getLoadingLazyAtYPosition((componentViewport?.y || 0) + 0),
                      pixelHeight: 5472,
                      pixelWidth: 3648,
                      sizes: componentViewport?.width || "100vw",
                      src: "https://framerusercontent.com/images/WkhfKz1YJ2Y3ADVaM.jpg",
                      srcSet: "https://framerusercontent.com/images/WkhfKz1YJ2Y3ADVaM.jpg 3648w"
                    }
                  }
                }, baseVariant, gestureVariant)
              })
            ]
          })
        })
      })
    })
  });
});

//=====================================================================================
// COMPONENT STYLING & CONFIGURATION
//=====================================================================================

// Combined CSS styles including typography and layout
var css2 = [
  "@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
  ".framer-CTg5A.framer-y1tnc3, .framer-CTg5A .framer-y1tnc3 { display: block; }",

  // Base desktop variant styles
  ".framer-CTg5A.framer-b3980a { align-content: center; align-items: center; cursor: pointer; display: flex; flex-direction: column; flex-wrap: nowrap; gap: 16px; height: 300px; justify-content: flex-end; overflow: hidden; padding: var(--1etlsou); position: relative; text-decoration: none; width: 340px; will-change: var(--framer-will-change-override, transform); }",

  // Stack Desktop container styles
  ".framer-CTg5A .framer-zzloin-container { flex: none; height: auto; position: relative; width: 100%; }",

  // Title container styles
  ".framer-CTg5A .framer-2yvwc7 { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; height: min-content; justify-content: space-between; overflow: hidden; padding: 0px; position: relative; width: 100%; z-index: 2; }",

  // Text container with skew effect
  ".framer-CTg5A .framer-17ev1q9 { -webkit-user-select: none; align-content: center; align-items: center; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 8px; height: 22px; justify-content: flex-start; overflow: hidden; padding: 0px; position: relative; user-select: none; width: min-content; }",

  // Text elements
  ".framer-CTg5A .framer-196o8av, .framer-CTg5A .framer-3c1z9t { flex: none; height: auto; position: relative; white-space: pre; width: auto; }",

  // Icon container styles
  ".framer-CTg5A .framer-1q1abns { align-content: center; align-items: center; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: center; overflow: visible; padding: 0px; position: relative; width: min-content; }",

  // Icon wrapper styles
  ".framer-CTg5A .framer-1sreug4 { align-content: center; align-items: center; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 0px; height: min-content; justify-content: flex-start; overflow: hidden; padding: 0px; position: relative; width: min-content; }",

  // SVG arrow styles
  ".framer-CTg5A .framer-cmxh54 { flex: none; height: 16px; position: relative; width: 18px; }",

  // Background image styles
  ".framer-CTg5A .framer-1dretve { bottom: 0px; flex: none; gap: 10px; left: 0px; overflow: hidden; position: absolute; right: 0px; top: 0px; z-index: 1; }",

  // Stack variant specific styles
  ".framer-CTg5A.framer-v-152idn9.framer-b3980a { justify-content: center; }",
  ".framer-CTg5A.framer-v-152idn9 .framer-zzloin-container { order: 1; }",
  ".framer-CTg5A.framer-v-152idn9 .framer-1dretve { order: 2; }",

  // Phone variant specific styles
  ".framer-CTg5A.framer-v-1cyedt2 .framer-cmxh54 { height: 15px; width: 17px; }",

  // Variant specific styles
  ".framer-CTg5A.framer-v-mz1i6h.framer-b3980a { cursor: unset; }",

  // Hover state styles
  ".framer-CTg5A.framer-v-b3980a.hover .framer-17ev1q9, .framer-CTg5A.framer-v-b3980a.hover .framer-1sreug4, .framer-CTg5A.framer-v-1cyedt2.hover .framer-17ev1q9 { justify-content: flex-end; }",
  ".framer-CTg5A.framer-v-1cyedt2.hover .framer-cmxh54 { height: 14px; width: 16px; }",

  // Include typography CSS
  ...css
];

//=====================================================================================
// EXPORTS & CONFIGURATION
//=====================================================================================

// Apply CSS and create final component
var FramerSlYfGW2gH = withCSS(Component, css2, "framer-CTg5A");
var stdin_default2 = FramerSlYfGW2gH;

// Component metadata
FramerSlYfGW2gH.displayName = "Header Box";
FramerSlYfGW2gH.defaultProps = {
  height: 300,
  width: 340
};

// Property controls for Framer interface
addPropertyControls(FramerSlYfGW2gH, {
  variant: {
    options: ["Nv38W5Tsu", "OGXHpotWX", "xdiOya1aU", "fx6U7VIVw", "dvvNQHRiV"],
    optionTitles: ["Desktop", "Stack", "Phone", "Contacts", "Variant"],
    title: "Variant",
    type: ControlType.Enum
  },
  L_eB2gWj1: {
    defaultValue: "About",
    displayTextArea: false,
    title: "Label",
    type: ControlType.String
  },
  IjIe6W9ul: {
    defaultValue: "32px",
    title: "Padding",
    type: ControlType.Padding
  },
  wqT46RT44: {
    defaultValue: "24px",
    title: "Radius",
    type: ControlType.BorderRadius
  },
  N1CQJWodn: {
    defaultValue: 10,
    title: "BG Blur",
    type: ControlType.Number
  },
  toX_51tQK: {
    title: "Mouse Enter",
    type: ControlType.EventHandler
  },
  RiNaLEmTk: {
    title: "Mouse Leave",
    type: ControlType.EventHandler
  },
  tULH8ktmi: {
    title: "Link",
    type: ControlType.Link
  },
  Iy5zBGhef: {
    defaultValue: false,
    title: "New Tab",
    type: ControlType.Boolean
  },
  Gafzg9nL9: {
    __defaultAssetReference: "data:framer/asset-reference,lvGu7F0gtoBT5Bv16auZ5ADVaM.jpg?originalFilename=pexels-roberto-nickson-2486168.jpg&width=3648&height=5472",
    __vekterDefault: {
      alt: "",
      assetReference: "data:framer/asset-reference,lvGu7F0gtoBT5Bv16auZ5ADVaM.jpg?originalFilename=pexels-roberto-nickson-2486168.jpg&width=3648&height=5472"
    },
    title: "Image 2",
    type: ControlType.ResponsiveImage
  }
});

// Add fonts configuration with Inter and Open Sauce Sans
addFonts(FramerSlYfGW2gH, [
  {
    explicitInter: true,
    fonts: [
      { family: "Inter", source: "framer", style: "normal", unicodeRange: "U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F", url: "https://framerusercontent.com/assets/5vvr9Vy74if2I6bQbJvbw7SY1pQ.woff2", weight: "400" },
      { family: "Inter", source: "framer", style: "normal", unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116", url: "https://framerusercontent.com/assets/EOr0mi4hNtlgWNn9if640EZzXCo.woff2", weight: "400" },
      { family: "Inter", source: "framer", style: "normal", unicodeRange: "U+1F00-1FFF", url: "https://framerusercontent.com/assets/Y9k9QrlZAqio88Klkmbd8VoMQc.woff2", weight: "400" },
      { family: "Inter", source: "framer", style: "normal", unicodeRange: "U+0370-03FF", url: "https://framerusercontent.com/assets/OYrD2tBIBPvoJXiIHnLoOXnY9M.woff2", weight: "400" },
      { family: "Inter", source: "framer", style: "normal", unicodeRange: "U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF", url: "https://framerusercontent.com/assets/JeYwfuaPfZHQhEG8U5gtPDZ7WQ.woff2", weight: "400" },
      { family: "Inter", source: "framer", style: "normal", unicodeRange: "U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2070, U+2074-207E, U+2080-208E, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD", url: "https://framerusercontent.com/assets/GrgcKwrN6d3Uz8EwcLHZxwEfC4.woff2", weight: "400" },
      { family: "Inter", source: "framer", style: "normal", unicodeRange: "U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB", url: "https://framerusercontent.com/assets/b6Y37FthZeALduNqHicBT6FutY.woff2", weight: "400" }
    ]
  },
  ...StackDesktopFonts,
  ...getFontsFromSharedStyle(fonts)
], { supportsExplicitInterCodegen: true });

export {
  stdin_default2 as stdin_default
};